CollectMeCompanionInfo = {
    [62514] = "Unknown - Not available on live servers. [BoP]", -- Alarming Clockbot
    [10713] = "Sold by Braeanni pet supplies vendor in Dalaran for 50g. [BoE]", -- Albino Snake
    [62562] = "Sold by Irisee (Exodar Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Draenei race or Champion of the Exodar. [BoE]", -- Ammen Vale Lashling
    [10685] = "Sold by Magus Tirth in Thousand Needles for 1G. [BoE]", -- Ancona Chicken
    [62746] = "Reward from A Champion Rises quest at the Argent Tournament. [BoP]", -- Argent Gruntling
    [62609] = "Reward from A Champion Rises quest at the Argent Tournament. [BoP]", -- Argent Squire
    [89670] = "Reward from Critter Kill Squad guild achievement (Kill 50,000 critters). [BoP]", -- Armadillo Pup
    [10696] = "Rare zone drop in Winterspring. [BoE]", -- Azure Whelpling
    [61855] = "Obtained by getting online during the 4th anniversary of World of Warcraft. Unique [BoA]", -- Baby Blizzard Bear
    [25849] = "Unknown - Not available on live servers. [BoE]", -- Baby Shark
    [40549] = "Obtained from a lootcard of the WoW Trading Card Game: Through the Dark Portal. [BoP]", -- Bananas
    [10714] = "Sold by Xan'tish in Orgrimmar for 50S. [BoE]", -- Black Kingsnake
    [10675] = "Chance to drop from all NPCs in Hillsbrad Foothills. [BoE]", -- Black Tabby Cat
    [75134] = "Sold by Jepetto (or his assistant) in Dalaran for 50g. [BoP]", -- Blue Clockwork Rocket Bot
    [36031] = "Sold by Dealer Rashaad in Netherstorm for 10G. [BoE]", -- Blue Dragonhawk Hatchling
    [78683] = "Reward from Egg Wave quest in Mount Hyjal. [BoP]", -- Blue Mini Jouster
    [35907] = "Sold by Sixx in the Exodar for 50S. [BoE]", -- Blue Moth
    [10673] = "Sold by Donni Anthania in Elwynn Forrest for 40S. [BoE]", -- Bombay Cat
    [93823] = "Reward from Lawn of the Dead quest in Hillsbrad Foothills. [BoP]", -- Brazie's Sunflower
    [10709] = "Sold by Halpa in Thunder Bluff for 40S. [BoE]", -- Brown Prairie Dog
    [35239] = "Sold by Dealer Rashaad in Netherstorm for 10G. [BoE]", -- Brown Rabbit
    [10716] = "Sold by Xan'tish in Orgrimmar for 50S. [BoE]", -- Brown Snake
    [65358] = "Sold by Breanni pet supplies vendor in Dalaran for 50g [BoE]", -- Calico Cat
    [75613] = "Obtained after collecting 150 companions. [BoP]", -- Celestial Dragon
    [46426] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest. [BoP]", -- Chuck
    [90523] = "Requires 100 Dwarf Archaeology Fragments. [BoP]", -- Clockwork Gnome
    [54187] = "Contained in Gaily Wrapped Present during Winter's Veil 2007. [BoP]", -- Clockwork Rocket Bot
    [61351] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered. [BoE]", -- Cobra Hatchling
    [10680] = "Sold by Narkk in Stranglethorn Vale for 40S. [BoE]", -- Cockatiel
    [10688] = "Sold by Jeremiah Payson in Undercity or Dealer Rashaad in Netherstorm for 50S. [BoE]", -- Cockroach
    [69452] = "Given to players who have an active Blizzard Authenticator linked to their account. Unique [BoP]", -- Core Hound Pup
    [10674] = "Sold by Donni Anthania in Elwynn Forest for 40S. [BoE]", -- Cornish Rex Cat
    [84263] = "Requires 150 Tol'vir Archaeology Fragments. [BoE]", -- Crawling Claw
    [10717] = "Sold by Xan'tish in Orgrimmar or Dealer Rashaad in Netherstorm for 50S. [BoE]", -- Crimson Snake
    [10697] = "Rare zone drop in the Wetlands. [BoE]", -- Crimson Whelpling
    [65381] = "Obtained from Dalaran Children's Week quest. [BoP]", -- Curious Oracle Hatchling
    [65382] = "Obtained from Dalaran Children's Week quest. [BoP]", -- Curious Wolvar Pup
    [89039] = "Unlocked by United Nations guild achievement (Raise 55 reputations to Exalted). Unique [BoP]", -- Dark Phoenix Hatchling
    [10695] = "Dropped by whelps, broodlings, and hatchlings in Badlands, Burning Steppes, Dustwallow Marsh, and Wetlands. [BoE]", -- Dark Whelpling
    [67413] = "Contained in rare spawn Dart's Nest in Dustwallow Marsh. [BoE]", -- Darting Hatchling
    [82173] = "Crafted by engineers. [BoP]", -- De-Weaponized Mechanical Companion
    [94070] = "Gift for attendees of BlizzCon 2010 or for buying streaming coverage. Unique [BoP]", -- Deathy
    [67414] = "Drops in Wailing Caverns from Deviate Guardian and Deviate Ravager. [BoE]", -- Deviate Hatchling
    [25162] = "Contained in Oozing Bag which is dropped by most of ooze and slime mobs in the WOW Classic high level zones. Unique [BoE]", -- Disgusting Oozeling
    [45127] = "Obtained from a lootcard of the WoW Trading Card Game: March of the Legion. [BoP]", -- Dragon Kite
    [62508] = "Sold by Derrick Brindlebeard (Ironforge Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Dwarf race or Champion of Ironforge. [BoE]", -- Dun Morogh Cub
    [62513] = "Sold by Freka Bloodaxe (Orgrimmar Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Orc race or Champion of Orgrimmar. [BoE]", -- Durotar Scorpion
    [87863] = "Not available to players. Unique [BoP]", -- Eat the Egg
    [40614] = "Reward from the Outland Children's Week questline. Unique [BoP]", -- Egbert
    [93838] = "Obtained from mining Elementium nodes. [BoE]", -- Elementium Geode
    [62516] = "Sold by Corporal Arthur Flew (Stormwind Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Human race or Champion of Stormwind. [BoE]", -- Elwyn Lamb
    [10698] = "Dropped by Noxious Whelp in Feralas. [BoE]", -- Emerald Whelpling
    [62564] = "Sold by Trellis Morningsun (Silvermoon Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Blood Elf race or Champion of Silvermoon [BoE]", -- Enchanted Broom
    [93836] = "Crafted by enchanters. BoP formula is sold by Agatian Fallanos in Twilight Highlands. [BoE]", -- Enchanted Lantern
    [48408] = "Obtained by winning a battleground during Beijing 2008 Summer Olympics. Unique [BoP]", -- Essence of Competition
    [49964] = "Obtained from a lootcard of the WoW Trading Card Game: Hunt for Illidan. [BoP]", -- Ethereal Soul-Trader
    [26533] = "Contained in the presents under the christmas trees during Winter Veil. [BoE]", -- Father Winter's Helper
    [36034] = "Dropped by Bogflare Needler in Zangamarsh. [BoE]", -- Firefly
    [84752] = "Requires 85 Fossil Archaeology Fragments. [BoP]", -- Fossilized Hatchling
    [90637] = "Dropped by Baradin Foxes in Tol Barad Peninsula. [BoP]", -- Fox Kit
    [74932] = "Contained in Satchel of Chilled Goods, rewarded once daily for killing Ahune during Midsummer Fire Festival. Unique [BoP]", -- Frigid Frostling
    [52615] = "Included in the WotLK Collector's Edition. [BoA]", -- Frosty
    [53316] = "Sold by Darahir in the Dalaran Sewers for 40G. [BoP]", -- Ghostly Skull
    [59250] = "Can be fished up in the Dalaran Sewers. [BoP]", -- Giant Sewer Rat
    [78685] = "Reward from Egg Wave quest in Mount Hyjal. [BoP]", -- Gold Mini Jouster
    [36027] = "Sold by Jilanne in Eversong Woods for 50S. [BoE]", -- Golden Dragonhawk Hatchling
    [45174] = "Gift for attendess of the 2007 Blizzard Worldwide Invitational", -- Golden Pig
    [10707] = "Sold by Shylenai in Darnassus for 50S. [BoE]", -- Great Horned Owl
    [10683] = "Dropped by Defias Pirate in the Deadmines. [BoE]", -- Green Wing Macaw
    [66030] = "Free gift for US and EU attendees of BlizzCon 2009 or buying PVP coverage of BlizzCon 2009. Unique [BoP]", -- Grunty
    [69535] = "Blizzard Online Store Pet, included when purchasing the Gryphon Hatchling Stuffed Animal. Unique [BoP]", -- Gryphon Hatchling
    [92397] = "Unlocked by Profit Sharing guild achievement (Loot 100,000 gold from creatures). [BoP]", -- Guild Herald (Alliance)
    [92398] = "Unlocked by Profit Sharing guild achievement (Loot 100,000 gold from creatures). [BoP]", -- Guild Herald (Horde)
    [92395] = "Unlocked by Horde Slayer guild achievement, purchased from Shay Pressler in Stormind City. [BoP]", -- Guild Page (Alliance)
    [92396] = "Unlocked by Alliance Slayer guild achievement, purchased from Goram in Orgrimmar. [BoP]", -- Guild Page (Horde)
    [67415] = "Drops in Zul'Drak from Gundrak Raptor. [BoE]", -- Gundrak Hatchling
    [27241] = "Offered as a fan websites gift around Christmas 2006 in Europe. Unique [BoA]", -- Gurky
    [10706] = "Sold by Shylenai in Darnassus for 50S. [BoE]", -- Hawk Owl
    [30156] = "Obtained from a lootcard of the WoW Trading Card Game: Heroes of Azeroth. [BoP]", -- Hippogryph Hatchling
    [10682] = "Dropped by Bloodsail Mobs in Strangethorn (very very rare). [BoE]", -- Hyacinth Macaw
    [66520] = "Available Oct. 19 - Nov. 24, 2009 on Chinese realms only. [BoA]", -- Jade Tiger
    [23811] = "Reward from Quest Spawn of Jubjub stared by Morja at Darkmoon Faire. Unique [BoP]", -- Jubling
    [61472] = "Obtained in the secret room in Dalaran which you can enter after completing the Higher Learning Achievment. Unique [BoP]", -- Kirin Tor Familiar
    [93624] = "Obtained from a lootcard of the WoW Trading Card Game: Worldbreaker. Unique [BoP]", -- Landro's Lil' XT
    [67416] = "Contained in rare spawn Takk's Nest in The Barrens. [BoE]", -- Leaping Hatching
    [19772] = "Crafted by engineers (very rare schematic). [BoE]", -- Lifelike Toad
    -- [94716] = "Removed in beta build 13241. Unique [BoP]",	-- Lil' Alexstrasza
    [87344] = "Included in the Cataclysm Collector's Edition. [BoA]", -- Lil' Deathwing
    [69677] = "Purchased from Blizzard's online store. Unique [BoA]", -- Lil' K.T.
    [95787] = "Purchased from Blizzard's online store. Unique [BoA]", -- Lil' Ragnaros
    [15049] = "Crafted by Engineers. BoP schematic drops in Gnomeregan from Arcane Nullifier X-21, Crowd Pummeler 9-60, Peacekeeper Security Suit. [BoE]", -- Lil' Smoky
    [75906] = "Purchased from Blizzard's Online Store. Unique [BoA]", -- Lil' XT
    [61991] = "Reward for the Lil' Game Hunter Achievment (collect 75 companions). [BoP]", -- Little Fawn
    [23429] = "Unknown - Not available on live servers. [BoE]", -- Loggerhead Snapjaw
    [40405] = "Gift for attendess of the 2007 Blizzard Worldwide Invitational, Chinese and Korean servers only. Unique [BoA]", -- Lucky
    [24988] = "Included in the Burning Crusade Collector's Edition. [BoA]", -- Lurky
    [93837] = "Crafted by enchanters. BoP formula is sold by Senthii in Twilight Highlands. [BoE]", -- Magic Lamp
    [33050] = "One of the wishes from Mr Pinchy which can be fished from the pools in Skettis. [BoP]", -- Magical Crawdad
    [35156] = "Sold by Dealer Rashaad in Netherstorm for 40G. [BoE]", -- Mana Wyrmling
    [12243] = "Reward when you complete the 3 OOX Quests in Feralas, Tanaris and Hinterlands. [BoE]", -- Mechanical Chicken
    [4055] = "Crafted by engineers. [BoE]", -- Mechanical Squirrel
    [62674] = "Sold by Rillie Spindlenut (Gnomeregan Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Gnome race or Champion of Gnomeregan. [BoE]", -- Mechanopeep
    [17708] = "Included in the WoW Classic Collector's Edition. [BoA]", -- Mini Diablo
    [78381] = "Included in the Starcraft II Collector's Edition. [BoA]", -- Mini Thor
    [53082] = "Gift for attendess of the 2008 Blizzard Worldwide Invitational. [BoA]", -- Mini Tyrael
    [39181] = "Reward for the quest Skywing started by Skywing in Terokkar Forest. [BoP]", -- Miniwing
    [43918] = "Obtained by using Hex Sticks on the frogs in Zul Aman. Unique [BoP]", -- Mojo
    [95786] = "Purchased from Blizzard's Online Store. Unique [BoA]", -- Moonkin Hatchling (Alliance)
    [95909] = "Purchased from Blizzard's Online Store. Unique [BoA]", -- Moonkin Hatchling (Horde)
    [55068] = "Gift for merging World of Warcraft account into Battle.net, available on all future characters. Account must be created before offer is removed. [BoP]", -- Mr. Chilly
    [93739] = "Contained in Hidden Stash, dropped from mobs in Eastern Plaguelands, after completion of Fiona's Lucky Charm quest. [BoP]", -- Mr. Grubbs
    [28739] = "Reward for the Stormwind or Orgrimmar Children's Week questline. Unique [BoP]", -- Mr. Wiggles
    [43698] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest. [BoP]", -- Muckbreath
    [62542] = "Sold by Doru Thunderhorn (Thunder Bluff Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Tauren race or Champion of Thunder Bluff. [BoE]", -- Mulgore Hatchling
    [63318] = "Obtained by playing 200 arena matches on the arena tournament server. Unique [BoP]", -- Murkimus the Gladiator
    [24696] = "Gift for attendees of the 2005 Blizzcon. Unique [BoA]", -- Murky
    [51716] = "Sold by Grella in Skettis for 40G. You need to be exalted with the Sha'Tari Skyguard. [BoP]", -- Nether Ray Fry
    [32298] = "Included in the Burning Crusade Collector's Edition. [BoA]", -- Netherwhelp
    [67417] = "Sold by vendor Breanni in Dalaran. [BoE]", -- Obsidian Hatchling
    [69002] = "Obtained by getting online during the 5th anniversary of World of Warcraft. [BoA]", -- Onyxian Whelpling
    [10676] = "Sold by Donni Anthania in Elwynn Forest for 40S. [BoE]", -- Orange Tabby Cat
    [17707] = "Included in the WoW Classic Collector's Edition. [BoA]", -- Panda Cub
    [69541] = "Purchased from Blizzard's online store. Unique [BoA]", -- Pandaren Monk
    [40634] = "Reward from the Outland Children's Week questline. Unique [BoP]", -- Peanut
    [84492] = "Reward from completing Lost In The Deeps daily quest in Deepholm 10 times. [BoP]", -- Pebble
    [27570] = "Contained in the Gifts of Adoration from the Love is in the Air festival. [BoP]", -- Peddlefeet
    [61357] = "Sold by Sairuk in Dragonblight or Tanaika in Howling Fjord for 12G. You need to be exalted with the Kalu'ak. [BoP]", -- Pengu
    [70613] = "Reward for grouping with 100 random players using the random heroic dungeon group tool [BoP]", -- Perky Pug
    [81937] = "Crafted by Engineers. Schematic taught by Goblin Engineering Trainers. [BoE]", -- Personal World Destroyer
    [15048] = "Crafted by Engineers. Bind on pickup schematic drops in Gnomeregan from Mekgineer Thermaplugg. [BoE]", -- Pet Bombling
    [46599] = "Dropped by Kael'thas Sunstrider in Magister's Terrace. Unique [BoP]", -- Phoenix Hatchling
    [44369] = "Sold by Brewfest vendors for 100 Brewfest Prize Tokens. [BoP]", -- Pint-Sized Pink Pachyderm
    [61773] = "Obtained after getting the Pilgrim Achievement. [BoP]", -- Plump Turkey
    [28505] = "Obtained by a Coca Cola event in China only. Unique [BoP]", -- Poley
    [61350] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered. [BoE]", -- Proto-Drake Whelp
    [67418] = "Contained in rare spawn Ravasaur Matriarch's Nest in Un'Goro Crater. [BoE]", -- Ravasaur Hatchling
    [67419] = "Contained in rare spawn Razormaw Matriarch's Nest in Wetlands [BoE]", -- Razormaw Hatchling
    [67420] = "Rare zone drop in Northern Stranglethorn, Stranglethorn Vale, and The Cape of Stranglethorn. [BoE]", -- Razzashi Hatchling
    [36028] = "Sold by Jilanne in Eversong Woods for 50S. [BoE]", -- Red Dragonhawk Hatchling
    [35909] = "Sold by Dealer Rashaad in Netherstorm for 10G. [BoE]", -- Red Moth
    [45125] = "Obtained from a lootcard of the WoW Trading Card Game: March of the Legion. [BoP]", -- Rocket Chicken
    [89929] = "Unknown - Not available on live servers. [?]", -- Rumbling Rockling
    [89472] = "Requires honored reputation with Baradin's Wardens (Alliance) or Hellscream's Reach (Horde). [BoP]", -- Rustberg Seagull
    [45890] = "Contained in Ice Chest which is dropped by Ahune in the Slave Pens during the Midsummer Festival (pre-2010) Unique [BoP]", -- Searing Scorchling
    [63712] = "Sold by Samamba (Sen'Jin Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Troll race or Champion of Sen'Jin. [BoE]", -- Sen'Jin Fetish
    [10684] = "Sold by Narkk in Stranglethorn Vale or Dealer Rashaad in Netherstorm for 40S. [BoE]", -- Senegal
    [66096] = "Obtained from Silver Covenant or Sunreavers Quartermaster for 40 Champion seals. Must be exaulted with Silver Covenant or Sunreavers. [BoE]", -- Shimmering Wyrmling
    [10677] = "Dropped by Cookie in the Deadmines or sold by Dealer Rashaad in Netherstorm for 60S. [BoE]", -- Siamese Cat
    [36029] = "Sold by Jilanne in Eversong Woods for 50S. [BoE]", -- Silver Dragonhawk Hatchling
    [45175] = "Only on Chinese realms. Unique [BoP]", -- Silver Pig
    [10678] = "Sold by Donni Anthania in Elwynn Forest for 40S. [BoE]", -- Silver Tabby Cat
    [42609] = "Dropped by the Headless Horseman and contained in Crudely Wrapped Gift and Treat Bag during Hallow's End. [BoP]", -- Sinister Squashling
    [16450] = "Reward for the quest En-Ay-Es-Tee-Why stared by Kibler in the Burning Steppes. [BoP]", -- Smolderweb Hatchling
    [46425] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest. [BoP]", -- Snarly
    [10711] = "Sold by Yarlyn Amberstill in Dun Morogh for 20S. [BoE]", -- Snowshoe Rabbit
    [68810] = "Redeemed from TCG loot code. [BoP]", -- Spectral Tiger Cub
    [28738] = "Reward for the Stormwind or Orgrimmar Children's Week questline. Unique [BoP]", -- Speedy
    [48406] = "Obtained by winning a battleground during Beijing 2008 Summer Olympics. Unique [BoP]", -- Spirit of Competition
    [28871] = "Sold by Midsummer Supplier and Midsummer Merchant in the capital cities for 350 Burning Blossoms during the Midsummer's Festival. Unique [BoP]", -- Spirit of Summer
    [61725] = "Can be bought for 100 Chocolate Eggs or random drop in an Egg on the Noblegarden festival. [BoP]", -- Spring Rabbit
    [15067] = "Obtained by Freedom for All Creatures Quest started by Kindal Moonweaver in Feralas and dropped by Sprite Darters in Feralas. [BoP]", -- Sprite Darter Hatchling
    [40990] = "Reward for the Shop Smart, Shop Pet...Smart Achievment (collect 50 companions). [BoP]", -- Stinker
    [62561] = "Contained in the Bag of Fishing Treasures which is a reward from the Northrend Fishing daily quests. [BoP]", -- Strand Crawler
    [89930] = "Unknown - Not available on live servers. [?]", -- Swirling Stormling
    [62491] = "Sold by Rook Hawkfist (Darnassus Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Night Elf race or Champion of Darnassus. [BoE]", -- Teldrassid Sproutling
    [61348] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered. [BoE]", -- Tickbird Hatchling
    [93813] = "Reward from SEVEN! YUP! (Alliance) or Not Fireflies, Flameflies (Horde) quest in Burning Steppes. [BoP]", -- Tiny Flamefly
    [23531] = "Special promotion only on Chinese realms. [BoP]", -- Tiny Green Dragon
    [23530] = "Special promotion only on Chinese realms. [BoP]", -- Tiny Red Dragon
    [91343] = "Dropped by Jadefang in Deepholm while doing the Underground Economy daily quest for the Therazane faction. [BoP]", -- Tiny Shale Spider
    [45082] = "Sold by Mycah in Zangamarsh for 30 Glowcaps. You need to be exalted with Sporeggar. [BoP]", -- Tiny Sporebat
    [26045] = "Contained in Gaily Wrapped Present during Winter's Veil. [BoE]", -- Tiny Snowman
    [62510] = "Sold by Eliza Killian (Undercity Quartermaster) at the Argent Tournament for 40 Champion's Seals. Requires Undead race or Champion of the Undercity. [BoE]", -- Tirisfal Batling
    [43697] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest. [BoP]", -- Toothy
    [71840] = "Drops from Apothecary Hummel in Shadowfang Keep during Love is in the Air holiday festival. [BoP]", -- Toxic Wasteling
    [26010] = "Crafted by engineers. [BoE]", -- Tranquil Mechanical Yeti
    [10704] = "Sold by Flik on Darkmoon Faire for 1G. [BoE]", -- Tree Frog
    [68767] = "Redeemed from TCG loot code. [BoP]", -- Tuskarr Kite
    [51851] = "Dropped by Prince Tenris Mirkblood in Karazhan on the pre WotLK Event. [BoP]", -- Vampiric Batling
    [65682] = "Special promotion from the www.mountaindewgamefuel.com with a valid battle.net account, available from May 15 - Aug. 20, 2009. US servers only. [BoP]", -- Warbot
    [13548] = "Reward for Quest CLUCK! started by Chickens in Westfall after you /chicken to them for a while. [BoP]", -- Westfall Chicken
    [89931] = "Unknown - Not available on live servers. [?]", -- Whirling Waveling
    [28740] = "Reward for the Stormwind or Orgrimmar Children's Week questline. Unique [BoP]", -- Whiskers the Rat
    [10679] = "Sold by Lil Timmy in Stormwind for 1G (Limited Supply). [BoE]", -- White Kitten
    [35911] = "Sold by Sixx in the Exodar for 50S. [BoE]", -- White Moth
    [61349] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered. [BoE]", -- White Tickbird Hatchling
    [30152] = "Unknown - Not available on live servers. [BoP]", -- White Tiger Cub
    [40613] = "Reward from the Outland Children's Week questline. Unique [BoP]", -- Willy
    [69536] = "Blizzard Online Store Pet, included when purchasing the Wind Rider Cub Stuffed Animal. Unique [BoP]", -- Wind Rider Cub
    [26529] = "Contained in Gaily Wrapped Present during Winter's Veil. [BoE]", -- Winter Reindeer
    [26541] = "Contained in Gaily Wrapped Present during Winter's Veil. [BoE]", -- Winter's Little Helper
    [65046] = "Alliance: Reward from Remembrance of Auberdine quest in Darkshore; Horde: Sold by Apothecary Furrows in Darkshore. [BoP]", -- Withers
    [39709] = "Sold by Larkin Thunderbrew in Ironforge and Ray'ma in Orgrimmar for 50S. [BoP]", -- Wolpertinger
    [10703] = "Sold by Flik on Darkmoon Faire for 1G (Limited Supply). [BoE]", -- Wood Frog
    [15999] = "Reward for the quest Kibler's Exotic Pets stared by Kibler in the Burning Steppes. [BoP]", -- Worg Pup
    [64351] = "Not available on live servers. [BoE]", -- XS-001 Constructor Bot
    [35910] = "Sold by Sixx in the Exodar for 50S. [BoE]", -- Yellow Moth
    [17709] = "Included in the WoW Classic Collector's Edition. [BoA]", -- Zergling
    [69539] = "Promotional, was only available on Taiwan servers. [BoA]", -- Zipao Tiger
    [97638] = "Sold by Michelle De Rum in Everlook Inn located in Winterspring for 50G. [BoE]", -- Winterspring Cub
    [96571] = "Reward from 'Some Good Will Come' quest in Northern Stranglethorn. [BoP]", -- Panther Cub
    [97779] = "Reward from 'An Old Friend' quest in Zul'Gurub. [BoP]", -- Lashtail Hatchling
    [93817] = "Reward for the Stormwind or Orgrimmar Children's Week questline. [BoP]", -- Scooter the Snail
    [99578] = "Purchased from Blizzard's online store. [BoA]", -- Cenarion Hatchling
    [98571] = "Obtained from Archaeology - Rare Fossil, 120 Fragments. [BoP]", -- Pterrordax Hatchling
    [98587] = "Obtained from Archaeology - Rare Troll, 100 Fragments. [BoP]", -- Voodoo Figurine
    [98079] = "Reward from the Outland Children's Week questline. Unique [BoP]", -- Legs
    [101986] = "Reward from Stormwind Quest, 'Blown Away' given by Vin behind the Orphanage. [BoP]", -- Alliance Balloon
    [96817] = "Loot reward from War of the Elements TCG expansion. [BoP]", -- Landro's Lichling
    [100970] = "Reward from 'Petting Zoo' achivement (obtain 100 companions) [BoP].", -- Nuts
    [101424] = "Reward from 'Menagerie' achivement (obtain 125 companions) [BoP].", -- Brilliant Kaliri
    [101989] = "Reward for Horde for 'Blown Away' quest in Orgimmar. [BoP]", -- Summon Horde Balloon
    [99668] = "Purchased from Ayla Shadowstorm in the Molten Front after completing quest Filling the Moonwell. [BoP]", -- Crimson Lasher
    [99663] = "Purchased from Varlan Highbough in the Molten Front after completing quest Calling the Ancients. [BoP]", -- Hyjal Bear Cub
    [96819] = "Loot reward from Twilight of the Dragons TCG expansion. [BoP]", -- Nightsaber Cub
    [100684] = "Reward from the quest Anson's Crate as part of the Hollows End holiday event. [BoP]", -- Creepy Crate
    [100330] = "Sold by Chub or Dorothy Candy & Toy Vendor as part of the Hollows End holiday event for 150 Tricky Treats. [BoP]", -- Feline Familiar
    [100576] = "Guild must complete the achivement 'Dragonwrath, Tarecgosa's Rest - Guild Edition' and anyone with exalted guild rep can purchase it from the guild vendor. [BoA]", -- Lil' Tarecgosa
    [101606] = "Sent to attendees of BlizzCon 2011 or purchasers of the live stream. Unique [BoP]", -- Murkablo
    [105122] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Cub
    [103076] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Balloon
    [101733] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Monkey
    [103544] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Tonk
    [103074] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Turtle
    [103549] = "Purchased from Lhara in the Darkmoon Faire for 90 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Zeppelin
    [101493] = "Loot reward from Throne of the Tides TCG expansion.  [BoP]", -- Purple Puffer
    [103588] = "Fished from the waters surrounding the Darkmoon Isle.  [BoP]", -- Sea Pony
    [105633] = "Included in the Diablo 3 Collector's Edition.  [BoA]", -- Fetish Shaman
    [102317] = "Loot reward from Crown of Heaven TCG expansion.  [BoP]", -- Gregarious Grell
    [102353] = "Loot reward from Tomb of the Forgotten TCG expansion.  [BoP]", -- Sand Scarab
    [103125] = "Chane of dropping from a Stolen Present obtained from the quest 'You're a Mean One...'. Unique [BoP]", -- Lumpy
    [110029] = "Unknown.  [BoP]", -- Soul of the Aspects
    [104047] = "Obtained during the Lunar Festival world event.  [BoP]", -- Lunar Lantern
    [104049] = "Obtained during the Lunar Festival world event.  [BoP]", -- Festival Lantern
}