CollectMeMountInfo = {
    [60025] = "Reward from Achievement Leading the Cavalry (collect 50 Mounts)", -- Albino Drake
    [40192] = "Dropped by Kael'Thas Sunstrider in Tempest Keep (Raid)", -- Ashes of Al'ar
    [41514] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Azure Netherwing Drake
    [59567] = "Reward from 25-man Eye of Eternity (Malygos). Unique [BoP]", -- Azure Drake
    [59650] = "Dropped by Sartharion (10) if you kill him in Hard Mode with three drakes alive", -- Black Drake
    [59976] = "Reward from Achievment Heroic: Glory of the Raider before Patch 3.1", -- Black Proto-Drake
    [59996] = "Dropped by Skadi the Ruthless in Uthgarde Pinnacle Heroic", -- Blue Proto-Drake
    [25953] = "Dropped by the Trash Mobs in Ahn'Qiraji", -- Blue Qiraji Battle Tank
    [39803] = "Sold by Grella in Terokkar Forest for 200G. You need to be exalted with Sha'tari Skyguard", -- Blue Riding Nether Ray
    [59569] = "Dropped by Infinite Corruptor in The Culling of Stratholme. He is only available in the timed run", -- Bronze Drake
    [58615] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 4. Unique [BoP]", -- Brutal Nether Drake
    [43927] = "Sold by Fedryen Swiftspear in Zangamarsh for 2000G. You need to be exalted with the Cenarion Expedition", -- Cenarion War Hippogryph
    [41515] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Cobalt Netherwing Drake
    [39315] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 70G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Cobalt Riding Talbuk
    [34896] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 100G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Cobalt War Talbuk
    [73313] = "Contained in Unsealed Chest, which drops from The Lich King when a player in the raid has the quest 'The Lich King's Last Stand' in their quest log (BoE)", -- Crimson Deathcharger
    [68188] = "Reward from completing 25-ToGC with no deaths and 50 attempts remaining. No longer obtainable. [BoP]", -- Crusader's Black Warhorse
    [68187] = "Reward from completing 25-ToGC with no deaths and 50 attempts remaining. No longer obtainable. [BoP]", -- Crusader's White Warhorse
    [39316] = "Sold by Aldraan (Alliance) and Coreiel (Horde) in Nagrand for 70 Halaa Battle Tokens and 15 Halaa Research Tokens", -- Dark Riding Talbuk
    [34790] = "Sold by Aldraan (Alliance) and Coreiel (Horde) in Nagrand for 100 Halaa Battle Tokens and 20 Halaa Research Tokens", -- Dark War Talbuk
    [36702] = "Dropped by Attumen the Huntsman in Karazhan", -- Fiery Warhorse
    [65439] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 6. Unique [BoP]", -- Furious Gladiator's Frost Wyrm
    [49379] = "Dropped by Coren Direbrew in Blackrock Depths during the Brewfest", -- Great Brewfest Kodo
    [61294] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered", -- Green Proto-Drake
    [26056] = "Dropped by the Trash Mobs in Ahn'Qiraji", -- Green Qiraji Battle Tank
    [39798] = "Sold by Grella in Terokkar Forest for 200G. You need to be exalted with Sha'tari Skyguard", -- Green Riding Nether Ray
    [48025] = "Dropped by the Headless Horseman in Scarlet Monastery during Hallows End", -- Headless Horseman's Mount
    [72286] = "Dropped by The Lich King in Heroic 25 mode", -- Invincible
    [41513] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Onyx Netherwing Drake
    [60021] = "Reward from Achievement Glory of the Raider before Patch 3.1", -- Plagued Proto-Drake
    [41516] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Purple Netherwing Drake
    [39801] = "Sold by Grella in Terokkar Forest for 200G. You need to be exalted with Sha'tari Skyguard", -- Purple Riding Nether Ray
    [41252] = "Dropped by Anzu in the Sethek Halls Heroic.", -- Raven Lord
    [59570] = "Sold by Cielstrasza in Dragonblight for 1600G. You need to be exalted with the Wyrmrest Accord", -- Red Drake
    [59961] = "Reward from the Achievement Glory of the Hero", -- Red Proto-Drake
    [26054] = "Dropped by the Trash Mobs in Ahn'Qiraji (rare) [BoP]", -- Red Qiraji Battle Tank
    [39800] = "Sold by Grella in Terokkar Forest for 200G. You need to be exalted with Sha'tari Skyguard", -- Red Riding Nether Ray
    [67336] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 7. Unique [BoP]", -- Relentless Gladiator's Frost Wyrm
    [17481] = "Dropped by Baron Rivendare in Stratholme", -- Rivendare's Deathcharger
    [39802] = "Sold by Grella in Terokkar Forest for 200G. You need to be exalted with Sha'tari Skyguard", -- Silver Riding Nether Ray
    [39317] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 70G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Silver Riding Talbuk
    [34898] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 100G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Silver War Talbuk
    [43900] = "Dropped by Coren Direbrew in Blackrock Depths during Brewfest, Also Sold by Pol Amberstill in Dun Morogh and Driz Tumblequick in Durotar if you purchased Honorary Brewer Hand Stamp during 2007 Brewfest", -- Swift Brewfest Ram
    [24242] = "Dropped by Bloodlord Mandokir in Zul Gurub prior to patch 4.0.3", -- Swift Razzashi Raptor
    [46628] = "Dropped by Kael'thas Sunstrider in Magister's Terrace Heroic", -- Swift White Hawkstrider
    [24252] = "Dropped by High Priest Thekal in Zul Gurub prior to patch 4.0.3", -- Swift Zulian Tiger
    [39318] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 70G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Tan Riding Talbuk
    [34899] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 100G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- Tan War Talbuk
    [60002] = "Dropped by Time-Lost Proto Drake in the Storm Peaks", -- Time-Lost Proto-Drake
    [59571] = "Dropped by Sartharion (25) if you kill him in Hard Mode with three drakes alive", -- Twilight Drake
    [41517] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Veridian Netherwing Drake
    [41518] = "Sold by Drake Dealer Hurlunk in Shadowmoon Valley for 200G. You need to be exalted with Netherwing", -- Violet Netherwing Drake
    [60024] = "Reward from the Achievement What A Long, Strange Trip It's Been", -- Violet Proto-Drake
    [54753] = "Contained in Hyldnir Spoils which is a quest reward for the Brunhildar daily quests", -- White Polar Bear Mount
    [39319] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 70G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- White Riding Talbuk
    [34897] = "Sold by Provisioner Nasela and Trader Narasu in Nagrand for 100G. You need to be exalted with the Kurenai (Alliance) or the Mag'Har (Horde)", -- White War Talbuk
    [71810] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 8. Unique [BoP]", -- Wrathful Gladiator's Frost Wyrm
    [26055] = "Dropped by the Trash Mobs in Ahn'Qiraji", -- Yellow Qiraji Battle Tank
    [43688] = "Contained in Ashli's Bag which was only obtainable by doing a Zul Aman timed run before Patch 3.0", -- Amani War Bear
    [51412] = "Obtained from a lootcard of the WoW Trading Card Game: Drums of War", -- Big Battle Bear
    [58983] = "Gift for attendees of the 2008 Blizzcon", -- Big Blizzard Bear
    [26656] = "Only obtained by the player who rang the gong on first opening Ahn'Qiraji", -- Black Qiraji Battle Tank
    [43899] = "Sold by Pol Amberstill in Dun Morogh and Driz Tumblequick in Durotar if you purchased Honorary Brewer Hand Stamp during 2007 Brewfest", -- Brewfest Ram
    [44744] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 2", -- Merciless Nether Drake
    [30174] = "Obtained from a lootcard of the WoW Trading Card Game: Heroes of Azeroth", -- Riding Turtle
    [42776] = "Obtained from a lootcard of the WoW Trading Card Game: Fires of Outland", -- Spectral Tiger
    [37015] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 1", -- Swift Nether Drake
    [42777] = "Obtained from a lootcard of the WoW Trading Card Game: Fires of Outland", -- Swift Spectral Tiger
    [49322] = "Obtained by Recruiting a Friend whom continues playing for at least 2 months", -- Swift Zhevra
    [49193] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 3", -- Vengeful Nether Drake
    [46197] = "Obtained from a lootcard of the WoW Trading Card Game: Servants of the Betrayer", -- X-51 Nether-Rocket
    [46199] = "Obtained from a lootcard of the WoW Trading Card Game: Servants of the Betrayer", -- X-51 Nether-Rocket X-TREME
    [75973] = "Obtained by Recruiting a Friend whom continues playing for at least 2 months", -- X-53 Touring Rocket
    [65917] = "Obtained from a lootcard 'El Pollo Grande' of the WoW Trading Card Game: Fields of Honor", -- Magic Rooster
    [64927] = "Won by the top 0.5% rated Arena groups in the battlegroup in Season 5", -- Deadly Gladiator's Frost Wyrm
    [63956] = "Reward from Heroic: Glory of the Ulduar Raider Achievement", -- Ironbound Proto-Drake
    [63963] = "Reward from Glory of the Ulduar Raider Achievement", -- Rusted Proto-Drake
    [63796] = "Drops from Yogg-Saron if you have no Keepers assisting you in 25 man Ulduar", -- Mimiron's Head
    [64659] = "Ravasaur trainer Mor'vek has returned to Un'Goro and will offer to help Horde players raise and train a Venomhide Ravasaur as a mount... if they can survive the creature's deadly poison.", -- Venomhide Ravasaur
    [64731] = "Can be fished from Northrend Fishing Pools", -- Sea Turtle
    [63844] = "Sold by the City Quartermasters at the Argent Tournament for 150 Champion's Seals", -- Argent Hippogryph
    [67466] = "Sold by Dame Evniki Kapsalis, Crusader's Quartermaster at the Argent Tournament for 100 Champion's Seals. Requires level 40 and Riding 150. Must have the Argent Champion title. ", -- Argent Warhorse
    [69395] = "Rare drop from Onxyia in 10 or 25 man encounters", -- Onyxian Drake
    [59568] = "Reward from 10-man Eye of Eternity (Malygos). Also contained in Satchel of Exotic Mysteries. Unique [BoP]", -- Blue Drake
    [66087] = "This mount can be purchased from the Silver Covenant quartermaster at Argent Tournament for 150 Champion Seals and you must be exalted with Silver Covenant.", -- Silver Covenant Hippogryph
    [65917] = "Obtained from a lootcard of the WoW Trading Card 'El Pollo Grande'.", -- Magic Rooster
    [72807] = "Obtained from Glory of the Icecrown Raider (25 man) Achievement.", -- Icebound Frostbrood Vanquisher
    [72808] = "Obtained from Glory of the Icecrown Raider (10 man) Achievement.", -- Bloodbathed Frsotbrood Vanquisher
    [71342] = "Drops from Apothecary Hummel in Shadowfang Keep during Love is in the Air holiday festival.", -- Big Love Rocket
    [75614] = "Purchased from the Blizzard online store, Available on all characters present and future. Flies upto 310% if you own another 310% mount also rides on the ground as well.", -- Celestial Steed
    [75207] = "Reward from The Abyssal Ride quest in Kelp'thar Forest, requires Level 80 and Expert Riding. [BoP]", -- Abyssal Seahorse
    [88748] = "Sold by Blacksmith Abasi Ramkahen Quartermaster in Uldum, requires Level 40, Journeyman Riding and Ramkahen Exalted rep. [BoP]", -- Brown Riding Camel
    [84751] = "Found while using Survey from Archaeology and requires 100 Fragments to complete. Requires Level 40 and Journeyman riding. ", -- Fossilized Raptor
    [88749] = "Sold by Blacksmith Abasi Ramkahen Quartermaster in Uldum, requires Level 40, Journeyman Riding and Ramkahen Exalted rep. [BoP]", -- Tan Riding Camel
    [88741] = "Sold in Tol Barad by Quartermaster Brazie for 200 Commendations. Requires Baradins Wardens Exaulted rep, level 70 and Artisan Riding. [BoP]", -- Drake of the West Wind
    [88990] = "Sold from Guild Vendor after completing the achivement Guild Glory of the Cataclysm Raider. [BoP]", -- Dark Phoenix
    [93326] = "Taught by Vial of the Sands created by Recipe: Vial of the Sands which is only found in Canopic Jars, gathered using Archaeology.  [BoE]", -- Sandstone Drake
    [88742] = "Drops from Altairus in 'Vortex Pinnacle'. Unique [BoP]", -- Drake of the North Wind
    [88746] = "Drops from Slabhide in Heroic 'The Stone Core' instance. [BoP]", -- Viteous Stone Drake
    [88331] = "Reward from the achivement 'Glory of the Cataclysm Hero'. [BoP]", -- Volcanic Stone Drake
    [88750] = "From Dormus the Camel-Hoarder in Feralas after finding the figurines in Uldum.", -- Grey Riding Camel
    [88718] = "This mount is a drop from the rare-spawn Aeonaxx in Deepholm. [BoP]", -- Phosphorescent Stone Drake
    [98204] = "Drops in Zul'Aman 4.1, Must complete a timed run to get Kasha's Bag. [BoP]", -- Amani Battle Bear
    [96491] = "Drops from Bloodlord Mandokir in 4.1 Zul'Gurub!  [BoP]", -- Armored Razzashi Raptor
    [96499] = "Drops from High Priestess Kilnara in 4.1 Zul'Gurub!  [BoP]", -- Swift Zulian Panther
    [92155] = "150 Tol'vir Archaeology Fragments required, random find while doing Archaeology. [BoP]", --  Ultramarine Qiraji Battle Tank
    [74856] = "Loot card from TCG expansion Wrathgate. [BoP]", -- Blazing Hippogryph
    [98727] = "Sold from the Blizzard Online Store for 25 dollars US. [BoP]", -- Winged Guardian
    [98718] = "Dropped from rare spawn Poseidus in Shimmering Expanse.  [BoE]", -- Subdued Seahorse
    [97359] = "Reward from The Molten Front Offensive achivement. [BoP]", -- Flameward Hippogryph
    [88335] = "Reward from the achivement 'Glory of the Cataclysm Raider'. [BoP]", -- Drake of the East Wind
    [88744] = "Drops from Al'Akir raid boss in Throne of the Four Winds. [BoP]", -- Drake of the South Wind
    [97560] = "Reward from the achivement 'Glory of the Firelands Raider'. [BoP]", -- Corrupted Fire Hawk
    [101542] = "Drops from Alysrazor in the Firelands. [BoP]", -- Flametalon of Alysrazor
    [97493] = "Drops from Ragnaros in the Firelands. [BoP]", -- Pureblood Fire Hawk
    [97581] = "Loot card from the WoW Trading Card Game: War of Elements. [BoE]", -- Savage Raptor
    [74918] = "Loot card from TCG expansion 'Icecrown'. [BoE]", -- Wooly White Rhino
    [68825] = "Loot card from the WoW Trading Card Game: Twilight of the Dragons. [BoE]", -- Amani Dragonhawk
    [107203] = "Obtained by signing up for the WoW Annual Pass promotion. [BoP]", -- Tyrael's Charger
    [103081] = "Purchased from Lhara in the Darkmoon Faire for 180 Darkmoon Prize Tickets. [BoP]", -- Darkmoon Dancing Bear
    [102346] = "Purchased from Lhara in the Darkmoon Faire for 180 Darkmoon Prize Tickets. [BoP]", -- Swift Forest Strider



    -- we begin with the alliance infos
    [60114] = "Sold by Mei Francis in Dalaran for 750G", -- Armored Brown Bear
    [61229] = "Sold by Mei Francis in Dalaran for 2000G", -- Armored Snowy Gryphon
    [22719] = "Sold by Lieutenant Karter in Stormwind for 2000 honor", -- Black Battlestrider
    [470] = "Sold by Unger Statforth in the Wetlands for 10G", -- Black Stallion Bridle
    [60118] = "Reward from For The Alliance! Achievement (Kill the 4 Horde faction leaders)", -- Black War Bear
    [48027] = "Sold by Lieutenant Karter in Stormwind for 2000 honor", -- Black War Elekk
    [59785] = "Sold by Knight Dameron in Lake Wintergrasp for 2000 honor", -- Black War Mammoth
    [22720] = "Sold by Lieutenant Karter in Stormwind for 2000 honor", -- Black War Ram
    [22717] = "Sold by Lieutenant Karter in Stormwind for 2000 honor", -- Black War Steed
    [22723] = "Sold by Lieutenant Karter in Stormwind for 2000 honor", -- Black War Tiger
    [61996] = "Reward from the Mountain o' Mounts Achievement (collect 100 mounts)", -- Blue Dragonhawk
    [10969] = "Sold by Milli Featherwhistle in Dun Morogh for 10G. You must be a Gnome or exalted with Gnomeregan", -- Blue Mechanostrider
    [34406] = "Sold by Torallius the Pack Handler in the Exodar for 10G. You must be a Draenei or exalted with the Exodar", -- Brown Elekk
    [458] = "Sold by Katie Hunter in Elwynn Forest for 10G. You must be a Human or exalted with Stormwind", -- Brown Horse
    [6899] = "Sold by Veron Amberstill in Dun Morogh for 10G. You must be a Dwarf or exalted with Ironforge", -- Brown Ram
    [6648] = "Sold by Katie Hunter in Elwynn Forest for 10G. You must be a Human or exalted with Stormwind", -- Chestnut Mare
    [32239] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Ebon Gryphon
    [32235] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Golden Gryphon
    [61470] = "Sold by Lillehoff in the Storm Peaks for 10000G. You must be exalted with the Sons of Hodir", -- Grand Ice Mammoth
    [35710] = "Sold by Torallius the Pack Handler in the Exodar for 10G. You must be a Draenei or exalted with the Exodar", -- Gray Elekk
    [6777] = "Sold by Veron Amberstill in Dun Morogh for 10G. You must be a Dwarf or exalted with Ironforge", -- Gray Ram
    [35713] = "Sold by Torallius the Pack Handler in the Exodar for 100G. You must be a Draenei or exalted with the Exodar", -- Great Blue Elekk
    [35712] = "Sold by Torallius the Pack Handler in the Exodar for 100G. You must be a Draenei or exalted with the Exodar", -- Great Green Elekk
    [35714] = "Sold by Torallius the Pack Handler in the Exodar for 100G. You must be a Draenei or exalted with the Exodar", -- Great Purple Elekk
    [17453] = "Sold by Milli Featherwhistle in Dun Morogh for 10G. You must be a Gnome or exalted with Gnomeregan", -- Green Mechanostrider
    [59799] = "Sold by Lillehoff in the Storm Peaks for 1000G. You must be revered with the Sons of Hodir", -- Ice Mammoth
    [60424] = "Built by an engineer", -- Mekgineer's Chopper
    [472] = "Sold by Katie Hunter in Elwynn Forest for 10G. You must be a Human or exalted with Stormwind", -- Pinto
    [35711] = "Sold by Torallius the Pack Handler in the Exodar for 10G. You must be a Draenei or exalted with the Exodar", -- Purple Elekk
    [10873] = "Sold by Milli Featherwhistle in Dun Morogh for 10G. You must be a Gnome or exalted with Gnomeregan", -- Red Mechanostrider
    [32240] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Snowy Gryphon
    [10789] = "Sold by Lelanai in Darnassus for 10G. You must be a Night Elf or exalted with Darnassus", -- Spotted Frostsaber
    [23510] = "Sold by Thanthaldis Snowgleam in Alterac Mountains and Gaelden Hammersmith in Alterac Valley for 2000 honor", -- Stormpike Battle Charger
    [8394] = "Sold by Lelanai in Darnassus for 10G. You must be a Night Elf or exalted with Darnassus", -- Striped Frostsaber
    [10793] = "Sold by Lelanai in Darnassus for 10G. You must be a Night Elf or exalted with Darnassus", -- Striped Nightsaber
    [32242] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Blue Gryphon
    [23238] = "Sold by Veron Amberstill in Dun Morogh for 100G. You must be a Dwarf or exalted with Ironforge", -- Swift Brown Ram
    [23229] = "Sold by Katie Hunter in Elwynn Forest for 100G. You must be a Human or exalted with Stormwind", -- Swift Brown Steed
    [23221] = "Sold by Lelanai in Darnassus for 100G. You must be a Night Elf or exalted with Darnassus", -- Swift Frostsaber
    [23239] = "Sold by Veron Amberstill in Dun Morogh for 100G. You must be a Dwarf or exalted with Ironforge", -- Swift Gray Ram
    [32290] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Green Gryphon
    [23225] = "Sold by Milli Featherwhistle in Dun Morogh for 100G. You must be a Gnome or exalted with Gnomeregan", -- Swift Green Mechanostrider
    [23219] = "Sold by Lelanai in Darnassus for 100G. You must be a Night Elf or exalted with Darnassus", -- Swift Mistsaber
    [23227] = "Sold by Katie Hunter in Elwynn Forest for 100G. You must be a Human or exalted with Stormwind", -- Swift Palomino
    [32292] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Purple Gryphon
    [32289] = "Sold by Brunn Flamebeard in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Red Gryphon
    [23338] = "Sold by Lelanai in Darnassus for 100G. You must be a Night Elf or exalted with Darnassus", -- Swift Stormsaber
    [23223] = "Sold by Milli Featherwhistle in Dun Morogh for 100G. You must be a Gnome or exalted with Gnomeregan", -- Swift White Mechanostrider
    [23240] = "Sold by Veron Amberstill in Dun Morogh for 100G. You must be a Dwarf or exalted with Ironforge", -- Swift White Ram
    [23228] = "Sold by Katie Hunter in Elwynn Forest for 100G. You must be a Human or exalted with Stormwind", -- Swift White Steed
    [23222] = "Sold by Milli Featherwhistle in Dun Morogh for 100G. You must be a Gnome or exalted with Gnomeregan", -- Swift Yellow Mechanostrider
    [61425] = "Sold by Mei Francis in Dalaran for 20000G", -- Traveler's Tundra Mammoth
    [17454] = "Sold by Milli Featherwhistle in Dun Morogh for 10G. You must be a Gnome or exalted with Gnomeregan", -- Unpainted Mechanostrider
    [6898] = "Sold by Veron Amberstill in Dun Morogh for 10G. You must be a Dwarf or exalted with Ironforge", -- White Ram
    [17229] = "Sold by Rivern Frostwind in Winterspring for 100G. You must be exalted with the Wintersaber Trainers", -- Winterspring Frostsaber
    [59791] = "Sold by Mei Francis in Dalaran for 2175 Justice Points", -- Wooly Mammoth
    [61465] = "Dropped by Archavon the Stone Watcher in the Vault of Archavon (Raid)", -- Grand Black War Mammoth
    [63639] = "Sold by Irisee (Exodar Quartermaster) at the Argent Tournamen for 100 Champion's Seals. You must be a Draenei or a Champion of the Exodar", -- Exodar Elekk
    [63637] = "Sold by Rook Hawkfist (Darnassus Quartermaster) at the Argent Tournamen for 100 Champion's Seals. You must be a Night Elf or a Champion of Darnassus", -- Darnassian Mistsaber
    [63232] = "Sold by Corporal Arthur Flew (Stormwind Quartermaster) at the Argent Tournamen for 100 Champion's Seals. You must be a Human or a Champion of Stormwind", -- Storwmwind Steed
    [63636] = "Sold by Derrick Brindlebeard (Ironforge Quartermaster) at the Argent Tournamen for 100 Champion's Seals. You must be a Dwarf or a Champion of Ironforge", -- Ironforge Ram
    [63638] = "Sold by Rillie Spindlenut (Gnomeregan Quartermaster) at the Argent Tournamen for 100 Champion's Seals. You must be a Gnome or a Champion of Gnomeregan", -- Gnomeregan Mechanostrider
    [65637] = "Sold by Irisee (Exodar Quartermaster) at the Argent Tournamen for 5 Champion's Seals and 500 Gold. You must be a Draenei or a Champion of the Exodar", -- Great Red Elekk
    [65640] = "Sold by Corporal Arthur Flew (Stormwind Quartermaster) at the Argent Tournamen for 5 Champion's Seals and 500 Gold. You must be a Human or a Champion of Stormwind", -- Swift Gray Steed
    [65643] = "Sold by Derrick Brindlebeard (Ironforge Quartermaster) at the Argent Tournamen for 5 Champion's Seals and 500 Gold. You must be a Dwarf or a Champion of Ironforge", -- Swift Violet Ram
    [65638] = "Sold by Rook Hawkfist (Darnassus Quartermaster) at the Argent Tournamen for 5 Champion's Seals and 500 Gold. You must be a Night Elf or a Champion of Darnassus", -- Swift Moonsaber
    [65642] = "Sold by Rillie Spindlenut (Gnomeregan Quartermaster) at the Argent Tournamen for 500 Gold and 5 Champion's Seals. You must be a Gnome or a Champion of Gnomeregan", -- Turbostrider
    [66090] = "Sold by Hiren Loresong, Silver Covenant Quartermaster at the Argent Tournament for 100 Champion's Seals. Requires level 40 and Riding 150. Must have Silver Covenant Exaulted rep.", -- Quel'dorei Steed
    [66847] = "Sold by Lelanai in Darnassus for 10G. You must be a Night Elf or exalted with Darnassus. Requires level 20 and Riding 75.", -- Striped Dawnsaber
    [46813] = "Sold by Hiren Loresong, Silver Covenant Quartermaster at the Argent Tournament for 150 Champion's Seals. Requires level 70 and Riding 300. Must have Silver Covenant Exaulted rep.", -- Silver Covenant Hippogryph
    [68057] = "Loot from 10 man Heroic Trial of the Grand Crusader with all 50 attempts left, only one drops per raid. No longer obtainable.", -- Swift Alliance Steed'
    [92231] = "Sold from Tol Barad Alliance vendor for 165 Tol Barad Commendations at Baradin's Wardins Exalted reputation.", -- Spectral Steed
    [90621] = "Alliance mount earned by guild achivement with exalted reputation.", -- Golden King
    [100332] = "Reward from achivement 'Veteran of the Alliance' or higher.", -- Vicious War Steed

    -- now the horde mounts
    [61230] = "Sold by Mei Francis in Dalaran for 2000G", -- Armored Blue Wind Rider
    [60116] = "Sold by Mei Francis in Dalaran for 750G", -- Armored Brown Bear
    [35022] = "Sold by Winaestra in Eversong Woods for 10G. You must be a Blood Elf or exalted with Silvermoon", -- Black Hawkstrider
    [60119] = "Reward from For The Horde! Achievement (Kill the 4 Alliance faction leaders)", -- Black War Bear
    [22718] = "Sold by Raider Bork in Orgrimmar for 2000 honor", -- Black War Kodo
    [59788] = "Sold by Stone Guard Mukar in Lake Wintergrasp for 2000 honor", -- Black War Mammoth
    [22721] = "Sold by Raider Bork in Orgrimmar for 2000 honor", -- Black War Raptor
    [22724] = "Sold by Raider Bork in Orgrimmar for 2000 honor", -- Black War Wolf
    [35020] = "Sold by Winaestra in Eversong Woods for 10G. You must be a Blood Elf or exalted with Silvermoon", -- Blue Hawkstrider
    [17463] = "Sold by Zachariah Post in Tirisfal Glades for 10G. You must be an Undead or exalted with the Undercity", -- Blue Skeletal Horse
    [32244] = "Sold by Dama Wildmane in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Blue Wind Rider
    [17464] = "Sold by Zachariah Post in Tirisfal Glades for 10G. You must be an Undead or exalted with the Undercity", -- Brown Skeletal Horse
    [18990] = "Sold by Harb Clawhoof in Mulgore for 10G. You must be a Tauren or exalted with Thunder Bluff", -- Brown Kodo
    [6654] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 10G. You must be an Orc or exalted with Orgrimmar", -- Brown Wolf
    [6653] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 10G. You must be an Orc or exalted with Orgrimmar", -- Dire Wolf
    [8395] = "Sold by Zjolnir in Durotar for 10G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Emerald Raptor
    [23509] = "Sold by Grunnda Wolfheart in Alterac Valley for 2000 honor", -- Frostwolf Howler
    [61469] = "Sold by Lillehoff in the Storm Peaks for 10000G. You must be exalted with the Sons of Hodir", -- Grand Ice Mammoth
    [18989] = "Sold by Harb Clawhoof in Mulgore for 100G. You must be a Tauren or exalted with Thunder Bluff", -- Gray Kodo
    [23249] = "Sold by Harb Clawhoof in Mulgore for 100G. You must be a Tauren or exalted with Thunder Bluff", -- Great Brown Kodo
    [23248] = "Sold by Harb Clawhoof in Mulgore for 100G. You must be a Tauren or exalted with Thunder Bluff", -- Great Gray Kodo
    [23247] = "Sold by Harb Clawhoof in Mulgore for 100G. You must be a Tauren or exalted with Thunder Bluff", -- Great White Kodo
    [17465] = "Sold by Zachariah Post in Tirisfal Glades for 100G. You must be an Undead or exalted with the Undercity", -- Green Skeletal Warhorse
    [32245] = "Sold by Dama Wildmane in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Green Wind Rider
    [59797] = "Sold by Lillehoff in the Storm Peaks for 1000G. You must be revered with the Sons of Hodir", -- Ice Mammoth
    [55531] = "Built by an engineer", -- Mechano-Hog
    [35018] = "Sold by Winaestra in Eversong Woods for 10G. You must be a Blood Elf or exalted with Silvermoon", -- Purple Hawkstrider
    [23246] = "Sold by Zachariah Post in Tirisfal Glades for 100G. You must be an Undead or exalted with the Undercity", -- Purple Skeletal Warhorse
    [61997] = "Reward from the Mountain o' Mounts Achievement (collect 100 mounts)", -- Red Dragonhawk
    [34795] = "Sold by Winaestra in Eversong Woods for 10G. You must be a Blood Elf or exalted with Silvermoon", -- Red Hawkstrider
    [17462] = "Sold by Zachariah Post in Tirisfal Glades for 10G. You must be an Undead or exalted with the Undercity", -- Red Skeletal Horse
    [22722] = "Sold by Raider Bork in Orgrimmar for 2000 honor", -- Red Skeletal Warhorse
    [23241] = "Sold by Zjolnir in Durotar for 100G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Swift Blue Raptor
    [23250] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 100G. You must be an Orc or exalted with Orgrimmar", -- Swift Brown Wolf
    [23252] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 100G. You must be an Orc or exalted with Orgrimmar", -- Swift Gray Wolf
    [35025] = "Sold by Winaestra in Eversong Woods for 100G. You must be a Blood Elf or exalted with Silvermoon", -- Swift Green Hawkstrider
    [32295] = "Sold by Dama Wildmane in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Green Wind Rider
    [23242] = "Sold by Zjolnir in Durotar for 100G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Swift Olive Raptor
    [23243] = "Sold by Zjolnir in Durotar for 100G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Swift Orange Raptor
    [33660] = "Sold by Winaestra in Eversong Woods for 100G. You must be a Blood Elf or exalted with Silvermoon", -- Swift Pink Hawkstrider
    [35027] = "Sold by Winaestra in Eversong Woods for 100G. You must be a Blood Elf or exalted with Silvermoon", -- Swift Purple Hawkstrider
    [32297] = "Sold by Dama Wildmane in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Purple Wind Rider
    [32246] = "Sold by Dama Wildmane in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Red Wind Rider
    [23251] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 100G. You must be an Orc or exalted with Orgrimmar", -- Swift Timber Wolf
    [35028] = "Sold by Raider Bork in Orgrimmar for 2000 honor", -- Swift Warstrider
    [32296] = "Sold by Dama Wildmane in Shadowmoon Valley for 200G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Swift Yellow Wind Rider
    [32243] = "Sold by Dama Wildmane in Shadowmoon Valley for 100G or Mei Francis in Dalaran with Kirin Tor Reputation Bonus", -- Tawny Wind Rider
    [580] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 10G. You must be an Orc or exalted with Orgrimmar", -- Timber Wolf
    [61447] = "Sold by Mei Francis in Dalaran for 20000G", -- Traveler's Tundra Mammoth
    [10796] = "Sold by Zjolnir in Durotar for 10G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Turquoise Raptor
    [10799] = "Sold by Zjolnir in Durotar for 10G. You must be a Troll (ingame, not on forums) or exalted with the Darkspear Trolls", -- Violet Raptor
    [59793] = "Sold by Mei Francis in Dalaran for 2175 Justice Points", -- Wooly Mammoth
    [61467] = "Dropped by Archavon the Stone Watcher in the Vault of Archavon (Raid)", -- Grand Black War Mammoth
    [64977] = "Sold by Zachariah Post in Tirisfal Glades for 10G. You must be an Undead or exalted with the Undercity", -- Black Skeletal Horse
    [64658] = "Sold by Ogunaro Wolfrunner in Orgrimmar for 10G. You must be an Orc or exalted with Orgrimmar", -- Black Wolf
    [64657] = "Sold by Harb Clawhoof in Mulgore for 10G. You must be a Tauren or exalted with Thunder Bluff", -- White Kodo
    [63641] = "Sold by Doru Thunderhorn (Thunder Bluff Quartermaster) at the Argent Tournament for 100 Champion's Seals. You must be a Tauren or a Champion of Thunder Bluff", -- Thunder Bluff Kodo
    [63643] = "Sold by Eliza Killian (Undercity Quartermaster) at the Argent Tournament for 100 Champion's Seals. You must be an Undead or a Champion of the Undercity", -- Forsaken Warhorse
    [63635] = "Sold by Samamba (Sen'Jin Quartermaster) at the Argent Tournament for 100 Champion's Seals. You must be a Troll (ingame, not on forums) or a Champion of Sen'Jin", -- Darkspear Raptor
    [63640] = "Sold by Freka Bloodaxe (Orgrimmar Quartermaster) at the Argent Tournament for 100 Champion's Seals. You must be an Orc or a Champion of Orgrimmar", -- Orgrimmar Wolf
    [63642] = "Sold by Trellis Morningsun (Silvermoon Quartermaster) at the Argent Tournament for 100 Champion's Seals. You must be a Blood Elf or a Champion of Silvermoon", -- Silvermoon Hawkstrider
    [65645] = "Sold by Eliza Killian (Undercity Quartermaster) at the Argent Tournament for 5 Champion's Seals and 500 Gold. You must be an Undead or a Champion of the Undercity", -- White Skelettal Warhorse
    [65644] = "Sold by Samamba (Sen'Jin Quartermaster) at the Argent Tournament for 5 Champion's Seals and 500 Gold. You must be a Troll (ingame, not on forums) or a Champion of Sen'Jin", -- Swift Purple Raptor
    [65641] = "Sold by Doru Thunderhorn (Thunder Bluff Quartermaster) at the Argent Tournament for 5 Champion's Seals and 500 Gold. You must be a Tauren or a Champion of Thunder Bluff", -- Great Golden Kodo
    [65646] = "Sold by Freka Bloodaxe (Orgrimmar Quartermaster) at the Argent Tournament for 500 Gold and 5 Champion's Seals. You must be an Orc or a Champion of Orgrimmar", -- Swift Burgundy Wolf
    [65639] = "Sold by Trellis Morningsun (Silvermoon Quartermaster) at the Argent Tournament for 500 Gold and 5 Champion's Seals. You must be a Blood Elf or a Champion of Silvermoon", -- Swift Red Hawkstrider
    [66846] = "Sold in Brill in Tirisfal Glades, must be Undead or exalted with Undercity.", -- Ochre Skeletal Warhorse
    [66091] = "Sold by Horde Sunreavers Quartermaster at the Argent Tournament for 100 Champion Seals. Requires level 40 and 150 Riding.", -- Sunreaver Hawkstrider
    [66088] = "Sold by Horde Sunreavers Quartermaster at the Argent Tournament for 150 Champion Seals. Requires level 70 and 300 Riding.", -- Sunreaver Dragonhawk
    [68056] = "Loot from 10 man Heroic Trial of the Grand Crusader with all 50 attempts left, only one drops per raid. No longer obtainable.", -- Swift Horde Wolf
    [87090] = "Purchased from Kall Worthaton in Orgrimmar.", -- Goblin Trike
    [87091] = "Purchased from Kall Worthaton in Orgrimmar.", -- Goblin Turbo-Trike
    [56921] = "Sold by Pogg, Hellscream's Reach Quartermaster. Requires Level 70, Apprentice Riding and Hellscream's Reach Exalted reputation.", -- Spectral Wolf
    [93644] = "Available for Horde after Guild reaches level 25 and you reach Exalted reputation with your guild, 1500g. [BoA]", -- Kor'kron Annihilator
    [100333] = "Reward from the achivement 'Veteran of the Horde' and other higher achivements.", -- Vicious War Wolf
    -- paladin mounts
    [23214] = "Taught by the Paladin Trainer at Level 61 or obtained by completing the Level 60 Paladin Quest Line", -- Alliance Charger
    [13819] = "Taught by the Paladin Trainer at Level 40", -- Alliance Warhorse
    [66906] = "Sold by Dame Evniki Kapsalis, Crusader's Quartermaster at the Argent Tournament for 100 Champion's Seals. Requires level 40 and Riding 150 and must be a Paladin. Must have the Argent Champion title.", -- Argent Charger
    [34767] = "Taught by the Paladin Trainer at Level 61 or obtained by completing the Level 60 Paladin Quest Line", -- Horde Charger
    [34769] = "Taught by the Paladin Trainer at Level 40", -- Horde Warhorse
    [73629] = "Taught by the Paladin Trainer at Level 20, Draenei Only", -- Exarch's Elekk
    [73630] = "Taught by the Paladin Trainer at Level 40, Draenei Only", -- Great Exarch's Elekk
    [69820] = "Taught by the Paladin Trainer at Level 20, Tauren Only", -- Sunwalker Kodo
    [69826] = "Taught by the Paladin Trainer at Level 40, Tauren Only", -- Great Sunwalker Kodo
    -- warlock mounts
    [23161] = "Taught by the Warlock Trainer at Level 61 or obtained by completing the Level 60 Warlock Quest Line", -- Dreadsteed
    [5784] = "Taught by the Warlock Trainer at Level 40", -- Felsteed
    -- deathknight mounts
    [54729] = "Sold by Dread Commander Thalanor in Acherus for 1000G", -- Winged Steed of the Ebon Blade
    [48778] = "Reward from the Quest Into the Realm of Shadows in the Death Knight Starting Zone", -- Acherus Deathcharger
    -- engineering mounts
    [44153] = "Recipe is taught by Niobe Whizzlespark and Jonathan Garrett in Shadowmoon Valley for 12G", -- Flying Machine
    [44151] = "Recipe is taught by Niobe Whizzlespark and Jonathan Garrett in Shadowmoon Valley for 18G", -- Turbo-Charged Flying Machine
    -- tailoring mounts
    [61451] = "Recipe is taught by Grand Master Tailoring Trainers", -- Flying Carpet
    [75596] = "Purchased for 6 Frozen Orbs from Frozo the Renowned in Dalaran, Requires level 70, Tailoring 425 and Artisan Riding.", -- Frosty Flying Carpet
    [61309] = "Recipe is taught by Grand Master Tailoring Trainers", -- Magnificent Flying Carpet
    [61444] = "Not available yet", -- Swift Shadoweave (Ebonweave) Carpet
    [61442] = "Not available yet", -- Swift Mooncloth Carpet
    [61446] = "Not available yet", -- Swift Spellfire Carpet
}