CollectMeTitleInfo = {
    [1] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Private ", -- [1]
    [2] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Corporal ", -- [2]
    [3] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant ", -- [3]
    [4] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Master Sergeant ", -- [4]
    [5] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant Major ", -- [5]
    [6] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight ", -- [6]
    [7] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Lieutenant ", -- [7]
    [8] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Captain ", -- [8]
    [9] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Champion 
    [10] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Lieutenant Commander ", -- [10]
    [11] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Commander ", -- [11]
    [12] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Marshal ", -- [12]
    [13] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Field Marshal ", -- [13]
    [14] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Grand Marshal ", -- [14]
    [15] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Scout ", -- [15]
    [16] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Grunt ", -- [16]
    [17] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant ", -- [17]
    [18] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Senior Sergeant ", -- [18]
    [19] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- First Sergeant ", -- [19]
    [20] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Stone Guard ", -- [20]
    [21] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Blood Guard ", -- [21]
    [22] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Legionnaire ", -- [22]
    [23] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Centurion ", -- [23]
    [24] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Champion ", -- [24]
    [25] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Lieutenant General ", -- [25]
    [26] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- General ", -- [26]
    [27] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Warlord ", -- [27]
    [28] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- High Warlord ", -- [28]
    [29] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 0.0% - 0.5.% ", -- Gladiator ", -- [29]
    [30] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 0.5% - 3%.", -- Duelist ", -- [30]
    [31] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 3% - 10%.", -- Rival ", -- [31]
    [32] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 10% - 35%.", -- Challenger ", -- [32]
    [33] = "The title was originally awarded when opening the gates to Ahn'Qiraj and is no longer obtainable.", -- Scarab Lord ", -- [33]
    [34] = "Obtained by gaining exalted reputation with  Frostwolf Clan, The Defilers, Warsong Outriders.", -- Conqueror", -- [34]
    [35] = "Obtained by gaining exalted reputation with Silverwing Sentinels, the League of Arathor, Stormpike Guard.", -- Justicar", -- [35]
    [36] = "This title was awarded to players that completed the attunement quest for Serpentshrine Cavern back in Burning Crusade.", -- Champion of the Naaru", -- [36]
    [37] = "Awarded per battlegroup at the end of arena season 2 based on top ranked percentage. Top 0.0% - 0.5.%", --Merciless Gladiator", -- [37]
    [38] = "Awarded after completing the quest 'A Magnanimous Benefactor' after gaining exalted reputation with the Shattered Sun Offensive.", -- of the Shattered Sun", -- [38]
    [39] = "Awarded after completing the quest 'The Vials of Eternity', this quest in no longer obtainable.", -- Hand of A'dal", -- [39]
    [40] = "Awarded per battlegroup at the end of arena season 3 based on top ranked percentage. Top 0.0% - 0.5.%", --Vengeful Gladiator ", -- [40]
    [41] = "Reward from the PvP achievement 'Battlemaster'.", --Battlemaster ", -- [41]
    [42] = "Awarded after gaining '3000 Quests Completed' achievement.", -- the Seeker", -- [42]
    [43] = "Reward from the world event achievement 'To Honor One's Elders'.", --Elder ", -- [43]
    [44] = "Reward from the world event achievement 'The Flame Warden'.", --Flame Warden ", -- [44]
    [45] = "Reward from the world event achievement 'The Flame Keeper'.", --Flame Keeper ", -- [45]
    [46] = "Obtained by gaining 55 exalted reputations", -- the Exalted", -- [46]
    [47] = "Reward from the exploration achievement 'World Explorer'.", -- the Explorer", -- [47]
    [48] = "Obtained by gaining exalted reputation with Timbermaw Hold, Sporeggar and the Kurenai(Alliance)/Mag'har(Horde).  ", -- the Diplomat", -- [48]
    [49] = "This title was awarded to players who were ranked #1 in their battlegroup when season 4 ended.", --Brutal Gladiator ", -- [49]
    [50] = "Reward from the arena achievement 'The Arena Master'.", --Arena Master ", -- [50]
    [51] = "Reward from the fishing achievement 'Accomplished Angler'.", --Salty ", -- [51]
    [52] = "Reward from the cooking achievement 'Hail to the Chef'.", --Chef ", -- [52]
    [53] = "Realm first level 80 Warrior. Removed in early WotLK Beta.", -- the Supreme", -- [53]
    [54] = "Realm first level 80 Shaman. Removed in early WotLK Beta.", -- of the Ten Storms", -- [54]
    [55] = "Realm first level 80 Druid. Removed in early WotLK Beta.", -- of the Emerald Dream", -- [55]
    [56] = "This title was awarded to players that were ranked #1 in their battlegroup when season 5 ended.", --Deadly Gladiator ", -- [56]
    [57] = "Realm first level 80 Priest. Removed in early WotLK Beta.", --Prophet ", -- [57]
    [58] = "Realm first level 80 Warlock. Removed in early WotLK Beta"., -- the Malefic", -- [58]
    [59] = "Realm first level 80 Hunter. Removed in early WotLK Beta.", --Stalker ", -- [59]
    [60] = "Realm first level 80 Death Knight. Removed in early WotLK Beta.", -- of the Ebon Blade", -- [60]
    [61] = "Realm first level 80 Mage. Removed in early WotLK Beta.", --Archmage ", -- [61]
    [62] = "Reward for winning 300 rated battlegrounds.", --Warbringer ", -- [62]
    [63] = "Realm first level 80 Rogue. Removed in early WotLK Beta.", --Assassin ", -- [63]
    [64] = "Realm first Alchemy skill 450. Removed in early WotLK Beta.", --Grand Master Alchemist ", -- [64]
    [65] = "Realm first Blacksmithing skill 450. Removed in early WotLK Beta.", --Grand Master Blacksmith ", -- [65]
    [66] = "Reward for obtaining 200 cooking recipes.", --Iron Chef ", -- [66]
    [67] = "Realm first Enchanting skill 450. Removed in early WotLK Beta.", --Grand Master Enchanter ", -- [67]
    [68] = "Realm first Engineering skill 450. Removed in early WotLK Beta.", --Grand Master Engineer ", -- [68]
    [69] = "Realm first First Aid skill 450. Removed in early WotLK Beta.", --Doctor ", -- [69]
    [70] = "Realm first Fishing skill 450. Removed in early WotLK Beta.", --Grand Master Angler ", -- [70]
    [71] = "Realm first Herbalism skill 450. Removed in early WotLK Beta.", --Grand Master Herbalist ", -- [71]
    [72] = "Realm first Inscription skill 450. Removed in early WotLK Beta.", --Grand Master Scribe ", -- [72]
    [73] = "Realm first Jewelcrafting skill 450. Removed in early WotLK Beta.", --Grand Master Jewelcrafter ", -- [73]
    [74] = "Realm first Leatherworking skill 450. Removed in early WotLK Beta.", --Grand Master Leatherworker ", -- [74]
    [75] = "Realm first Mining skill 450. Removed in early WotLK Beta.", --Grand Master Miner ", -- [75]
    [76] = "Realm first Skinning skill 450. Removed in early WotLK Beta.", --Grand Master Skinner ", -- [76]
    [77] = "Realm first Tailoring skill 450. Removed in early WotLK Beta.", --Grand Master Tailor ", -- [77]
    [78] = "Realm first level 80 Blood Elf. Removed in early WotLK Beta.", -- of Quel'Thalas", -- [78]
    [79] = "Realm first level 80 Draenei. Removed in early WotLK Beta.", -- of Argus -- [79]
    [81] = "Realm first level 80 Dwarf. Removed in early WotLK Beta.", -- of Khaz Modan", -- [80]
    [82] = "Realm first level 80 Human. Removed in early WotLK Beta.", -- the Lion Hearted", -- [82]
    [83] = "Realm first level 80 Night Elf. Removed in early WotLK Beta.", -- Champion of Elune", -- [83]
    [84] = "Realm first level 80 Orc. Removed in early WotLK Beta.", -- Hero of Orgrimmar", -- [84]
    [85] = "Realm first level 80 Tauren. Removed in early WotLK Beta.", --Plainsrunner ", -- [85]
    [86] = "Realm first level 80 Troll. Removed in early WotLK Beta.", -- of the Darkspear", -- [86]
    [87] = "Realm first level 80 Undead. Removed in early WotLK Betav", -- the Forsaken", -- [87]
    [88] = "Reward for realm first defeat of Malygos in 25-player mode.", -- the Magic Seeker", -- [88]
    [89] = "Reward from the achievement 'The Twilight Zone (25 player)'.", -- Twilight Vanquisher ", -- [89]
    [90] = "Awarded to participant in the realm first defeat of Kel'Thuzad in Naxxramas in 25-player mode. ", -- Conqueror of Naxxramas", -- [90]
    [91] = "Reward for realm first exalted with the Argent Crusade, the Wyrmrest Accord, the Kirin Tor and the Knights of the Ebon Blade. Removed in early WotLK Beta.", -- Hero of Northrend
    [92] = "Reward for completing all Hallow's End holiday achievements.", -- the Hallowed
    [93] = "Reward for from the 'Loremaster' achievement for completing almost all quests in all zones.", -- Loremaster
    [94] = "Reward for reaching 100.000 honorable kills.", -- of the Alliance
    [95] = "Reward for reaching 100.000 honorable kills.", -- of the Horde
    [96] = "Reward for winning 10 ranked matches in a row with a rating above 2.000 at level 80. Removed in patch 3.1.0", -- the Flawless Victor
    [97] = "Reward for completing every WotLK 3.0 Dungeon on heroic difficulty and every WotLK 3.0 Raid on any difficulty", -- Champion of the Frozen Wastes
    [98] = "Reward for getting exalted with each city of your faction.", -- Ambassador
    [99] = "Reward for getting exalted with the Argent Dawn and the Argent Crusade.", -- the Argent Champion
    [100] = "Reward for getting exalted with the Cenarion Circle and the Cenarion Expedition.", -- Guardian of Cenarius
    [101] = "Reward for completing the Brewfest holiday achievements.", -- Brewmaster
    [102] = "Reward for completing the Winter's Veil holiday achievements.", -- Merrymaker
    [103] = "Reward for completing the Love is in the Air holiday achievements.", -- the Love Fool
    [104] = "Reward for completing the Children's Week holiday achievements. Only applies to female characters.", -- Matron
    [105] = "Reward for completing the Children's Week holiday achievements. Only applies to male characters.", -- Patron
    [106] = "Reward for realm first defeat of Sartharion the Onyx Guardian in 25-player mode.", -- Obsidian Slayer
    [107] = "Reward for defeating Sartharion the Onyx Guardian with all three drakes alive in 10-player mode.", -- of the Nightfall
    [108] = "Reward for defeating all the bosses in Naxxramas on heroic, during one lockout period, without any raid members dying during any of the boss encounters in 25-player mode.", -- the Immortal
    [109] = "Reward for defeating all the bosses in Naxxramas on heroic, during one lockout period, without any raid members dying during any of the boss encounters in 10-player mode.", -- the Undying
    [110] = "Reward for killing 50 rookery whelps within 15 seconds in Upper Blackrock Spire.", -- Jenkins
    [111] = "Reward for gaining exalted reputation with the Bloodsail Buccaneers.", -- Bloodsail Admiral
    [112] = "Reward for gaining exalted reputation with the Bloodsail Buccaneers, Darkmoon Faire, Gadgetzan, Booty Bay, Everlook, Ratchet, Ravenholdt", -- the Insane
    [113] = "Reward for earning the right to represent the Exodar in the Argent Tournament.", -- of the Exodar
    [114] = "Reward for earning the right to represent Darnassus in the Argent Tournament.", -- of Darnassus
    [115] = "Reward for earning the right to represent Ironforge in the Argent Tournament.", -- of Ironforge
    [116] = "Reward for earning the right to represent Stormwind in the Argent Tournament.", -- of Stormwind
    [117] = "Reward for earning the right to represent Orgrimmar in the Argent Tournament.", -- of Orgrimmar
    [118] = "Reward for earning the right to represent Sen'jin in the Argent Tournament.", -- of Sen'jin
    [119] = "Reward for earning the right to represent Silvermoon in the Argent Tournament.", -- of Silvermoon
    [120] = "Reward for earning the right to represent Thunder Bluff in the Argent Tournament.", -- of Thunder Bluff
    [121] = "Reward for earning the right to represent the Undercity in the Argent Tournament.", -- of the Undercity
    [122] = "Reward for completing the Noblegarden holiday achievements.", -- the Noble"
    [123] = "Reward for earning the right to represent every city of you faction in the Argent Tournament as well as beeing exalted with them and the Argent Crusade.", -- Crusader
    [124] = "Reward for realm first Yogg-Saron kill in 25-player mode", -- Death's Demise
    [125] = "Reward for realm first Algalon the Observer kill in 25-player mode", -- the Celestial Defender
    [126] = "Reward for defeating each boss in Ulduar in 25-player mode without allowing any raid member to die to that boss at any point during that raid lockout period.", -- Conqueror of Ulduar
    [127] = "Reward for defeatubg each boss in Ulduar in 10-player mode without allowing any raid member to die to that boss at any point during that raid lockout period.", -- Champion of Ulduar
    [128] = "Reward for beeing in the top 1.000 players in the 2009 Arena Season.", -- Vanquisher
    [129] = "Reward for defeating Algalon the Observer in 10-player mode.", -- Starcaller
    [130] = "Reward for defeating Algalon the Observer in 25-player mode.", -- the Astral Walker
    [131] = "Reward for defeating Algalon the Observer in 10-player mode at level 80 without anyone in the raid wearing any equipment with an item level higher than is available in 10-player Ulduar", -- Herald of the Titans
    [132] = "Awarded per battlegroup at the end of arena season 6 based on top ranked percentage. Top 0.0% - 0.5.%", -- Furious Gladiator
    [133] = "Reward for completing the Pilgrim's Bounty holiday achievements", -- the Pilgrim
    [134] = "Awarded per battlegroup at the end of arena season 7 based on top ranked percentage. Top 0.0% - 0.5.%", -- Relentless Gladiator
    [135] = "Reward for realm first conquest of the Trial of the Grand Crusader with 50 attempts remaining in 25-player mode", -- Grand Crusader
    [136] = "Reward for meet the criteria for A Tribute to Insanity without any raid member having used an item only obtainable from 25-player Coliseum, or any more powerful item", -- the Argent Defender
    [137] = "Reward for using the Dungeon Finder tool to finish random heroic dungeons until you have grouped with 50 random players total", -- the Patient
    [138] = "Reward for defeating the Lich King in 25-player mode on heroic difficulty", -- the Light of Dawn
    [139] = "Reward for defeating the Lich King in 10-player mode on heroic difficulty", -- Bane of the Fallen King
    [140] = "Reward for defeating every Boss in Icecrown Citadel", -- the Kingslayer
    [141] = "Reward for getting exalted with the Ashen Verdict", -- of the Ashen Verdict
    [142] = "Awarded per battlegroup at the end of arena season 8 based on top ranked percentage. Top 0.0% - 0.5.%", -- Wrathful Gladiator
    [143] = "Reward for obtaining the reins of the Grey Riding Camel from Dormus the Camel-Hoarder.", -- the Camel-Hoarder
    [144] = "Reward for winning 300 rated battleground", -- Warbringer
    [145] = "Reward for winning 300 rated battleground", -- Warbound
    [146] = "Temporary title while on the quest for Dragonwrath, Tarecgosa's Rest", -- Blessed Defender of Nordrassil
    [147] = "Temporary title earned in Blackwing Descent", -- Slayer of Stupid, Incompetent and Disappointing Minions
    [148] = "Reward for finding one rare artifact in Archeology", -- Assistant Professor
    [149] = "Reward for finding 10 rare artifacts in Archeology", -- Associate Professor
    [150] = "Reward for finding 20 rare artifacts in Archeology", -- Professor
    [151] = "Reward for defeating Al'Akir in Throne of the Four Winds on heroic difficulty", -- of the Four Winds
    [152] = "Reward for winning 75 rated battlegrounds", -- Veteran of the Alliance
    [153] = "Reward for winning 75 rated battlegrounds", -- Veteran of the Horde
    [154] = "Reward for reaching a rated battleground rating of 1100", -- Private
    [155] = "Reward for reaching a rated battleground rating of 1200", -- Corporal
    [156] = "Reward for reaching a rated battleground rating of 1300", -- Sergeant
    [157] = "Reward for reaching a rated battleground rating of 1400", -- Master Sergeant
    [158] = "Reward for reaching a rated battleground rating of 1500", -- Sergeant Major
    [159] = "Reward for reaching a rated battleground rating of 1600", -- Knight
    [160] = "Reward for reaching a rated battleground rating of 1700", -- Knight-Lieutenant
    [161] = "Reward for reaching a rated battleground rating of 1800", -- Knight-Captain
    [162] = "Reward for reaching a rated battleground rating of 1900", -- Knight-Champion
    [163] = "Reward for reaching a rated battleground rating of 2000", -- Lieutenant Commander
    [164] = "Reward for reaching a rated battleground rating of 2100", -- Commander
    [165] = "Reward for reaching a rated battleground rating of 2200", -- Marshal
    [166] = "Reward for reaching a rated battleground rating of 2300", -- Field Marshal
    [167] = "Reward for reaching a rated battleground rating of 2400", -- Grand Marshal
    [168] = "Reward for reaching a rated battleground rating of 1100", -- Scout
    [169] = "Reward for reaching a rated battleground rating of 1200", -- Grunt
    [170] = "Reward for reaching a rated battleground rating of 1300", -- Sergeant
    [171] = "Reward for reaching a rated battleground rating of 1400", -- Senior Sergeant
    [172] = "Reward for reaching a rated battleground rating of 1500", -- First Sergeant
    [173] = "Reward for reaching a rated battleground rating of 1600", -- Stone Guard
    [174] = "Reward for reaching a rated battleground rating of 1700", -- Blood Guard
    [175] = "Reward for reaching a rated battleground rating of 1800", -- Legionnaire
    [176] = "Reward for reaching a rated battleground rating of 1900", -- Centurion
    [177] = "Reward for reaching a rated battleground rating of 2000", -- Champion
    [178] = "Reward for reaching a rated battleground rating of 2100", -- Lieutenant General
    [179] = "Reward for reaching a rated battleground rating of 2200", -- General
    [180] = "Reward for reaching a rated battleground rating of 2300", -- Warlord
    [181] = "Reward for reaching a rated battleground rating of 2400", -- High Warlord
    [182] = "Reward for ending PvP season 9 in the top 0.5% bracket.", -- Hero of the Alliance
    [183] = "Reward for ending PvP season 9 in the top 0.5% bracket.", -- Hero of the Horde
    [184] = "Reward for reaching 250.000 honorable kills.", -- The Bloodthirsty
    [185] = "Reward for completing all Cataclysm 4.0 dungeons on heroic difficulty and the Cataclysm 4.0 raids on any difficulty", -- Defender of a Shattered World
    [186] = "Reward for defeating Sinestra in the Bastion of Twilight on heroic difficulty", -- Dragonslayer
    [187] = "Reward for defeating Nefarian in Blackwing Descent on heroic difficulty", -- Blackwing's Bane
    [188] = "Reward for earning exalted reputation with the Avenger's of Hyjal", -- Avenger of Hyjal
    [189] = "Reward for completing all special achievements of the Molten Front 'Veteran of the Molten Front' achievement.", -- the Flamebreaker
    [190] = "Reward for defeating Ragnaros in the Firelands on heroic difficulty.", -- Firelord
    [191] = "Awarded per battlegroup at the end of arena season 9 based on top ranked percentage. Top 0.0% - 0.5.%", -- Vicious Gladiator
    [192] = "Awarded per battlegroup at the end of arena season 10 based on top ranked percentage. Top 0.0% - 0.5.%", -- Ruthless Gladiator
    [193] = "Awarded per battlegroup at the end of arena season 11 based on top ranked percentage. Top 0.0% - 0.5.%", -- Cataclysmic Gladiator
    [194] = "Reward for defeating Deathwing on heroic difficulty"., -- Savior of Azeroth
    [196] = "Reward for defeating Deathwing on normal difficulty.", -- Destroyer's End
};