CollectMeTitleInfo = {
    [1] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Private ", -- [1]
    [2] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Corporal ", -- [2]
    [3] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant ", -- [3]
    [4] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Master Sergeant ", -- [4]
    [5] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant Major ", -- [5]
    [6] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight ", -- [6]
    [7] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Lieutenant ", -- [7]
    [8] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Captain ", -- [8]
    [9] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Knight-Champion 
    [10] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Lieutenant Commander ", -- [10]
    [11] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Commander ", -- [11]
    [12] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Marshal ", -- [12]
    [13] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Field Marshal ", -- [13]
    [14] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Grand Marshal ", -- [14]
    [15] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Scout ", -- [15]
    [16] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Grunt ", -- [16]
    [17] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Sergeant ", -- [17]
    [18] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Senior Sergeant ", -- [18]
    [19] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- First Sergeant ", -- [19]
    [20] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Stone Guard ", -- [20]
    [21] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Blood Guard ", -- [21]
    [22] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Legionnaire ", -- [22]
    [23] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Centurion ", -- [23]
    [24] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Champion ", -- [24]
    [25] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Lieutenant General ", -- [25]
    [26] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- General ", -- [26]
    [27] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- Warlord ", -- [27]
    [28] = "The title was originally awarded as part of the PvP ranking system and is no longer obtainable.", -- High Warlord ", -- [28]
    [29] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 0.0% - 0.5.% ", -- Gladiator ", -- [29]
    [30] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 0.5% - 3%.", -- Duelist ", -- [30]
    [31] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 3% - 10%.", -- Rival ", -- [31]
    [32] = "Awarded per battlegroup at the end of a season based on top ranked percentage. Top 10% - 35%.", -- Challenger ", -- [32]
    [33] = "The title was originally awarded when opening the gates to Ahn'Qiraj and is no longer obtainable.", -- Scarab Lord ", -- [33]
    [34] = "Obtained by gaining exalted with reputation with  Frostwolf Clan, The Defilers, Warsong Outriders.", -- Conqueror", -- [34]
    [35] = "Obtained by gaining exalted with reputation with Silverwing Sentinels, the League of Arathor, Stormpike Guard.", -- Justicar", -- [35]
    [36] = "This title was awarded to players that completed the attunement quest for Serpentshrine Cavern back in Burning Crusade.", -- Champion of the Naaru", -- [36]
    [37] = "This title was awarded to players who were ranked #1 in their battlegroup when season 2 ended.", --Merciless Gladiator", -- [37]
    [38] = "Awarded after completing the quest 'A Magnanimous Benefactor' after gaining exalted reputation with the Shattered Sun Offensive.", -- of the Shattered Sun", -- [38]
    [39] = "Awarded after completing the quest 'The Vials of Eternity', this quest in no longer obtainable.", -- Hand of A'dal", -- [39]
    [40] = "This title was awarded to players who were ranked #1 in their battlegroup when season 3 ended.", --Vengeful Gladiator ", -- [40]
    [41] = "Reward from the PvP achievement 'Battlemaster'.", --Battlemaster ", -- [41]
    [42] = "Awarded after gaining '3000 Quests Completed' achievement.", -- the Seeker", -- [42]
    [43] = "Reward from the world event achievement 'To Honor One's Elders'.", --Elder ", -- [43]
    [44] = "Reward from the world event achievement 'The Flame Warden'.", --Flame Warden ", -- [44]
    [45] = "Reward from the world event achievement 'The Flame Keeper'.", --Flame Keeper ", -- [45]
    [46] = "Obtained by gaining 55 exalted with reputation", -- the Exalted", -- [46]
    [47] = "Reward from the exploration achievement 'World Explorer'.", -- the Explorer", -- [47]
    [48] = "Obtained by gaining exalted reputation with Timbermaw Hold, Sporeggar and the Kurenai(Alliance)/Mag'har(Horde).  ", -- the Diplomat", -- [48]
    [49] = "This title was awarded to players who were ranked #1 in their battlegroup when season 4 ended.", --Brutal Gladiator ", -- [49]
    [50] = "Reward from the arena achievement 'The Arena Master'.", --Arena Master ", -- [50]
    [51] = "Reward from the fishing achievement 'Accomplished Angler'.", --Salty ", -- [51]
    [52] = "Reward from the cooking achievement 'Hail to the Chef'.", --Chef ", -- [52]
    [53] = "???", -- the Supreme", -- [53]
    [54] = "???", -- of the Ten Storms", -- [54]
    [55] = "???", -- of the Emerald Dream", -- [55]
    [56] = "This title was awarded to players who were ranked #1 in their battlegroup when season 5 ended.", --Deadly Gladiator ", -- [56]
    [57] = "???", --Prophet ", -- [57]
    [58] = "???", -- the Malefic", -- [58]
    [59] = "???", --Stalker ", -- [59]
    [60] = "???", -- of the Ebon Blade", -- [60]
    [61] = "???", --Archmage ", -- [61]
    [62] = "Reward for winning 300 rated battlegrounds.", --Warbringer ", -- [62]
    [63] = "???", --Assassin ", -- [63]
    [64] = "???", --Grand Master Alchemist ", -- [64]
    [65] = "???", --Grand Master Blacksmith ", -- [65]
    [66] = "Reward for obtaining 200 cooking recipes.", --Iron Chef ", -- [66]
    [67] = "???", --Grand Master Enchanter ", -- [67]
    [68] = "???", --Grand Master Engineer ", -- [68]
    [69] = "???", --Doctor ", -- [69]
    [70] = "???", --Grand Master Angler ", -- [70]
    [71] = "???", --Grand Master Herbalist ", -- [71]
    [72] = "???", --Grand Master Scribe ", -- [72]
    [73] = "???", --Grand Master Jewelcrafter ", -- [73]
    [74] = "???", --Grand Master Leatherworker ", -- [74]
    [75] = "???", --Grand Master Miner ", -- [75]
    [76] = "???", --Grand Master Skinner ", -- [76]
    [77] = "???", --Grand Master Tailor ", -- [77]
    [78] = "???", -- of Quel'Thalas", -- [78]
    [79] = "???", -- of Argus", -- [79]
    [81] = "???", -- of Khaz Modan", -- [80]
    [82] = "???", -- the Lion Hearted", -- [82]
    [83] = "???", -- Champion of Elune", -- [83]
    [84] = "???", -- Hero of Orgrimmar", -- [84]
    [85] = "???", --Plainsrunner ", -- [85]
    [86] = "???", -- of the Darkspear", -- [86]
    [87] = "???", -- the Forsaken", -- [87]
    [88] = "???", -- the Magic Seeker", -- [88]
    [89] = "Reward from the achievement 'The Twilight Zone (25 player)'", -- Twilight Vanquisher ", -- [89]
    [90] = "Awarded to participant in the realm first defeat of Kel'Thuzad in Naxxramas in 25-player mode. ", -- Conqueror of Naxxramas", -- [90]
    [91] = "test", -- Avenger of Hyjal", -- [188]
    [92] = "fill", -- Avenger of Hyjal", -- [188]
    [93] = "test", -- Avenger of Hyjal", -- [188]
    [94] = "fill", -- Avenger of Hyjal", -- [188]
    [95] = "test", -- Avenger of Hyjal", -- [188]
    [96] = "fill", -- Avenger of Hyjal", -- [188]
    [97] = "fill", -- Avenger of Hyjal", -- [188]
    [98] = "test", -- Avenger of Hyjal", -- [188]
    [99] = "fill", -- Avenger of Hyjal", -- [188]
    [100] = "Reward for getting exalted with the Cenarion Circle and the Cenarion Expedition ", -- Guardian of Cenarius
    [101] = "Reward for completing the Brewfest holiday achievments", -- Brewmaster
    [102] = "Reward for completing the Winter's Veil holiday achievments", -- Merrymaker
    [103] = "Reward for completing the Love is in the Air holiday achievments", -- the Love Fool
    [104] = "Reward for completing the Children's Week holiday achievments. Only applies to female characters", -- Matron
    [105] = "Reward for completing the Children's Week holiday achievments. Only applies to male characters", -- Patron
    [106] = "Reward for realm first defeat of Sartharion the Onyx Guardian in 25-player mode", -- Obsidian Slayer
    [107] = "Reward for defeating Sartharion the Onyx Guardian with all three drakes alive in 10-player mode ", -- of the Nightfall
    [108] = "Reward for defeating all the bosses in Naxxramas on heroic, during one lockout period, without any raid members dying during any of the boss encounters in 25-player mode", -- the Immortal
    [109] = "Reward for defeating all the bosses in Naxxramas on heroic, during one lockout period, without any raid members dying during any of the boss encounters in 10-player mode", -- the Undying
    [110] = "Reward for killing 50 rookery whelps within 15 seconds in Upper Blackrock Spire", -- Jenkins
    [111] = "Reward for getting exalted with the Bloodsail Buccaneers", -- Bloodsail Admiral
    [112] = "Reward for getting exalted with Bloodsail Buccaneers, Darkmoon Faire, Gadgetzan, Booty Bay, Everlook, Ratchet, Ravenholdt", -- the Insane
    [113] = "Reward for earning the right to represent the Exodar on the Argent Tournament", -- of the Exodar
    [114] = "Reward for earning the right to represent Darnassus on the Argent Tournament", -- of Darnassus
    [115] = "Reward for earning the right to represent Ironforge on the Argent Tournament", -- of Ironforge
    [116] = "Reward for earning the right to represent Stormwind on the Argent Tournament", -- of Stormwind
    [117] = "Reward for earning the right to represent Orgrimmar on the Argent Tournament", -- of Orgrimmar
    [118] = "Reward for earning the right to represent Sen'jin on the Argent Tournament", -- of Sen'jin
    [119] = "Reward for earning the right to represent Silvermoon on the Argent Tournament", -- of Silvermoon
    [120] = "Reward for earning the right to represent Thunder Bluff on the Argent Tournament", -- of Thunder Bluff
    [121] = "Reward for earning the right to represent the Undercity on the Argent Tournament", -- of the Undercity
    [122] = "Reward for completing the Noblegarden holiday achievments", -- the Noble"
    [123] = "Reward for earning the right to represent every city of you faction on the Argent Tournament as well as beeing exalted with them and the Argent Crusade", -- Crusader
    [124] = "Reward for realm first Yogg-Saron kill in 25-player mode", -- Death's Demise
    [125] = "Reward for realm first Algalon the Observer kill in 25-player mode", -- the Celestial Defender
    [126] = "Reward for defeating each boss in Ulduar in 25-player mode without allowing any raid member to die to that boss at any point during that raid lockout period", -- Conqueror of Ulduar
    [127] = "Reward for defeatubg each boss in Ulduar in 10-player mode without allowing any raid member to die to that boss at any point during that raid lockout period", -- Champion of Ulduar
    [128] = "Reward for beeing in the top 1.000 players in the 2009 Arena Season", -- Vanquisher
    [129] = "Reward for defeating Algalon the Observer in 10-player mode", -- Starcaller
    [130] = "Reward for defeating Algalon the Observer in 25-player mode", -- the Astral Walker
    [131] = "Reward for defeating Algalon the Observer in 10-player mode at level 80 without anyone in the raid wearing any equipment with an item level higher than is available in 10-player Ulduar", -- Herald of the Titans
    [132] = "Awarded per battlegroup at the end of arena season 6 based on top ranked percentage. Top 0.0% - 0.5.%", -- Furious Gladiator
    [133] = "Reward for completing the Pilgrim's Bounty holiday achievments", -- the Pilgrim
    [134] = "Awarded per battlegroup at the end of arena season 7 based on top ranked percentage. Top 0.0% - 0.5.%", -- Relentless Gladiator
    [135] = "Reward for realm first conquest of the Trial of the Grand Crusader with 50 attempts remaining in 25-player mode", -- Grand Crusader
    [136] = "Reward for meet the criteria for A Tribute to Insanity without any raid member having used an item only obtainable from 25-player Coliseum, or any more powerful item", -- the Argent Defender
    [137] = "Reward for using the Dungeon Finder tool to finish random heroic dungeons until you have grouped with 50 random players total", -- the Patient
    [138] = "Reward for defeating the Lich King in 25-player mode on heroic difficulty", -- the Light of Dawn
    [139] = "Reward for defeating the Lich King in 10-player mode on heroic difficulty", -- Bane of the Fallen King
    [140] = "Reward for defeating every Boss in Icecrown Citadel", -- the Kingslayer
    [141] = "Reward for getting exalted with the Ashen Verdict", -- of the Ashen Verdict
    [142] = "Awarded per battlegroup at the end of arena season 8 based on top ranked percentage. Top 0.0% - 0.5.%", -- Wrathful Gladiator
    [143] = "Reward for obtaining the reins of the Grey Riding Camel from Dormus the Camel-Hoarder", -- the Camel-Hoarder
    [144] = "Reward for winning 300 rated battleground", -- Warbringer
    [145] = "Reward for winning 300 rated battleground", -- Warbound
    [146] = "Temporary title while on the quest for Dragonwrath, Tarecgosa's Rest", -- Blessed Defender of Nordrassil
    [147] = "Temporary title earned in Blackwing Descent", -- Slayer of Stupid, Incompetent and Disappointing Minions
    [148] = "Reward for finding one rare artifact in Archeology", -- Assistant Professor
    [149] = "Reward for finding 10 rare artifacts in Archeology", -- Associate Professor
    [150] = "Reward for finding 20 rare artifacts in Archeology", -- Professor
    [151] = "Reward for defeating Al'Akir in Throne of the Four Winds on heroic difficulty", -- of the Four Winds
    [152] = "fill", -- Avenger of Hyjal", -- [188]
    [153] = "test", -- Avenger of Hyjal", -- [188]
    [154] = "fill", -- Avenger of Hyjal", -- [188]
    [155] = "test", -- Avenger of Hyjal", -- [188]
    [156] = "fill", -- Avenger of Hyjal", -- [188]
    [157] = "test", -- Avenger of Hyjal", -- [188]
    [158] = "fill", -- Avenger of Hyjal", -- [188]
    [159] = "test", -- Avenger of Hyjal", -- [188]
    [160] = "fill", -- Avenger of Hyjal", -- [188]
    [161] = "test", -- Avenger of Hyjal", -- [188]
    [162] = "fill", -- Avenger of Hyjal", -- [188]
    [163] = "test", -- Avenger of Hyjal", -- [188]
    [164] = "fill", -- Avenger of Hyjal", -- [188]
    [165] = "fill", -- Avenger of Hyjal", -- [188]
    [166] = "test", -- Avenger of Hyjal", -- [188]
    [167] = "fill", -- Avenger of Hyjal", -- [188]
    [168] = "test", -- Avenger of Hyjal", -- [188]
    [169] = "fill", -- Avenger of Hyjal", -- [188]
    [170] = "test", -- Avenger of Hyjal", -- [188]
    [171] = "fill", -- Avenger of Hyjal", -- [188]
    [172] = "test", -- Avenger of Hyjal", -- [188]
    [173] = "fill", -- Avenger of Hyjal", -- [188]
    [174] = "test", -- Avenger of Hyjal", -- [188]
    [175] = "fill", -- Avenger of Hyjal", -- [188]
    [176] = "test", -- Avenger of Hyjal", -- [188]
    [177] = "fill", -- Avenger of Hyjal", -- [188]
    [178] = "test", -- Avenger of Hyjal", -- [178]
    [179] = "fill", -- Avenger of Hyjal", -- [179]
    [180] = "fill", -- Avenger of Hyjal", -- [180]
    [181] = "test", -- Avenger of Hyjal", -- [181]
    [182] = "fill", -- Avenger of Hyjal", -- [182]
    [183] = "test", -- Avenger of Hyjal", -- [183]
    [184] = "fill", -- Avenger of Hyjal", -- [184]
    [185] = "test", -- Avenger of Hyjal", -- [185]
    [186] = "fill", -- Avenger of Hyjal", -- [186]
    [187] = "test", -- Avenger of Hyjal", -- [187]
    [188] = "fill", -- Avenger of Hyjal", -- [188]
    [189] = "test", -- Avenger of Hyjal", -- [189]
    [190] = "fill", -- Avenger of Hyjal", -- [190]
    [191] = "test", -- Avenger of Hyjal", -- [191]
    [192] = "fill", -- Avenger of Hyjal", -- [192]
    [193] = "test", -- Avenger of Hyjal", -- [193]
    [194] = "fill", -- Avenger of Hyjal", -- [194]
    [195] = "test", -- Avenger of Hyjal", -- [195]
    [196] = "fill", -- Avenger of Hyjal", -- [196]
};