-- auto generated by collectmedb on 2018-08-13 23:52:35

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

Data.CompanionsZone = {
    [2403] = { [1198] = 1198 }, -- Abyssal Eel
    [1624] = { [339] = 339 }, -- Abyssius
    [2420] = { [1194] = 1194 }, -- Accursed Hexxer
    [635] = { [1] = 1, [10] = 10, [199] = 199, [17] = 17, [27] = 27, [50] = 50, [100] = 100, [107] = 107, [550] = 550, [542] = 542, [606] = 606 }, -- Adder
    [1805] = { [125] = 125, [627] = 627 }, -- Alarm-o-Bot
    [1708] = { [630] = 630, [634] = 634 }, -- Albatross Chick
    [1385] = { [585] = 585, [579] = 579 }, -- Albino Chimaeraling
    [74] = { [125] = 125, [627] = 627 }, -- Albino Snake
    [2433] = { [14] = 14 }, -- Aldrusian Sproutling
    [487] = { [198] = 198, [65] = 65, [83] = 83, [650] = 650 }, -- Alpine Chipmunk
    [441] = { [83] = 83, [27] = 27 }, -- Alpine Hare
    [732] = { [422] = 422, [388] = 388 }, -- Amber Moth
    [1465] = { [543] = 543 }, -- Amberbarb Wasp
    [838] = { [66] = 66, [207] = 207 }, -- Amethyst Shale Hatchling
    [716] = { [418] = 418 }, -- Amethyst Spiderling
    [212] = { [118] = 118 }, -- Ammen Vale Lashling
    [52] = { [64] = 64 }, -- Ancona Chicken
    [1163] = { [83] = 83 }, -- Anodized Robo Cub
    [2122] = { [885] = 885 }, -- Antoran Bile Larva
    [2126] = { [885] = 885 }, -- Antoran Bilescourge
    [1155] = { [319] = 319 }, -- Anubisath Idol
    [836] = { [422] = 422 }, -- Aqua Strider
    [1160] = { [42] = 42 }, -- Arcane Eye
    [2131] = { [882] = 882 }, -- Arcane Gorger
    [558] = { [120] = 120 }, -- Arctic Fox Kit
    [641] = { [114] = 114, [115] = 115, [120] = 120, [121] = 121 }, -- Arctic Hare
    [216] = { [118] = 118 }, -- Argent Gruntling
    [214] = { [118] = 118 }, -- Argent Squire
    [272] = { [85] = 85 }, -- Armadillo Pup
    [632] = { [198] = 198, [78] = 78 }, -- Ash Lizard
    [427] = { [32] = 32, [535] = 535 }, -- Ash Spiderling
    [425] = { [36] = 36, [104] = 104, [539] = 539, [680] = 680 }, -- Ash Viper
    [1927] = { [641] = 641 }, -- Ash'ana
    [1323] = { [554] = 554 }, -- Ashleaf Spriteling
    [1706] = { [641] = 641 }, -- Ashmaw Cub
    [1150] = { [232] = 232 }, -- Ashstone Core
    [1324] = { [554] = 554 }, -- Ashwing Moth
    [1738] = { [641] = 641 }, -- Auburn Ringtail
    [1429] = { [125] = 125, [627] = 627 }, -- Autumnal Sproutling
    [1470] = { [543] = 543 }, -- Axebeak Hatchling
    [2439] = { [81] = 81, [947] = 947 }, -- Azerite Puddle
    [2429] = { [81] = 81, [947] = 947 }, -- Azeriti
    [1321] = { [554] = 554 }, -- Azure Crane Chick
    [57] = { [83] = 83 }, -- Azure Whelpling
    [411] = { [210] = 210 }, -- Baby Ape
    [1884] = { [650] = 650 }, -- Baby Elderhorn
    [2047] = { [378] = 378 }, -- Ban-Fu, Cub of Ban-Lu
    [706] = { [376] = 376 }, -- Bandicoon
    [707] = { [376] = 376 }, -- Bandicoon Kit
    [2425] = { [1195] = 1195, [1198] = 1198 }, -- Barnacled Hermit Crab
    [2385] = { [1193] = 1193 }, -- Barrier Hermit
    [626] = { [198] = 198, [23] = 23, [18] = 18 }, -- Bat
    [406] = { [77] = 77, [81] = 81, [78] = 78, [15] = 15, [23] = 23, [50] = 50, [210] = 210 }, -- Beetle
    [1934] = { [680] = 680 }, -- Benax
    [2123] = { [830] = 830 }, -- Bile Larva
    [2408] = { [1197] = 1197 }, -- Bilefang Skitterer
    [2124] = { [830] = 830 }, -- Bilescourge
    [649] = { [119] = 119 }, -- Biletoad
    [75] = { [85] = 85 }, -- Black Kingsnake
    [374] = { [37] = 37 }, -- Black Lamb
    [398] = { [70] = 70, [64] = 64, [15] = 15, [47] = 47, [23] = 23, [241] = 241, [22] = 22, [56] = 56 }, -- Black Rat
    [42] = { [25] = 25 }, -- Black Tabby Cat
    [1743] = { [650] = 650, [634] = 634 }, -- Black-Footed Fox Kit
    [1322] = { [85] = 85, [556] = 556 }, -- Blackfuse Bombling
    [2086] = { [367] = 367 }, -- Blazehound
    [1693] = { [534] = 534, [577] = 577 }, -- Blazing Firehawk
    [1753] = { [649] = 649 }, -- Bleakwater Jelly
    [1965] = { [118] = 118, [186] = 186 }, -- Blightbreath
    [455] = { [21] = 21 }, -- Blighted Squirrel
    [456] = { [22] = 22 }, -- Blighthawk
    [1915] = { [125] = 125, [627] = 627 }, -- Blind Rat
    [1964] = { [118] = 118, [186] = 186 }, -- Blood Boil
    [1468] = { [534] = 534, [577] = 577 }, -- Bloodbeak
    [2414] = { [1194] = 1194 }, -- Bloodfeaster Larva
    [2388] = { [1194] = 1194 }, -- Bloodfever Tarantula
    [1462] = { [542] = 542 }, -- Bloodsting Wasp
    [1577] = { [585] = 585, [579] = 579 }, -- Bloodthorn Hatchling
    [1666] = { [407] = 407 }, -- Blorp
    [145] = { [109] = 109 }, -- Blue Dragonhawk Hatchling
    [2422] = { [1193] = 1193, [1198] = 1198 }, -- Blue Flitter
    [259] = { [198] = 198 }, -- Blue Mini Jouster
    [138] = { [103] = 103 }, -- Blue Moth
    [2398] = { [1194] = 1194 }, -- Boghopper
    [40] = { [37] = 37 }, -- Bombay Cat
    [1963] = { [118] = 118, [186] = 186 }, -- Boneshard
    [1343] = { [554] = 554 }, -- Bonkers
    [639] = { [114] = 114 }, -- Borean Marmot
    [2082] = { [294] = 294 }, -- Bound Stream
    [1572] = { [535] = 535 }, -- Brilliant Bloodfeather
    [1540] = { [542] = 542 }, -- Brilliant Spore
    [1563] = { [17] = 17 }, -- Bronze Whelpling
    [449] = { [26] = 26, [105] = 105, [543] = 543 }, -- Brown Marmot
    [70] = { [7] = 7 }, -- Brown Prairie Dog
    [137] = { [109] = 109 }, -- Brown Rabbit
    [77] = { [85] = 85 }, -- Brown Snake
    [380] = { [371] = 371 }, -- Bucktooth Flapper
    [2442] = { [947] = 947 }, -- Bumbles
    [1726] = { [650] = 650 }, -- Burrow Spiderling
    [224] = { [127] = 127 }, -- Calico Cat
    [2428] = { [1195] = 1195, [1198] = 1198 }, -- Carnivorous Lasher
    [540] = { [198] = 198 }, -- Carrion Rat
    [459] = { [14] = 14, [37] = 37, [94] = 94, [110] = 110, [109] = 109 }, -- Cat
    [1586] = { [534] = 534, [577] = 577 }, -- Cerulean Moth
    [1633] = { [335] = 335 }, -- Chaos Pup
    [474] = { [10] = 10 }, -- Cheetah Cub
    [1303] = { [554] = 554 }, -- Chi-Chi, Hatchling of Chi-Ji
    [646] = { [70] = 70, [47] = 47, [37] = 37, [25] = 25, [49] = 49, [18] = 18, [52] = 52, [56] = 56, [108] = 108, [117] = 117 }, -- Chicken
    [2418] = { [1193] = 1193 }, -- Child of Jani
    [1152] = { [287] = 287 }, -- Chrominius
    [2087] = { [367] = 367 }, -- Cinderweb Recluse
    [518] = { [107] = 107, [550] = 550 }, -- Clefthoof Runt
    [1142] = { [503] = 503 }, -- Clock'em
    [742] = { [422] = 422 }, -- Clouded Hedgehog
    [2400] = { [1194] = 1194 }, -- Coastal Bounder
    [1914] = { [76] = 76, [630] = 630, [790] = 790, [680] = 680, [713] = 713 }, -- Coastal Sandpiper
    [2386] = { [1197] = 1197 }, -- Coastal Scuttler
    [47] = { [210] = 210 }, -- Cockatiel
    [393] = { [78] = 78, [36] = 36, [23] = 23, [26] = 26, [241] = 241, [56] = 56, [118] = 118, [543] = 543, [595] = 595 }, -- Cockroach
    [1164] = { [105] = 105 }, -- Cogblade Raptor
    [1232] = { [332] = 332 }, -- Coilfang Stalker
    [562] = { [371] = 371 }, -- Coral Adder
    [488] = { [65] = 65 }, -- Coral Snake
    [1775] = { [650] = 650 }, -- Coralback Fiddler
    [1149] = { [232] = 232 }, -- Corefire Imp
    [1890] = { [85] = 85, [84] = 84 }, -- Corgi Pup
    [2405] = { [1197] = 1197 }, -- Corlain Falcon
    [41] = { [37] = 37 }, -- Cornish Rex Cat
    [1672] = { [661] = 661 }, -- Corrupted Nest Guardian
    [2427] = { [1193] = 1193, [1198] = 1198 }, -- Cou'pa
    [1931] = { [630] = 630 }, -- Court Scribe
    [1396] = { [585] = 585, [579] = 579 }, -- Crazy Carrot
    [1962] = { [147] = 147 }, -- Creeping Tentacle
    [468] = { [1] = 1 }, -- Creepy Crawly
    [507] = { [57] = 57 }, -- Crested Owl
    [2424] = { [1194] = 1194, [1197] = 1197 }, -- Crimson Frog
    [559] = { [207] = 207 }, -- Crimson Geode
    [318] = { [338] = 338 }, -- Crimson Lasher
    [421] = { [50] = 50, [210] = 210 }, -- Crimson Moth
    [554] = { [207] = 207 }, -- Crimson Shale Hatchling
    [78] = { [85] = 85, [109] = 109 }, -- Crimson Snake
    [1537] = { [543] = 543 }, -- Crimson Spore
    [58] = { [56] = 56 }, -- Crimson Whelpling
    [1589] = { [535] = 535 }, -- Crimsonwing Moth
    [1752] = { [650] = 650 }, -- Crispin
    [2115] = { [885] = 885 }, -- Cross Gazer
    [1068] = { [407] = 407 }, -- Crow
    [745] = { [422] = 422 }, -- Crunchy Scorpion
    [1688] = { [585] = 585, [579] = 579 }, -- Crusher
    [556] = { [207] = 207 }, -- Crystal Beetle
    [634] = { [83] = 83 }, -- Crystal Spider
    [1809] = { [680] = 680 }, -- Crystalline Broodling
    [1521] = { [84] = 84, [18] = 18 }, -- Cursed Birman
    [751] = { [390] = 390 }, -- Dancing Water Skimmer
    [1329] = { [554] = 554 }, -- Dandelion Frolicker
    [270] = { [85] = 85 }, -- Dark Phoenix Hatchling
    [56] = { [70] = 70, [15] = 15, [36] = 36, [56] = 56 }, -- Dark Whelpling
    [336] = { [407] = 407 }, -- Darkmoon Balloon
    [343] = { [407] = 407 }, -- Darkmoon Cub
    [1062] = { [407] = 407 }, -- Darkmoon Glowfly
    [1061] = { [407] = 407 }, -- Darkmoon Hatchling
    [330] = { [407] = 407 }, -- Darkmoon Monkey
    [848] = { [407] = 407 }, -- Darkmoon Rabbit
    [338] = { [407] = 407 }, -- Darkmoon Tonk
    [335] = { [407] = 407 }, -- Darkmoon Turtle
    [339] = { [407] = 407 }, -- Darkmoon Zeppelin
    [508] = { [62] = 62 }, -- Darkshore Cub
    [2157] = { [1194] = 1194 }, -- Dart
    [232] = { [70] = 70 }, -- Darting Hatchling
    [1330] = { [554] = 554 }, -- Death Adder Hatchling
    [1153] = { [287] = 287 }, -- Death Talon Whelpguard
    [755] = { [198] = 198 }, -- Death's Head Cockroach
    [1449] = { [85] = 85 }, -- Deathwatch Hatchling
    [555] = { [207] = 207 }, -- Deepholm Cockroach
    [484] = { [66] = 66, [81] = 81, [71] = 71, [249] = 249 }, -- Desert Spider
    [233] = { [279] = 279 }, -- Deviate Hatchling
    [523] = { [117] = 117 }, -- Devouring Maggot
    [504] = { [78] = 78 }, -- Diemetradon Hatchling
    [1205] = { [507] = 507 }, -- Direhorn Runt
    [2079] = { [285] = 285 }, -- Discarded Experiment
    [1564] = { [543] = 543 }, -- Doom Bloom
    [2085] = { [328] = 328 }, -- Drafty
    [537] = { [115] = 115 }, -- Dragonbone Hatchling
    [1952] = { [172] = 172 }, -- Dreadmaw
    [1722] = { [777] = 777 }, -- Dream Whelpling
    [1331] = { [85] = 85, [556] = 556 }, -- Droplet of Y'Shaarj
    [1967] = { [118] = 118, [186] = 186 }, -- Drudge Ghoul
    [2406] = { [1197] = 1197 }, -- Drustvar Piglet
    [205] = { [118] = 118 }, -- Dun Morogh Cub
    [467] = { [1] = 1, [85] = 85, [249] = 249 }, -- Dung Beetle
    [207] = { [118] = 118 }, -- Durotar Scorpion
    [396] = { [47] = 47 }, -- Dusk Spiderling
    [1778] = { [125] = 125, [627] = 627 }, -- Dust Bunny
    [1588] = { [585] = 585, [579] = 579 }, -- Dusty Sporewing
    [1761] = { [650] = 650 }, -- Echo Batling
    [747] = { [390] = 390 }, -- Effervescent Glowfly
    [1181] = { [504] = 504 }, -- Elder Python
    [1774] = { [630] = 630 }, -- Eldritch Manafiend
    [1179] = { [504] = 504 }, -- Electrified Razortooth
    [293] = { [249] = 249, [241] = 241, [207] = 207 }, -- Elementium Geode
    [479] = { [89] = 89, [66] = 66, [198] = 198, [57] = 57 }, -- Elfin Rabbit
    [2389] = { [1194] = 1194 }, -- Elusive Skimmer
    [209] = { [118] = 118 }, -- Elwynn Lamb
    [631] = { [10] = 10, [199] = 199, [249] = 249, [78] = 78 }, -- Emerald Boa
    [1167] = { [119] = 119 }, -- Emerald Proto-Whelp
    [837] = { [207] = 207 }, -- Emerald Shale Hatchling
    [564] = { [371] = 371 }, -- Emerald Turtle
    [59] = { [69] = 69 }, -- Emerald Whelpling
    [1720] = { [630] = 630 }, -- Emmigosa
    [746] = { [422] = 422 }, -- Emperor Crab
    [1766] = { [107] = 107, [550] = 550 }, -- Empowered Manafiend
    [1765] = { [107] = 107, [550] = 550 }, -- Empyreal Manafiend
    [213] = { [118] = 118 }, -- Enchanted Broom
    [1764] = { [107] = 107, [550] = 550 }, -- Energized Manafiend
    [1773] = { [630] = 630 }, -- Erudite Manafiend
    [383] = { [390] = 390 }, -- Eternal Strider
    [1717] = { [680] = 680 }, -- Extinguished Eye
    [1719] = { [680] = 680 }, -- Eye of Inquisition
    [1576] = { [535] = 535 }, -- Eye of Observation
    [2090] = { [409] = 409 }, -- Faceless Mindlasher
    [2083] = { [294] = 294 }, -- Faceless Minion
    [447] = { [57] = 57, [37] = 37 }, -- Fawn
    [519] = { [104] = 104, [539] = 539, [534] = 534, [577] = 577 }, -- Fel Flame
    [1760] = { [125] = 125, [627] = 627 }, -- Fel Piglet
    [1660] = { [534] = 534, [577] = 577 }, -- Fel Pup
    [2132] = { [882] = 882 }, -- Felcrazed Wyrm
    [319] = { [84] = 84, [18] = 18 }, -- Feline Familiar
    [1731] = { [630] = 630, [650] = 650 }, -- Felspider
    [1581] = { [534] = 534, [577] = 577 }, -- Fen Crab
    [457] = { [23] = 23 }, -- Festering Maggot
    [342] = { [80] = 80 }, -- Festival Lantern
    [1802] = { [641] = 641 }, -- Fetid Waveling
    [714] = { [418] = 418 }, -- Feverbite Hatchling
    [1229] = { [350] = 350, [809] = 809 }, -- Fiendish Imp
    [2187] = { [974] = 974 }, -- Filthy Slime
    [415] = { [198] = 198, [78] = 78, [17] = 17, [36] = 36, [32] = 32 }, -- Fire Beetle
    [541] = { [198] = 198, [525] = 525 }, -- Fire-Proof Roach
    [146] = { [102] = 102 }, -- Firefly
    [1545] = { [585] = 585, [579] = 579 }, -- Firewing
    [847] = { [371] = 371 }, -- Fishy
    [644] = { [117] = 117 }, -- Fjord Rat
    [529] = { [117] = 117 }, -- Fjord Worg Pup
    [1325] = { [554] = 554 }, -- Flamering Moth
    [1595] = { [535] = 535 }, -- Flat-Tooth Calf
    [514] = { [100] = 100 }, -- Flayer Youngling
    [395] = { [49] = 49 }, -- Fledgling Buzzard
    [1709] = { [630] = 630 }, -- Fledgling Kingfeather
    [521] = { [109] = 109 }, -- Fledgling Nether Ray
    [1710] = { [630] = 630 }, -- Fledgling Oliveback
    [1716] = { [630] = 630 }, -- Fledgling Warden Owl
    [2127] = { [830] = 830 }, -- Flickering Argunite
    [1162] = { [226] = 226 }, -- Fluxfire Feline
    [2058] = { [52] = 52 }, -- Foe Reaper 0.9
    [478] = { [63] = 63, [89] = 89, [66] = 66, [80] = 80, [198] = 198, [57] = 57 }, -- Forest Moth
    [407] = { [50] = 50, [210] = 210, [104] = 104, [539] = 539, [650] = 650 }, -- Forest Spiderling
    [2438] = { [14] = 14 }, -- Foulfeather
    [278] = { [244] = 244, [245] = 245 }, -- Fox Kit
    [2440] = { [14] = 14 }, -- Fozling
    [1625] = { [339] = 339 }, -- Fragment of Anger
    [1627] = { [339] = 339 }, -- Fragment of Desire
    [1626] = { [339] = 339 }, -- Fragment of Suffering
    [2165] = { [1196] = 1196 }, -- Francois
    [2407] = { [1197] = 1197 }, -- Frenzied Cottontail
    [2374] = { [1198] = 1198 }, -- Freshwater Crawler
    [2423] = { [1195] = 1195, [1198] = 1198 }, -- Freshwater Pincher
    [495] = { [63] = 63 }, -- Frog
    [1427] = { [525] = 525 }, -- Frostfur Rat
    [1578] = { [525] = 525 }, -- Frostshell Pincher
    [1471] = { [525] = 525 }, -- Fruit Hunter
    [1144] = { [162] = 162 }, -- Fungal Abomination
    [756] = { [207] = 207 }, -- Fungal Moth
    [2432] = { [14] = 14 }, -- Fuzzy Creepling
    [1961] = { [147] = 147 }, -- G0-R41-0N Ultratonk
    [1237] = { [1] = 1 }, -- Gahz'rooki
    [569] = { [371] = 371, [630] = 630, [650] = 650 }, -- Garden Frog
    [477] = { [7] = 7 }, -- Gazelle Fawn
    [1442] = { [585] = 585, [579] = 579 }, -- Ghastly Kid
    [2077] = { [630] = 630 }, -- Ghost Shark
    [190] = { [127] = 127 }, -- Ghostly Skull
    [1665] = { [407] = 407 }, -- Ghostshell Crab
    [1143] = { [162] = 162 }, -- Giant Bone Spider
    [193] = { [125] = 125, [627] = 627 }, -- Giant Sewer Rat
    [2383] = { [1196] = 1196 }, -- Giant Woodworm
    [748] = { [390] = 390 }, -- Gilded Moth
    [630] = { [62] = 62 }, -- Gilnean Raven
    [475] = { [199] = 199 }, -- Giraffe Calf
    [1913] = { [641] = 641 }, -- Gleamhoof Fawn
    [1598] = { [585] = 585, [579] = 579 }, -- Glowing Sporebat
    [2395] = { [1194] = 1194 }, -- Glutted Bleeder
    [430] = { [71] = 71, [15] = 15, [543] = 543 }, -- Gold Beetle
    [260] = { [198] = 198 }, -- Gold Mini Jouster
    [2387] = { [1193] = 1193 }, -- Golden Beetle
    [749] = { [390] = 390 }, -- Golden Civet
    [750] = { [390] = 390 }, -- Golden Civet Kitten
    [1573] = { [542] = 542 }, -- Golden Dawnfeather
    [142] = { [94] = 94 }, -- Golden Dragonhawk Hatchling
    [1712] = { [634] = 634 }, -- Golden Eaglet
    [1332] = { [85] = 85, [556] = 556 }, -- Gooey Sha-ling
    [2120] = { [882] = 882 }, -- Grasping Manifestation
    [733] = { [388] = 388 }, -- Grassland Hopper
    [443] = { [14] = 14 }, -- Grasslands Cottontail
    [68] = { [57] = 57 }, -- Great Horned Owl
    [2409] = { [1196] = 1196 }, -- Greatwing Macaw
    [50] = { [291] = 291 }, -- Green Wing Macaw
    [464] = { [97] = 97 }, -- Grey Moth
    [834] = { [422] = 422 }, -- Grinder
    [647] = { [241] = 241, [116] = 116 }, -- Grizzly Squirrel
    [1622] = { [329] = 329 }, -- Grotesque
    [539] = { [198] = 198 }, -- Grotto Vole
    [571] = { [371] = 371 }, -- Grove Viper
    [1705] = { [641] = 641 }, -- Grumpy
    [1345] = { [554] = 554 }, -- Gu'chi Swarmling
    [2190] = { [1195] = 1195 }, -- Guardian Cobra Hatchling
    [282] = { [85] = 85 }, -- Guild Herald
    [283] = { [85] = 85 }, -- Guild Herald
    [281] = { [85] = 85 }, -- Guild Page
    [280] = { [85] = 85 }, -- Guild Page
    [1338] = { [554] = 554 }, -- Gulp Froglet
    [234] = { [121] = 121, [153] = 153 }, -- Gundrak Hatchling
    [1147] = { [232] = 232 }, -- Harbinger of Flame
    [448] = { [1] = 1, [14] = 14, [26] = 26 }, -- Hare
    [1346] = { [554] = 554 }, -- Harmonious Porcupette
    [1157] = { [10] = 10 }, -- Harpy Youngling
    [1544] = { [232] = 232 }, -- Hatespark the Tiny
    [67] = { [57] = 57 }, -- Hawk Owl
    [2399] = { [1195] = 1195 }, -- Hermit Crab
    [550] = { [241] = 241 }, -- Highlands Mouse
    [823] = { [241] = 241 }, -- Highlands Skunk
    [645] = { [241] = 241 }, -- Highlands Turkey
    [130] = { [947] = 947 }, -- Hippogryph Hatchling
    [1762] = { [650] = 650 }, -- Hog-Nosed Bat
    [2379] = { [1198] = 1198 }, -- Honey Bee
    [332] = { [85] = 85 }, -- Horde Balloon
    [851] = { [249] = 249 }, -- Horned Lizard
    [483] = { [66] = 66, [534] = 534, [577] = 577 }, -- Horny Toad
    [648] = { [25] = 25, [51] = 51, [241] = 241, [121] = 121 }, -- Huge Toad
    [1926] = { [790] = 790 }, -- Hungering Claw
    [49] = { [50] = 50, [210] = 210 }, -- Hyacinth Macaw
    [1541] = { [542] = 542 }, -- Hydraling
    [317] = { [338] = 338 }, -- Hyjal Bear Cub
    [1631] = { [329] = 329 }, -- Hyjal Wisp
    [1457] = { [525] = 525 }, -- Icespine Hatchling
    [1532] = { [542] = 542 }, -- Ikky
    [534] = { [116] = 116 }, -- Imperial Eagle Chick
    [628] = { [106] = 106, [23] = 23, [21] = 21 }, -- Infected Fawn
    [627] = { [106] = 106, [23] = 23, [21] = 21 }, -- Infected Squirrel
    [2089] = { [367] = 367 }, -- Infernal Pyreclaw
    [453] = { [25] = 25 }, -- Infested Bear Cub
    [2017] = { [554] = 554 }, -- Infinite Hatchling
    [2382] = { [1196] = 1196 }, -- Inland Croaker
    [1387] = { [17] = 17 }, -- Iron Starlette
    [1956] = { [147] = 147 }, -- Ironbound Proto-Whelp
    [1579] = { [525] = 525 }, -- Ironclaw Scuttler
    [442] = { [27] = 27 }, -- Irradiated Roach
    [792] = { [85] = 85 }, -- Jade Crane Chick
    [446] = { [26] = 26 }, -- Jade Oozeling
    [1348] = { [554] = 554 }, -- Jadefire Spirit
    [1333] = { [554] = 554 }, -- Jademist Dancer
    [1202] = { [508] = 508 }, -- Ji-Kun Hatchling
    [699] = { [371] = 371 }, -- Jumping Spider
    [565] = { [371] = 371 }, -- Jungle Darter
    [678] = { [418] = 418 }, -- Jungle Grub
    [1469] = { [543] = 543 }, -- Junglebeak
    [1728] = { [76] = 76, [630] = 630, [790] = 790, [713] = 713 }, -- Juvenile Scuttleback
    [1597] = { [542] = 542 }, -- Kaliri Hatchling
    [1583] = { [535] = 535 }, -- Kelp Scuttler
    [438] = { [15] = 15 }, -- King Snake
    [1334] = { [85] = 85, [556] = 556 }, -- Kovok
    [680] = { [388] = 388 }, -- Kuitan Mongoose
    [115] = { [585] = 585, [579] = 579 }, -- Land Shark
    [461] = { [95] = 95 }, -- Larva
    [307] = { [337] = 337 }, -- Lashtail Hatchling
    [429] = { [36] = 36 }, -- Lava Beetle
    [423] = { [36] = 36, [32] = 32 }, -- Lava Crab
    [2390] = { [1193] = 1193 }, -- Leafy Flutterwing
    [1435] = { [107] = 107, [550] = 550 }, -- Leatherhide Runt
    [545] = { [249] = 249 }, -- Leopard Scorpid
    [702] = { [371] = 371, [543] = 543 }, -- Leopard Tree Frog
    [1234] = { [334] = 334 }, -- Lesser Voidcaller
    [1623] = { [339] = 339 }, -- Leviathan Hatchling
    [1808] = { [680] = 680 }, -- Leyline Broodling
    [1226] = { [350] = 350, [809] = 809 }, -- Lil' Bad Wolf
    [2416] = { [1193] = 1193 }, -- Lil' Ben'fon
    [320] = { [85] = 85 }, -- Lil' Tarecgosa
    [2196] = { [1193] = 1193 }, -- Lil' Tika
    [2444] = { [1193] = 1193 }, -- Lil' War Machine
    [437] = { [48] = 48 }, -- Little Black Ram
    [1243] = { [508] = 508 }, -- Living Fluid
    [1177] = { [508] = 508 }, -- Living Sandling
    [408] = { [50] = 50, [210] = 210 }, -- Lizard Hatchling
    [543] = { [249] = 249 }, -- Locust
    [1159] = { [25] = 25 }, -- Lofty Libram
    [1713] = { [650] = 650, [634] = 634 }, -- Long-Eared Owl
    [404] = { [78] = 78, [27] = 27, [50] = 50, [210] = 210 }, -- Long-tailed Mole
    [1661] = { [585] = 585, [579] = 579 }, -- Lost Netherpup
    [458] = { [18] = 18 }, -- Lost of Lordaeron
    [2430] = { [1193] = 1193, [1196] = 1196 }, -- Lost Platysaur
    [341] = { [80] = 80 }, -- Lunar Lantern
    [1922] = { [680] = 680 }, -- Lurking Owl Kitten
    [718] = { [418] = 418 }, -- Luyu Moth
    [542] = { [249] = 249 }, -- Mac Frog
    [450] = { [63] = 63, [95] = 95, [25] = 25, [26] = 26, [18] = 18, [117] = 117, [534] = 534, [577] = 577 }, -- Maggot
    [132] = { [108] = 108 }, -- Magical Crawdad
    [1955] = { [147] = 147 }, -- Magma Rageling
    [708] = { [418] = 418, [376] = 376 }, -- Malayan Quillrat
    [709] = { [376] = 376 }, -- Malayan Quillrat Pup
    [136] = { [109] = 109 }, -- Mana Wyrmling
    [710] = { [376] = 376 }, -- Marsh Fiddler
    [570] = { [371] = 371 }, -- Masked Tanuki
    [703] = { [371] = 371 }, -- Masked Tanuki Pup
    [1446] = { [107] = 107, [550] = 550 }, -- Meadowstomper Calf
    [2410] = { [1196] = 1196 }, -- Mechanical Prairie Dog
    [215] = { [118] = 118 }, -- Mechanopeep
    [722] = { [418] = 418 }, -- Mei Li Sparkler
    [1227] = { [350] = 350, [809] = 809 }, -- Menagerie Custodian
    [500] = { [77] = 77 }, -- Minfernal
    [1156] = { [319] = 319 }, -- Mini Mindslayer
    [149] = { [108] = 108 }, -- Miniwing
    [566] = { [371] = 371 }, -- Mirror Strider
    [1744] = { [650] = 650, [634] = 634 }, -- Mist Fox Kit
    [422] = { [51] = 51 }, -- Moccasin
    [165] = { [333] = 333 }, -- Mojo
    [428] = { [32] = 32 }, -- Molten Hatchling
    [737] = { [388] = 388 }, -- Mongoose
    [739] = { [388] = 388 }, -- Mongoose Pup
    [1276] = { [407] = 407 }, -- Moon Moon
    [1447] = { [104] = 104, [539] = 539 }, -- Moonshell Crab
    [1455] = { [104] = 104, [539] = 539 }, -- Mossbite Skitterer
    [391] = { [49] = 49, [650] = 650 }, -- Mountain Cottontail
    [633] = { [65] = 65, [83] = 83, [56] = 56, [116] = 116, [120] = 120 }, -- Mountain Skunk
    [385] = { [70] = 70, [7] = 7, [47] = 47, [52] = 52, [56] = 56, [109] = 109, [116] = 116 }, -- Mouse
    [286] = { [23] = 23 }, -- Mr. Grubbs
    [1441] = { [107] = 107, [550] = 550, [542] = 542, [535] = 535, [650] = 650 }, -- Mud Jumper
    [1594] = { [543] = 543 }, -- Mudback Calf
    [1776] = { [650] = 650 }, -- Mudshell Conch
    [210] = { [118] = 118 }, -- Mulgore Hatchling
    [2002] = { [18] = 18 }, -- Naxxy
    [1954] = { [172] = 172 }, -- Nerubian Swarmer
    [1604] = { [125] = 125, [627] = 627 }, -- Nethaera's Light
    [557] = { [69] = 69 }, -- Nether Faerie Dragon
    [186] = { [108] = 108 }, -- Nether Ray Fry
    [638] = { [109] = 109 }, -- Nether Roach
    [1228] = { [350] = 350, [809] = 809 }, -- Netherspace Abyssal
    [1524] = { [107] = 107, [550] = 550 }, -- Netherspawn, Spawn of Netherspawn
    [1664] = { [534] = 534, [577] = 577 }, -- Nightmare Bell
    [1723] = { [777] = 777 }, -- Nightmare Whelpling
    [1715] = { [125] = 125, [627] = 627 }, -- Nightwatch Swooper
    [547] = { [198] = 198 }, -- Nordrassil Wisp
    [1714] = { [650] = 650 }, -- Northern Hawk Owl
    [1727] = { [127] = 127, [125] = 125, [627] = 627 }, -- Nursery Spider
    [544] = { [249] = 249 }, -- Oasis Moth
    [236] = { [127] = 127 }, -- Obsidian Hatchling
    [530] = { [114] = 114 }, -- Oily Slimeling
    [1729] = { [76] = 76, [630] = 630, [790] = 790, [713] = 713 }, -- Olivetail Hare
    [1335] = { [554] = 554 }, -- Ominous Flame
    [43] = { [37] = 37 }, -- Orange Tabby Cat
    [2116] = { [994] = 994 }, -- Orphaned Marsuul
    [1125] = { [390] = 390 }, -- Pandaren Air Spirit
    [1126] = { [390] = 390 }, -- Pandaren Earth Spirit
    [1124] = { [390] = 390 }, -- Pandaren Fire Spirit
    [868] = { [390] = 390 }, -- Pandaren Water Spirit
    [301] = { [50] = 50 }, -- Panther Cub
    [2018] = { [554] = 554 }, -- Paradox Spirit
    [2380] = { [1196] = 1196 }, -- Parasitic Boarfly
    [1615] = { [543] = 543 }, -- Parched Lizard
    [403] = { [78] = 78, [50] = 50, [51] = 51, [210] = 210 }, -- Parrot
    [198] = { [115] = 115, [117] = 117 }, -- Pengu
    [1663] = { [534] = 534, [577] = 577 }, -- Periwinkle Calf
    [175] = { [348] = 348 }, -- Phoenix Hatchling
    [1235] = { [334] = 334 }, -- Phoenix Hawk Hatchling
    [166] = { [1] = 1, [27] = 27 }, -- Pint-Sized Pink Pachyderm
    [1755] = { [125] = 125, [627] = 627 }, -- Plump Jelly
    [2041] = { [52] = 52 }, -- Pocket Cannon
    [1233] = { [334] = 334 }, -- Pocket Reaver
    [2188] = { [1195] = 1195 }, -- Poda
    [409] = { [50] = 50 }, -- Polly
    [386] = { [7] = 7, [10] = 10, [199] = 199, [88] = 88, [14] = 14, [52] = 52, [107] = 107, [550] = 550 }, -- Prairie Dog
    [1568] = { [585] = 585, [579] = 579 }, -- Puddle Terror
    [328] = { [322] = 322 }, -- Purple Puffer
    [1200] = { [508] = 508 }, -- Pygmy Direhorn
    [2133] = { [882] = 882 }, -- Pygmy Marsuul
    [1907] = { [641] = 641 }, -- Pygmy Owl
    [513] = { [81] = 81 }, -- Qiraji Guardling
    [378] = { [76] = 76, [62] = 62, [69] = 69, [80] = 80, [198] = 198, [7] = 7, [65] = 65, [27] = 27, [47] = 47, [37] = 37, [94] = 94, [25] = 25, [49] = 49, [110] = 110, [21] = 21, [84] = 84, [18] = 18, [22] = 22, [52] = 52, [56] = 56, [105] = 105, [107] = 107, [127] = 127, [117] = 117, [550] = 550, [650] = 650 }, -- Rabbit
    [472] = { [76] = 76, [65] = 65, [83] = 83 }, -- Rabid Nut Varmint 5000
    [2437] = { [14] = 14 }, -- Ragepeep
    [2417] = { [1195] = 1195 }, -- Ranishu Runt
    [743] = { [422] = 422 }, -- Rapana Whelk
    [417] = { [468] = 468, [63] = 63, [76] = 76, [106] = 106, [62] = 62, [66] = 66, [65] = 65, [14] = 14, [27] = 27, [95] = 95, [179] = 179, [202] = 202, [25] = 25, [48] = 48, [217] = 217, [21] = 21, [84] = 84, [51] = 51, [210] = 210, [26] = 26, [18] = 18, [107] = 107, [111] = 111, [108] = 108, [127] = 127, [117] = 117, [174] = 174, [93] = 93, [302] = 302, [306] = 306, [317] = 317, [291] = 291, [246] = 246, [350] = 350, [160] = 160, [130] = 130, [168] = 168, [162] = 162, [554] = 554, [525] = 525, [550] = 550, [542] = 542, [534] = 534, [577] = 577, [650] = 650, [732] = 732, [809] = 809 }, -- Rat
    [399] = { [47] = 47 }, -- Rat Snake
    [2080] = { [285] = 285 }, -- Rattlejaw
    [431] = { [71] = 71, [15] = 15, [241] = 241 }, -- Rattlesnake
    [465] = { [106] = 106 }, -- Ravager Hatchling
    [237] = { [78] = 78 }, -- Ravasaur Hatchling
    [238] = { [56] = 56 }, -- Razormaw Hatchling
    [239] = { [50] = 50, [210] = 210 }, -- Razzashi Hatchling
    [2135] = { [885] = 885 }, -- Rebellious Imp
    [1042] = { [376] = 376 }, -- Red Cricket
    [143] = { [94] = 94 }, -- Red Dragonhawk Hatchling
    [139] = { [109] = 109 }, -- Red Moth
    [452] = { [89] = 89, [66] = 66, [57] = 57, [25] = 25, [535] = 535 }, -- Red-Tailed Chipmunk
    [392] = { [49] = 49 }, -- Redridge Rat
    [744] = { [422] = 422 }, -- Resilient Roach
    [439] = { [42] = 42 }, -- Restless Shadeling
    [2394] = { [1194] = 1194 }, -- Returned Hatchling
    [1804] = { [641] = 641 }, -- Risen Saber Kitten
    [1453] = { [125] = 125, [627] = 627 }, -- River Calf
    [2373] = { [1198] = 1198 }, -- River Frog
    [2378] = { [1197] = 1197, [1198] = 1198 }, -- River Otter
    [424] = { [63] = 63, [76] = 76, [66] = 66, [65] = 65, [64] = 64, [27] = 27, [47] = 47, [179] = 179, [202] = 202, [48] = 48, [50] = 50, [49] = 49, [210] = 210, [18] = 18, [117] = 117, [118] = 118, [194] = 194, [300] = 300, [317] = 317, [130] = 130, [186] = 186 }, -- Roach
    [471] = { [76] = 76, [85] = 85, [83] = 83 }, -- Robo-Chick
    [482] = { [66] = 66, [198] = 198, [81] = 81, [105] = 105 }, -- Rock Viper
    [1749] = { [634] = 634 }, -- Rose Taipan
    [1587] = { [104] = 104, [539] = 539, [535] = 535 }, -- Royal Moth
    [1328] = { [554] = 554 }, -- Ruby Droplet
    [460] = { [94] = 94 }, -- Ruby Sapling
    [1957] = { [147] = 147 }, -- Runeforged Servitor
    [271] = { [244] = 244, [245] = 245 }, -- Rustberg Gull
    [496] = { [63] = 63 }, -- Rusty Snail
    [1958] = { [147] = 147 }, -- Sanctum Cub
    [491] = { [71] = 71 }, -- Sand Kitten
    [2426] = { [1195] = 1195, [1198] = 1198 }, -- Sandstinger Wasp
    [573] = { [371] = 371 }, -- Sandy Petrel
    [2377] = { [1196] = 1196, [1198] = 1198 }, -- Sandyback Crawler
    [1592] = { [542] = 542 }, -- Sapphire Firefly
    [2421] = { [1193] = 1193, [1198] = 1198 }, -- Saurolisk Hatchling
    [1692] = { [534] = 534, [577] = 577 }, -- Savage Cub
    [717] = { [418] = 418 }, -- Savory Beetle
    [2436] = { [14] = 14 }, -- Scabby
    [528] = { [105] = 105 }, -- Scalded Basilisk Hatchling
    [512] = { [81] = 81 }, -- Scarab Hatchling
    [414] = { [85] = 85, [81] = 81, [64] = 64, [17] = 17, [36] = 36, [23] = 23, [241] = 241, [105] = 105, [100] = 100, [104] = 104, [539] = 539 }, -- Scorpid
    [416] = { [17] = 17 }, -- Scorpling
    [538] = { [118] = 118 }, -- Scourged Whelpling
    [2042] = { [646] = 646 }, -- Scraps
    [1448] = { [585] = 585, [579] = 579 }, -- Sea Calf
    [560] = { [71] = 71, [418] = 418, [585] = 585, [535] = 535 }, -- Sea Gull
    [340] = { [407] = 407 }, -- Sea Pony
    [1539] = { [534] = 534, [577] = 577 }, -- Seaborne Spore
    [2404] = { [1198] = 1198 }, -- Seabreeze Bumblebee
    [172] = { [338] = 338 }, -- Searing Scorchling
    [218] = { [118] = 118 }, -- Sen'jin Fetish
    [51] = { [210] = 210, [109] = 109 }, -- Senegal
    [1601] = { [104] = 104, [539] = 539 }, -- Servant of Demidos
    [1754] = { [125] = 125, [627] = 627 }, -- Sewer-Pipe Jelly
    [2381] = { [1196] = 1196 }, -- Shack Crab
    [1599] = { [535] = 535 }, -- Shadow Sporebat
    [2372] = { [1198] = 1198 }, -- Shadowback Crawler
    [1690] = { [534] = 534, [577] = 577 }, -- Shard of Cyrukh
    [1734] = { [641] = 641 }, -- Shimmering Aquafly
    [229] = { [118] = 118 }, -- Shimmering Wyrmling
    [493] = { [62] = 62 }, -- Shimmershell Snail
    [2384] = { [1193] = 1193 }, -- Shore Butterfly
    [388] = { [76] = 76, [241] = 241, [52] = 52, [107] = 107, [114] = 114, [117] = 117, [418] = 418, [550] = 550 }, -- Shore Crab
    [629] = { [85] = 85 }, -- Shore Crawler
    [754] = { [371] = 371 }, -- Shrine Fly
    [677] = { [376] = 376 }, -- Shy Bandicoon
    [44] = { [109] = 109 }, -- Siamese Cat
    [511] = { [81] = 81, [249] = 249 }, -- Sidewinder
    [711] = { [376] = 376 }, -- Sifang Otter
    [712] = { [376] = 376 }, -- Sifang Otter Pup
    [741] = { [422] = 422 }, -- Silent Hedgehog
    [494] = { [71] = 71 }, -- Silithid Hatchling
    [2163] = { [81] = 81 }, -- Silithid Mini-Tank
    [568] = { [371] = 371, [543] = 543, [542] = 542, [535] = 535 }, -- Silkbead Snail
    [503] = { [80] = 80, [198] = 198, [78] = 78 }, -- Silky Moth
    [144] = { [94] = 94 }, -- Silver Dragonhawk Hatchling
    [45] = { [37] = 37 }, -- Silver Tabby Cat
    [291] = { [25] = 25 }, -- Singing Sunflower
    [1628] = { [339] = 339 }, -- Sister of Temptation
    [637] = { [105] = 105 }, -- Skittering Cavern Crawler
    [397] = { [468] = 468, [76] = 76, [106] = 106, [47] = 47, [179] = 179, [107] = 107, [108] = 108, [117] = 117, [550] = 550 }, -- Skunk
    [1336] = { [554] = 554 }, -- Skunky Alemental
    [1350] = { [554] = 554 }, -- Sky Lantern
    [2134] = { [882] = 882 }, -- Skyfin Juvenile
    [1711] = { [650] = 650 }, -- Skyhorn Nestling
    [1326] = { [554] = 554 }, -- Skywisp Moth
    [1736] = { [630] = 630, [634] = 634, [641] = 641 }, -- Slithering Brownscale
    [419] = { [89] = 89, [66] = 66, [10] = 10, [199] = 199, [57] = 57, [14] = 14, [37] = 37, [94] = 94, [95] = 95, [48] = 48, [51] = 51, [102] = 102 }, -- Small Frog
    [90] = { [250] = 250 }, -- Smolderweb Hatchling
    [2189] = { [1197] = 1197 }, -- Smoochums
    [387] = { [70] = 70, [69] = 69, [94] = 94, [95] = 95, [48] = 48, [50] = 50, [21] = 21, [52] = 52, [107] = 107, [108] = 108, [102] = 102, [117] = 117, [119] = 119, [121] = 121, [550] = 550 }, -- Snake
    [1960] = { [147] = 147 }, -- Snaplasher
    [1953] = { [172] = 172 }, -- Snobold Runt
    [440] = { [27] = 27 }, -- Snow Cub
    [640] = { [25] = 25 }, -- Snowshoe Hare
    [72] = { [27] = 27 }, -- Snowshoe Rabbit
    [69] = { [83] = 83 }, -- Snowy Owl
    [713] = { [376] = 376 }, -- Softshell Snapling
    [1183] = { [508] = 508 }, -- Son of Animus
    [1574] = { [622] = 622, [624] = 624 }, -- Son of Sethe
    [2049] = { [279] = 279 }, -- Son of Skum
    [1966] = { [118] = 118, [186] = 186 }, -- Soulbroken Whelpling
    [1201] = { [388] = 388 }, -- Spawn of G'nathus
    [2186] = { [1038] = 1038 }, -- Spawn of Merektha
    [489] = { [70] = 70 }, -- Spawn of Onyxia
    [1185] = { [507] = 507 }, -- Spectral Porcupette
    [2397] = { [1194] = 1194 }, -- Spectral Raven
    [412] = { [76] = 76, [70] = 70, [85] = 85, [65] = 65, [57] = 57, [83] = 83, [17] = 17, [27] = 27, [23] = 23, [37] = 37, [95] = 95, [179] = 179, [202] = 202, [25] = 25, [217] = 217, [51] = 51, [26] = 26, [18] = 18, [104] = 104, [117] = 117, [118] = 118, [120] = 120, [121] = 121, [317] = 317, [339] = 339, [350] = 350, [132] = 132, [160] = 160, [185] = 185, [184] = 184, [130] = 130, [183] = 183, [168] = 168, [133] = 133, [136] = 136, [186] = 186, [162] = 162, [333] = 333, [539] = 539, [732] = 732, [809] = 809 }, -- Spider
    [1763] = { [650] = 650 }, -- Spiketail Beaver
    [433] = { [81] = 81, [15] = 15 }, -- Spiky Lizard
    [1337] = { [554] = 554 }, -- Spineclaw Crab
    [466] = { [1] = 1, [85] = 85 }, -- Spiny Lizard
    [723] = { [418] = 418 }, -- Spiny Terrapin
    [572] = { [371] = 371 }, -- Spirebound Crab
    [463] = { [95] = 95 }, -- Spirit Crab
    [515] = { [102] = 102 }, -- Sporeling Sprout
    [502] = { [78] = 78 }, -- Spotted Bell Frog
    [1739] = { [641] = 641 }, -- Spring Strider
    [87] = { [69] = 69 }, -- Sprite Darter Hatchling
    [2441] = { [14] = 14 }, -- Squawkling
    [379] = { [468] = 468, [63] = 63, [76] = 76, [62] = 62, [70] = 70, [69] = 69, [80] = 80, [198] = 198, [57] = 57, [27] = 27, [47] = 47, [37] = 37, [179] = 179, [25] = 25, [48] = 48, [217] = 217, [21] = 21, [84] = 84, [244] = 244, [245] = 245, [241] = 241, [22] = 22, [52] = 52, [56] = 56, [105] = 105, [107] = 107, [108] = 108, [127] = 127, [117] = 117, [119] = 119, [348] = 348, [398] = 398, [333] = 333, [550] = 550, [542] = 542, [650] = 650, [641] = 641 }, -- Squirrel
    [1969] = { [120] = 120 }, -- Stardust
    [2393] = { [1194] = 1194 }, -- Sticky Oozeling
    [1911] = { [125] = 125, [627] = 627 }, -- Sting Ray Pup
    [492] = { [71] = 71 }, -- Stinkbug
    [1629] = { [329] = 329 }, -- Stinkrot
    [1146] = { [162] = 162 }, -- Stitched Pup
    [485] = { [66] = 66 }, -- Stone Armadillo
    [1515] = { [535] = 535 }, -- Stonegrinder
    [1721] = { [634] = 634 }, -- Stormborne Whelpling
    [1917] = { [634] = 634 }, -- Stormstruck Beaver
    [675] = { [37] = 37, [84] = 84 }, -- Stormwind Rat
    [1518] = { [1] = 1, [27] = 27 }, -- Stout Alemental
    [553] = { [207] = 207 }, -- Stowaway Rat
    [401] = { [62] = 62, [27] = 27, [179] = 179, [50] = 50, [51] = 51, [210] = 210, [115] = 115, [194] = 194, [174] = 174, [542] = 542 }, -- Strand Crab
    [211] = { [85] = 85 }, -- Strand Crawler
    [432] = { [71] = 71, [15] = 15, [108] = 108 }, -- Stripe-Tailed Scorpid
    [532] = { [119] = 119 }, -- Stunted Shardhorn
    [1158] = { [69] = 69 }, -- Stunted Yeti
    [1128] = { [418] = 418 }, -- Sumprush Rodent
    [1434] = { [585] = 585, [579] = 579 }, -- Sun Sproutling
    [1632] = { [335] = 335 }, -- Sunblade Micro-Defender
    [1885] = { [634] = 634 }, -- Sunborne Val'kyr
    [1570] = { [585] = 585, [579] = 579 }, -- Sunfire Kaliri
    [1178] = { [504] = 504 }, -- Sunreaver Micro-Sentry
    [2088] = { [367] = 367 }, -- Surger
    [1182] = { [504] = 504 }, -- Swamp Croaker
    [402] = { [51] = 51 }, -- Swamp Moth
    [2419] = { [1194] = 1194 }, -- Swamp Toad
    [1590] = { [542] = 542, [650] = 650 }, -- Swamplighter Firefly
    [497] = { [77] = 77, [104] = 104, [539] = 539 }, -- Tainted Cockroach
    [498] = { [77] = 77 }, -- Tainted Moth
    [499] = { [77] = 77 }, -- Tainted Rat
    [1231] = { [332] = 332 }, -- Tainted Waveling
    [2198] = { [1197] = 1197 }, -- Taptaf
    [2435] = { [14] = 14 }, -- Teeny Titan Orb
    [204] = { [118] = 118 }, -- Teldrassil Sproutling
    [567] = { [371] = 371 }, -- Temple Snake
    [1416] = { [535] = 535 }, -- Teroclaw Hatchling
    [650] = { [376] = 376 }, -- Terrible Turnip
    [1735] = { [641] = 641 }, -- Terror Larva
    [1456] = { [542] = 542 }, -- Thicket Skitterer
    [1810] = { [680] = 680 }, -- Thornclaw Broodling
    [1175] = { [504] = 504 }, -- Thundertail Flapper
    [1230] = { [332] = 332 }, -- Tideskipper
    [1750] = { [634] = 634 }, -- Tiny Apparition
    [509] = { [56] = 56 }, -- Tiny Bog Beast
    [2412] = { [1193] = 1193 }, -- Tiny Direhorn
    [287] = { [36] = 36 }, -- Tiny Flamefly
    [652] = { [418] = 418 }, -- Tiny Goldfish
    [389] = { [52] = 52 }, -- Tiny Harvester
    [279] = { [207] = 207 }, -- Tiny Shale Spider
    [167] = { [102] = 102 }, -- Tiny Sporebat
    [445] = { [14] = 14 }, -- Tiny Twister
    [2078] = { [285] = 285 }, -- Tinytron
    [206] = { [118] = 118 }, -- Tirisfal Batling
    [420] = { [63] = 63, [1] = 1, [70] = 70, [77] = 77, [85] = 85, [57] = 57, [94] = 94, [95] = 95, [25] = 25, [21] = 21, [51] = 51, [241] = 241, [56] = 56, [107] = 107, [117] = 117, [550] = 550 }, -- Toad
    [546] = { [249] = 249 }, -- Tol'vir Scarab
    [480] = { [66] = 66, [207] = 207 }, -- Topaz Shale Hatchling
    [2143] = { [947] = 947 }, -- Tottle
    [2415] = { [1194] = 1194 }, -- Tragg the Curious
    [2004] = { [125] = 125, [627] = 627 }, -- Trashy
    [65] = { [407] = 407 }, -- Tree Frog
    [405] = { [78] = 78, [50] = 50, [210] = 210, [534] = 534, [577] = 577 }, -- Tree Python
    [2057] = { [52] = 52 }, -- Tricorne
    [536] = { [114] = 114, [115] = 115 }, -- Tundra Penguin
    [525] = { [117] = 117 }, -- Turkey
    [473] = { [76] = 76 }, -- Turquoise Turtle
    [469] = { [76] = 76, [198] = 198, [207] = 207 }, -- Twilight Beetle
    [2081] = { [294] = 294 }, -- Twilight Clutch-Sister
    [552] = { [241] = 241 }, -- Twilight Fiendling
    [505] = { [64] = 64 }, -- Twilight Iguana
    [470] = { [76] = 76, [241] = 241, [207] = 207 }, -- Twilight Spider
    [1464] = { [525] = 525, [543] = 543 }, -- Twilight Wasp
    [2022] = { [503] = 503 }, -- Tylarr Gronnden
    [1538] = { [104] = 104, [539] = 539 }, -- Umbrafen Spore
    [55] = { [18] = 18, [109] = 109 }, -- Undercity Cockroach
    [454] = { [18] = 18 }, -- Undercity Rat
    [1151] = { [287] = 287 }, -- Untamed Hatchling
    [1921] = { [680] = 680 }, -- Untethered Wyrmling
    [2136] = { [885] = 885 }, -- Uuna
    [1737] = { [641] = 641 }, -- Vale Flitter
    [2375] = { [1198] = 1198 }, -- Vale Marmot
    [2376] = { [1198] = 1198 }, -- Valley Chicken
    [187] = { [350] = 350, [809] = 809 }, -- Vampiric Batling
    [1596] = { [542] = 542 }, -- Veilwatcher Hatchling
    [1344] = { [554] = 554 }, -- Vengeful Porcupette
    [506] = { [65] = 65 }, -- Venomspitter Hatchling
    [1807] = { [680] = 680 }, -- Vicious Broodling
    [1591] = { [534] = 534, [577] = 577 }, -- Violet Firefly
    [1154] = { [319] = 319 }, -- Viscidus Globule
    [1244] = { [508] = 508 }, -- Viscous Horror
    [2130] = { [882] = 882 }, -- Void Shardling
    [2129] = { [882] = 882 }, -- Voidstalker Runt
    [2434] = { [14] = 14 }, -- Voidwiggler
    [1013] = { [418] = 418 }, -- Wanderer's Festival Hatchling
    [517] = { [108] = 108 }, -- Warpstalker Hatchling
    [2128] = { [882] = 882 }, -- Warpstalker Runt
    [418] = { [1] = 1, [85] = 85, [50] = 50, [51] = 51, [241] = 241, [56] = 56 }, -- Water Snake
    [535] = { [121] = 121 }, -- Water Waveling
    [1593] = { [104] = 104, [539] = 539, [535] = 535, [534] = 534, [577] = 577 }, -- Waterfly
    [1394] = { [585] = 585, [579] = 579 }, -- Weebomination
    [84] = { [52] = 52 }, -- Westfall Chicken
    [410] = { [210] = 210, [244] = 244, [245] = 245, [595] = 595 }, -- Wharf Rat
    [46] = { [84] = 84 }, -- White Kitten
    [141] = { [103] = 103 }, -- White Moth
    [1968] = { [118] = 118, [186] = 186 }, -- Wicked Soul
    [2411] = { [1197] = 1197 }, -- Wicker Pup
    [1523] = { [84] = 84, [18] = 18 }, -- Widget the Departed
    [400] = { [47] = 47 }, -- Widow Spiderling
    [819] = { [371] = 371 }, -- Wild Crimson Hatchling
    [818] = { [371] = 371 }, -- Wild Golden Hatchling
    [817] = { [371] = 371 }, -- Wild Jade Hatchling
    [548] = { [241] = 241 }, -- Wildhammer Gryphon Hatchling
    [1959] = { [147] = 147 }, -- Winter Rageling
    [306] = { [83] = 83 }, -- Winterspring Cub
    [220] = { [62] = 62 }, -- Withers
    [153] = { [1] = 1, [27] = 27 }, -- Wolpertinger
    [64] = { [407] = 407 }, -- Wood Frog
    [1463] = { [543] = 543 }, -- Wood Wasp
    [89] = { [250] = 250 }, -- Worg Pup
    [1634] = { [335] = 335 }, -- Wretched Servant
    [1266] = { [554] = 554 }, -- Xu-Fu, Cub of Xuen
    [740] = { [422] = 422, [388] = 388 }, -- Yakrat
    [140] = { [103] = 103 }, -- Yellow Moth
    [752] = { [390] = 390 }, -- Yellow-Bellied Bullfrog
    [549] = { [241] = 241 }, -- Yellow-Bellied Marmot
    [1912] = { [125] = 125, [627] = 627 }, -- Young Mutant Warturtle
    [2392] = { [1194] = 1194 }, -- Young Sand Sifter
    [1304] = { [554] = 554 }, -- Yu'la, Broodling of Yu'lon
    [1211] = { [507] = 507, [991] = 991 }, -- Zandalari Anklerender
    [1212] = { [507] = 507, [991] = 991 }, -- Zandalari Footslasher
    [1180] = { [507] = 507, [991] = 991 }, -- Zandalari Kneebiter
    [2413] = { [1193] = 1193 }, -- Zandalari Shinchomper
    [1213] = { [507] = 507, [991] = 991 }, -- Zandalari Toenibbler
    [1582] = { [104] = 104, [539] = 539 }, -- Zangar Crawler
    [1536] = { [534] = 534, [577] = 577 }, -- Zangar Spore
    [1305] = { [554] = 554 }, -- Zao, Calfling of Niuzao
    [2084] = { [328] = 328 }, -- Zephyrian Prince
    [1428] = { [104] = 104, [539] = 539 }, -- Zomstrok
}

Data.ZoneCompanions = {
    [132] = { [412] = 412 }, -- Ahn'kahet: The Old Kingdom
    [468] = { [397] = 397, [417] = 417, [379] = 379 }, -- Ammen Vale MoP
    [885] = { [2122] = 2122, [2126] = 2126, [2115] = 2115, [2135] = 2135, [2136] = 2136 }, -- Antoran Wastes
    [93] = { [417] = 417 }, -- Arathi Basin
    [14] = { [445] = 445, [448] = 448, [419] = 419, [459] = 459, [417] = 417, [386] = 386, [443] = 443, [2432] = 2432, [2434] = 2434, [2436] = 2436, [2438] = 2438, [2440] = 2440, [2433] = 2433, [2441] = 2441, [2435] = 2435, [2437] = 2437 }, -- Arathi Highlands
    [994] = { [2116] = 2116 }, -- Argus
    [63] = { [450] = 450, [495] = 495, [496] = 496, [478] = 478, [420] = 420, [417] = 417, [424] = 424, [379] = 379 }, -- Ashenvale
    [732] = { [417] = 417, [412] = 412 }, -- Assault on Violet Hold
    [947] = { [2442] = 2442, [2143] = 2143, [2439] = 2439, [130] = 130, [2429] = 2429 }, -- Azeroth
    [76] = { [388] = 388, [397] = 397, [469] = 469, [470] = 470, [471] = 471, [472] = 472, [473] = 473, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [379] = 379, [1728] = 1728, [1729] = 1729, [1914] = 1914 }, -- Azshara
    [630] = { [569] = 569, [1728] = 1728, [1729] = 1729, [1914] = 1914, [1708] = 1708, [1710] = 1710, [1716] = 1716, [1720] = 1720, [1731] = 1731, [1736] = 1736, [1773] = 1773, [1774] = 1774, [1931] = 1931, [1709] = 1709, [2077] = 2077 }, -- Azsuna
    [97] = { [464] = 464 }, -- Azuremyst Isle
    [15] = { [56] = 56, [398] = 398, [406] = 406, [430] = 430, [431] = 431, [432] = 432, [433] = 433, [438] = 438 }, -- Badlands
    [339] = { [1625] = 1625, [1628] = 1628, [1623] = 1623, [1626] = 1626, [1627] = 1627, [1624] = 1624, [412] = 412 }, -- Black Temple
    [250] = { [89] = 89, [90] = 90 }, -- Blackrock Spire
    [285] = { [2078] = 2078, [2080] = 2080, [2079] = 2079 }, -- Blackwing Descent
    [287] = { [1151] = 1151, [1152] = 1152, [1153] = 1153 }, -- Blackwing Lair
    [105] = { [449] = 449, [528] = 528, [414] = 414, [482] = 482, [1164] = 1164, [637] = 637, [378] = 378, [379] = 379 }, -- Blade's Edge Mountains
    [17] = { [635] = 635, [1563] = 1563, [1387] = 1387, [414] = 414, [415] = 415, [412] = 412, [416] = 416 }, -- Blasted Lands
    [106] = { [397] = 397, [465] = 465, [417] = 417, [627] = 627, [628] = 628 }, -- Bloodmyst Isle
    [114] = { [639] = 639, [641] = 641, [388] = 388, [530] = 530, [536] = 536 }, -- Borean Tundra
    [503] = { [1142] = 1142, [2022] = 2022 }, -- Brawl'gar Arena
    [646] = { [2042] = 2042 }, -- Broken Shore
    [36] = { [56] = 56, [393] = 393, [414] = 414, [415] = 415, [423] = 423, [425] = 425, [429] = 429, [287] = 287 }, -- Burning Steppes
    [127] = { [190] = 190, [224] = 224, [236] = 236, [417] = 417, [378] = 378, [379] = 379, [1727] = 1727 }, -- Crystalsong Forest
    [627] = { [193] = 193, [74] = 74, [1604] = 1604, [1429] = 1429, [1453] = 1453, [1715] = 1715, [1727] = 1727, [1755] = 1755, [1760] = 1760, [1778] = 1778, [1805] = 1805, [1912] = 1912, [1915] = 1915, [1754] = 1754, [1911] = 1911, [2004] = 2004 }, -- Dalaran
    [125] = { [193] = 193, [74] = 74, [1604] = 1604, [1429] = 1429, [1453] = 1453, [1715] = 1715, [1727] = 1727, [1755] = 1755, [1760] = 1760, [1778] = 1778, [1805] = 1805, [1912] = 1912, [1915] = 1915, [1754] = 1754, [1911] = 1911, [2004] = 2004 }, -- Dalaran
    [407] = { [64] = 64, [65] = 65, [1062] = 1062, [1276] = 1276, [330] = 330, [335] = 335, [336] = 336, [338] = 338, [339] = 339, [340] = 340, [343] = 343, [848] = 848, [1068] = 1068, [1061] = 1061, [1665] = 1665, [1666] = 1666 }, -- Darkmoon Island
    [62] = { [630] = 630, [508] = 508, [401] = 401, [417] = 417, [493] = 493, [220] = 220, [378] = 378, [379] = 379 }, -- Darkshore
    [89] = { [452] = 452, [419] = 419, [478] = 478, [479] = 479 }, -- Darnassus
    [42] = { [1160] = 1160, [439] = 439 }, -- Deadwind Pass
    [207] = { [555] = 555, [469] = 469, [554] = 554, [470] = 470, [556] = 556, [559] = 559, [480] = 480, [837] = 837, [838] = 838, [293] = 293, [553] = 553, [279] = 279, [756] = 756 }, -- Deepholm
    [66] = { [452] = 452, [419] = 419, [478] = 478, [479] = 479, [480] = 480, [482] = 482, [483] = 483, [838] = 838, [484] = 484, [417] = 417, [485] = 485, [424] = 424 }, -- Desolace
    [409] = { [2090] = 2090 }, -- Dragon Soul
    [115] = { [641] = 641, [536] = 536, [401] = 401, [198] = 198, [537] = 537 }, -- Dragonblight
    [160] = { [417] = 417, [412] = 412 }, -- Drak'Tharon Keep
    [422] = { [834] = 834, [742] = 742, [836] = 836, [740] = 740, [741] = 741, [743] = 743, [744] = 744, [745] = 745, [746] = 746, [732] = 732 }, -- Dread Wastes MoP
    [1197] = { [2378] = 2378, [2386] = 2386, [2406] = 2406, [2424] = 2424, [2189] = 2189, [2405] = 2405, [2407] = 2407, [2411] = 2411, [2408] = 2408, [2198] = 2198 }, -- Drustvar
    [27] = { [1518] = 1518, [635] = 635, [166] = 166, [401] = 401, [404] = 404, [72] = 72, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [440] = 440, [441] = 441, [442] = 442, [379] = 379, [153] = 153 }, -- Dun Morogh
    [1] = { [1518] = 1518, [635] = 635, [448] = 448, [166] = 166, [466] = 466, [467] = 467, [468] = 468, [418] = 418, [420] = 420, [1237] = 1237, [153] = 153 }, -- Durotar
    [47] = { [385] = 385, [646] = 646, [396] = 396, [397] = 397, [398] = 398, [399] = 399, [400] = 400, [424] = 424, [378] = 378, [379] = 379 }, -- Duskwood
    [70] = { [56] = 56, [385] = 385, [387] = 387, [646] = 646, [398] = 398, [232] = 232, [420] = 420, [412] = 412, [489] = 489, [379] = 379 }, -- Dustwallow Marsh
    [23] = { [393] = 393, [457] = 457, [398] = 398, [286] = 286, [406] = 406, [414] = 414, [412] = 412, [626] = 626, [627] = 627, [628] = 628 }, -- Eastern Plaguelands
    [37] = { [40] = 40, [447] = 447, [646] = 646, [41] = 41, [419] = 419, [459] = 459, [43] = 43, [45] = 45, [412] = 412, [675] = 675, [374] = 374, [378] = 378, [379] = 379 }, -- Elwynn Forest
    [94] = { [387] = 387, [419] = 419, [459] = 459, [460] = 460, [142] = 142, [143] = 143, [144] = 144, [420] = 420, [378] = 378 }, -- Eversong Woods
    [790] = { [1728] = 1728, [1729] = 1729, [1914] = 1914, [1926] = 1926 }, -- Eye of Azshara
    [713] = { [1728] = 1728, [1729] = 1729, [1914] = 1914 }, -- Eye of Azshara
    [77] = { [406] = 406, [420] = 420, [497] = 497, [498] = 498, [499] = 499, [500] = 500 }, -- Felwood
    [69] = { [387] = 387, [59] = 59, [557] = 557, [87] = 87, [1158] = 1158, [378] = 378, [379] = 379 }, -- Feralas
    [367] = { [2086] = 2086, [2087] = 2087, [2089] = 2089, [2088] = 2088 }, -- Firelands
    [525] = { [1578] = 1578, [1579] = 1579, [541] = 541, [417] = 417, [1427] = 1427, [1457] = 1457, [1464] = 1464, [1471] = 1471 }, -- Frostfire Ridge
    [585] = { [560] = 560, [1396] = 1396, [1688] = 1688, [1588] = 1588, [1598] = 1598, [1577] = 1577, [1661] = 1661, [1385] = 1385, [1545] = 1545, [1568] = 1568, [1442] = 1442, [1434] = 1434, [1570] = 1570, [1394] = 1394, [115] = 115, [1448] = 1448 }, -- Frostwall
    [95] = { [450] = 450, [387] = 387, [419] = 419, [461] = 461, [463] = 463, [420] = 420, [417] = 417, [412] = 412 }, -- Ghostlands
    [179] = { [397] = 397, [401] = 401, [417] = 417, [412] = 412, [424] = 424, [379] = 379 }, -- Gilneas
    [202] = { [417] = 417, [412] = 412, [424] = 424 }, -- Gilneas City
    [226] = { [1162] = 1162 }, -- Gnomeregan
    [543] = { [1564] = 1564, [449] = 449, [1537] = 1537, [393] = 393, [1594] = 1594, [1615] = 1615, [568] = 568, [702] = 702, [430] = 430, [1463] = 1463, [1465] = 1465, [1464] = 1464, [1469] = 1469, [1470] = 1470 }, -- Gorgrond
    [606] = { [635] = 635 }, -- Grimrail Depot
    [116] = { [385] = 385, [647] = 647, [534] = 534, [633] = 633 }, -- Grizzly Hills
    [153] = { [234] = 234 }, -- Gundrak
    [185] = { [412] = 412 }, -- Halls of Reflection
    [649] = { [1753] = 1753 }, -- Helheim
    [661] = { [1672] = 1672 }, -- Hellfire Citadel
    [100] = { [635] = 635, [414] = 414, [514] = 514 }, -- Hellfire Peninsula
    [650] = { [391] = 391, [407] = 407, [569] = 569, [417] = 417, [487] = 487, [1441] = 1441, [1590] = 1590, [378] = 378, [379] = 379, [1711] = 1711, [1713] = 1713, [1726] = 1726, [1731] = 1731, [1743] = 1743, [1744] = 1744, [1752] = 1752, [1761] = 1761, [1762] = 1762, [1763] = 1763, [1775] = 1775, [1776] = 1776, [1884] = 1884, [1714] = 1714 }, -- Highmountain
    [25] = { [640] = 640, [450] = 450, [646] = 646, [452] = 452, [648] = 648, [453] = 453, [42] = 42, [291] = 291, [1159] = 1159, [420] = 420, [417] = 417, [412] = 412, [378] = 378, [379] = 379 }, -- Hillsbrad Foothills
    [117] = { [450] = 450, [644] = 644, [387] = 387, [646] = 646, [388] = 388, [523] = 523, [525] = 525, [529] = 529, [397] = 397, [198] = 198, [420] = 420, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [379] = 379 }, -- Howling Fjord
    [329] = { [1629] = 1629, [1622] = 1622, [1631] = 1631 }, -- Hyjal Summit
    [118] = { [393] = 393, [229] = 229, [538] = 538, [204] = 204, [205] = 205, [206] = 206, [207] = 207, [212] = 212, [209] = 209, [213] = 213, [214] = 214, [412] = 412, [215] = 215, [216] = 216, [218] = 218, [424] = 424, [210] = 210, [1963] = 1963, [1964] = 1964, [1965] = 1965, [1966] = 1966, [1967] = 1967, [1968] = 1968 }, -- Icecrown
    [186] = { [412] = 412, [424] = 424, [1963] = 1963, [1964] = 1964, [1965] = 1965, [1966] = 1966, [1967] = 1967, [1968] = 1968 }, -- Icecrown Citadel
    [595] = { [393] = 393, [410] = 410 }, -- Iron Docks
    [507] = { [1213] = 1213, [1211] = 1211, [1185] = 1185, [1180] = 1180, [1212] = 1212, [1205] = 1205 }, -- Isle of Giants
    [504] = { [1181] = 1181, [1175] = 1175, [1179] = 1179, [1178] = 1178, [1182] = 1182 }, -- Isle of Thunder
    [350] = { [187] = 187, [417] = 417, [412] = 412, [1227] = 1227, [1226] = 1226, [1228] = 1228, [1229] = 1229 }, -- Karazhan
    [194] = { [401] = 401, [424] = 424 }, -- Kezan
    [418] = { [388] = 388, [1013] = 1013, [1128] = 1128, [678] = 678, [560] = 560, [717] = 717, [708] = 708, [714] = 714, [718] = 718, [722] = 722, [723] = 723, [716] = 716, [652] = 652 }, -- Krasarang Wilds MoP
    [830] = { [2124] = 2124, [2123] = 2123, [2127] = 2127 }, -- Krokuun
    [48] = { [387] = 387, [419] = 419, [417] = 417, [437] = 437, [424] = 424, [379] = 379 }, -- Loch Modan
    [579] = { [1396] = 1396, [1688] = 1688, [1588] = 1588, [1598] = 1598, [1577] = 1577, [1661] = 1661, [1385] = 1385, [1545] = 1545, [1568] = 1568, [1442] = 1442, [1434] = 1434, [1570] = 1570, [1394] = 1394, [115] = 115, [1448] = 1448 }, -- Lunarfall
    [882] = { [2120] = 2120, [2128] = 2128, [2130] = 2130, [2132] = 2132, [2129] = 2129, [2134] = 2134, [2133] = 2133, [2131] = 2131 }, -- Mac'Aree
    [348] = { [175] = 175, [379] = 379 }, -- Magisters' Terrace
    [232] = { [1544] = 1544, [1147] = 1147, [1149] = 1149, [1150] = 1150 }, -- Molten Core
    [338] = { [317] = 317, [172] = 172, [318] = 318 }, -- Molten Front
    [80] = { [341] = 341, [342] = 342, [478] = 478, [503] = 503, [378] = 378, [379] = 379 }, -- Moonglade
    [198] = { [632] = 632, [259] = 259, [539] = 539, [540] = 540, [541] = 541, [547] = 547, [469] = 469, [478] = 478, [415] = 415, [479] = 479, [482] = 482, [487] = 487, [503] = 503, [378] = 378, [626] = 626, [755] = 755, [260] = 260, [379] = 379 }, -- Mount Hyjal
    [7] = { [385] = 385, [70] = 70, [477] = 477, [386] = 386, [378] = 378 }, -- Mulgore
    [107] = { [635] = 635, [1524] = 1524, [387] = 387, [518] = 518, [388] = 388, [397] = 397, [420] = 420, [417] = 417, [1435] = 1435, [1441] = 1441, [1446] = 1446, [386] = 386, [378] = 378, [379] = 379, [1764] = 1764, [1765] = 1765, [1766] = 1766 }, -- Nagrand
    [550] = { [635] = 635, [1524] = 1524, [387] = 387, [518] = 518, [388] = 388, [397] = 397, [420] = 420, [417] = 417, [1435] = 1435, [1441] = 1441, [1446] = 1446, [386] = 386, [378] = 378, [379] = 379, [1764] = 1764, [1765] = 1765, [1766] = 1766 }, -- Nagrand
    [162] = { [1146] = 1146, [1143] = 1143, [1144] = 1144, [417] = 417, [412] = 412 }, -- Naxxramas
    [1194] = { [2388] = 2388, [2392] = 2392, [2394] = 2394, [2398] = 2398, [2400] = 2400, [2414] = 2414, [2420] = 2420, [2424] = 2424, [2157] = 2157, [2389] = 2389, [2395] = 2395, [2415] = 2415, [2419] = 2419, [2393] = 2393, [2397] = 2397 }, -- Nazmir
    [109] = { [638] = 638, [385] = 385, [521] = 521, [459] = 459, [136] = 136, [137] = 137, [51] = 51, [44] = 44, [145] = 145, [139] = 139, [55] = 55, [78] = 78 }, -- Netherstorm
    [10] = { [631] = 631, [635] = 635, [419] = 419, [474] = 474, [1157] = 1157, [386] = 386 }, -- Northern Barrens
    [50] = { [635] = 635, [387] = 387, [49] = 49, [401] = 401, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [407] = 407, [408] = 408, [409] = 409, [239] = 239, [418] = 418, [421] = 421, [301] = 301, [424] = 424 }, -- Northern Stranglethorn
    [85] = { [272] = 272, [1449] = 1449, [332] = 332, [792] = 792, [1331] = 1331, [1332] = 1332, [466] = 466, [467] = 467, [270] = 270, [471] = 471, [281] = 281, [282] = 282, [283] = 283, [1334] = 1334, [280] = 280, [414] = 414, [418] = 418, [420] = 420, [211] = 211, [75] = 75, [1322] = 1322, [412] = 412, [320] = 320, [78] = 78, [77] = 77, [629] = 629, [1890] = 1890 }, -- Orgrimmar
    [184] = { [412] = 412 }, -- Pit of Saron
    [300] = { [424] = 424 }, -- Razorfen Downs
    [49] = { [646] = 646, [391] = 391, [392] = 392, [395] = 395, [424] = 424, [378] = 378 }, -- Redridge Mountains
    [809] = { [187] = 187, [417] = 417, [412] = 412, [1227] = 1227, [1226] = 1226, [1228] = 1228, [1229] = 1229 }, -- Return to Karazhan
    [217] = { [417] = 417, [412] = 412, [379] = 379 }, -- Ruins of Gilneas
    [302] = { [417] = 417 }, -- Scarlet Monastery
    [306] = { [417] = 417 }, -- Scholomance
    [32] = { [415] = 415, [423] = 423, [427] = 427, [428] = 428 }, -- Searing Gorge
    [332] = { [1230] = 1230, [1231] = 1231, [1232] = 1232 }, -- Serpentshrine Cavern
    [104] = { [519] = 519, [1593] = 1593, [407] = 407, [1601] = 1601, [414] = 414, [1428] = 1428, [425] = 425, [1447] = 1447, [1582] = 1582, [412] = 412, [1455] = 1455, [1587] = 1587, [1538] = 1538, [497] = 497 }, -- Shadowmoon Valley
    [539] = { [519] = 519, [1593] = 1593, [407] = 407, [1601] = 1601, [414] = 414, [1428] = 1428, [425] = 425, [1447] = 1447, [1582] = 1582, [412] = 412, [1455] = 1455, [1587] = 1587, [1538] = 1538, [497] = 497 }, -- Shadowmoon Valley
    [111] = { [417] = 417 }, -- Shattrath City
    [119] = { [387] = 387, [649] = 649, [1167] = 1167, [532] = 532, [379] = 379 }, -- Sholazar Basin
    [556] = { [1331] = 1331, [1332] = 1332, [1334] = 1334, [1322] = 1322 }, -- Siege of Orgrimmar
    [81] = { [511] = 511, [512] = 512, [513] = 513, [406] = 406, [414] = 414, [482] = 482, [484] = 484, [433] = 433, [2163] = 2163, [2439] = 2439, [2429] = 2429 }, -- Silithus
    [110] = { [459] = 459, [378] = 378 }, -- Silvermoon City
    [21] = { [387] = 387, [455] = 455, [420] = 420, [417] = 417, [378] = 378, [627] = 627, [628] = 628, [379] = 379 }, -- Silverpine Forest
    [199] = { [631] = 631, [635] = 635, [419] = 419, [475] = 475, [386] = 386 }, -- Southern Barrens
    [542] = { [635] = 635, [1532] = 1532, [1540] = 1540, [1541] = 1541, [1596] = 1596, [1573] = 1573, [401] = 401, [568] = 568, [1597] = 1597, [417] = 417, [1441] = 1441, [1456] = 1456, [1462] = 1462, [1590] = 1590, [379] = 379, [1592] = 1592 }, -- Spires of Arak
    [65] = { [472] = 472, [417] = 417, [487] = 487, [488] = 488, [412] = 412, [424] = 424, [378] = 378, [633] = 633, [506] = 506 }, -- Stonetalon Mountains
    [634] = { [1708] = 1708, [1712] = 1712, [1713] = 1713, [1721] = 1721, [1736] = 1736, [1743] = 1743, [1744] = 1744, [1749] = 1749, [1917] = 1917, [1750] = 1750, [1885] = 1885 }, -- Stormheim
    [622] = { [1574] = 1574 }, -- Stormshield
    [1198] = { [2372] = 2372, [2374] = 2374, [2378] = 2378, [2404] = 2404, [2426] = 2426, [2428] = 2428, [2373] = 2373, [2375] = 2375, [2379] = 2379, [2403] = 2403, [2423] = 2423, [2427] = 2427, [2376] = 2376, [2421] = 2421, [2377] = 2377, [2422] = 2422, [2425] = 2425 }, -- Stormsong Valley
    [84] = { [1523] = 1523, [319] = 319, [417] = 417, [1521] = 1521, [46] = 46, [675] = 675, [378] = 378, [379] = 379, [1890] = 1890 }, -- Stormwind City
    [317] = { [417] = 417, [412] = 412, [424] = 424 }, -- Stratholme
    [335] = { [1634] = 1634, [1632] = 1632, [1633] = 1633 }, -- Sunwell Plateau
    [680] = { [425] = 425, [1914] = 1914, [1717] = 1717, [1719] = 1719, [1807] = 1807, [1808] = 1808, [1809] = 1809, [1921] = 1921, [1922] = 1922, [1934] = 1934, [1810] = 1810 }, -- Suramar
    [51] = { [648] = 648, [419] = 419, [401] = 401, [402] = 402, [403] = 403, [418] = 418, [420] = 420, [417] = 417, [422] = 422, [412] = 412 }, -- Swamp of Sorrows
    [535] = { [1515] = 1515, [452] = 452, [1572] = 1572, [1583] = 1583, [1595] = 1595, [1593] = 1593, [560] = 560, [1599] = 1599, [568] = 568, [1416] = 1416, [1576] = 1576, [1441] = 1441, [427] = 427, [1587] = 1587, [1589] = 1589 }, -- Talador
    [534] = { [450] = 450, [519] = 519, [1593] = 1593, [405] = 405, [483] = 483, [417] = 417, [1468] = 1468, [1536] = 1536, [1539] = 1539, [1586] = 1586, [1591] = 1591, [1660] = 1660, [1663] = 1663, [1664] = 1664, [1692] = 1692, [1693] = 1693, [1690] = 1690, [1581] = 1581 }, -- Tanaan Jungle
    [577] = { [450] = 450, [519] = 519, [1593] = 1593, [405] = 405, [483] = 483, [417] = 417, [1468] = 1468, [1536] = 1536, [1539] = 1539, [1586] = 1586, [1591] = 1591, [1660] = 1660, [1663] = 1663, [1664] = 1664, [1692] = 1692, [1693] = 1693, [1690] = 1690, [1581] = 1581 }, -- Tanaan Jungle - Assault on the Dark Portal
    [71] = { [560] = 560, [484] = 484, [491] = 491, [492] = 492, [430] = 430, [494] = 494, [431] = 431, [432] = 432 }, -- Tanaris
    [57] = { [507] = 507, [447] = 447, [452] = 452, [68] = 68, [419] = 419, [67] = 67, [478] = 478, [479] = 479, [420] = 420, [412] = 412, [379] = 379 }, -- Teldrassil
    [319] = { [1154] = 1154, [1155] = 1155, [1156] = 1156 }, -- Temple of Ahn'Qiraj
    [1038] = { [2186] = 2186 }, -- Temple of Sethraliss
    [108] = { [387] = 387, [646] = 646, [132] = 132, [397] = 397, [417] = 417, [149] = 149, [517] = 517, [432] = 432, [186] = 186, [379] = 379 }, -- Terokkar Forest
    [294] = { [2082] = 2082, [2081] = 2081, [2083] = 2083 }, -- The Bastion of Twilight
    [210] = { [49] = 49, [401] = 401, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [51] = 51, [407] = 407, [408] = 408, [410] = 410, [411] = 411, [239] = 239, [417] = 417, [421] = 421, [424] = 424, [47] = 47 }, -- The Cape of Stranglethorn
    [130] = { [417] = 417, [412] = 412, [424] = 424 }, -- The Culling of Stratholme
    [291] = { [50] = 50, [417] = 417 }, -- The Deadmines
    [777] = { [1722] = 1722, [1723] = 1723 }, -- The Emerald Nightmare
    [103] = { [141] = 141, [140] = 140, [138] = 138 }, -- The Exodar
    [334] = { [1233] = 1233, [1234] = 1234, [1235] = 1235 }, -- The Eye
    [183] = { [412] = 412 }, -- The Forge of Souls
    [26] = { [446] = 446, [448] = 448, [449] = 449, [450] = 450, [393] = 393, [417] = 417, [412] = 412 }, -- The Hinterlands
    [371] = { [380] = 380, [817] = 817, [818] = 818, [819] = 819, [562] = 562, [564] = 564, [567] = 567, [566] = 566, [568] = 568, [570] = 570, [569] = 569, [571] = 571, [699] = 699, [572] = 572, [702] = 702, [703] = 703, [565] = 565, [847] = 847, [573] = 573, [754] = 754 }, -- The Jade Forest MoP
    [174] = { [401] = 401, [417] = 417 }, -- The Lost Isles
    [246] = { [417] = 417 }, -- The Shattered Halls
    [120] = { [641] = 641, [558] = 558, [412] = 412, [633] = 633, [1969] = 1969 }, -- The Storm Peaks
    [168] = { [417] = 417, [412] = 412 }, -- The Violet Hold
    [378] = { [2047] = 2047 }, -- The Wandering Isle MoP
    [64] = { [398] = 398, [414] = 414, [52] = 52, [424] = 424, [505] = 505 }, -- Thousand Needles
    [328] = { [2084] = 2084, [2085] = 2085 }, -- Throne of the Four Winds
    [322] = { [328] = 328 }, -- Throne of the Tides
    [508] = { [1183] = 1183, [1200] = 1200, [1177] = 1177, [1243] = 1243, [1202] = 1202, [1244] = 1244 }, -- Throne of Thunder
    [88] = { [386] = 386 }, -- Thunder Bluff
    [554] = { [1304] = 1304, [1323] = 1323, [1324] = 1324, [1326] = 1326, [1328] = 1328, [1337] = 1337, [1333] = 1333, [1338] = 1338, [1343] = 1343, [1344] = 1344, [1346] = 1346, [1350] = 1350, [1336] = 1336, [1335] = 1335, [1348] = 1348, [1345] = 1345, [417] = 417, [1325] = 1325, [1330] = 1330, [1329] = 1329, [1303] = 1303, [1321] = 1321, [1305] = 1305, [1266] = 1266, [2017] = 2017, [2018] = 2018 }, -- Timeless Isle
    [1196] = { [2380] = 2380, [2382] = 2382, [2410] = 2410, [2430] = 2430, [2381] = 2381, [2383] = 2383, [2377] = 2377, [2409] = 2409, [2165] = 2165 }, -- Tiragarde Sound
    [18] = { [1523] = 1523, [319] = 319, [450] = 450, [646] = 646, [454] = 454, [458] = 458, [417] = 417, [1521] = 1521, [412] = 412, [424] = 424, [55] = 55, [378] = 378, [626] = 626, [2002] = 2002 }, -- Tirisfal Glades
    [244] = { [271] = 271, [278] = 278, [410] = 410, [379] = 379 }, -- Tol Barad
    [245] = { [271] = 271, [278] = 278, [410] = 410, [379] = 379 }, -- Tol Barad Peninsula
    [974] = { [2187] = 2187 }, -- Tol Dagor
    [388] = { [1201] = 1201, [680] = 680, [733] = 733, [737] = 737, [739] = 739, [740] = 740, [732] = 732 }, -- Townlong Steppes MoP
    [172] = { [1952] = 1952, [1953] = 1953, [1954] = 1954 }, -- Trial of the Crusader
    [241] = { [645] = 645, [647] = 647, [388] = 388, [648] = 648, [393] = 393, [398] = 398, [548] = 548, [549] = 549, [550] = 550, [552] = 552, [470] = 470, [823] = 823, [414] = 414, [418] = 418, [420] = 420, [293] = 293, [431] = 431, [379] = 379 }, -- Twilight Highlands
    [147] = { [1955] = 1955, [1956] = 1956, [1957] = 1957, [1958] = 1958, [1959] = 1959, [1960] = 1960, [1961] = 1961, [1962] = 1962 }, -- Ulduar
    [249] = { [631] = 631, [511] = 511, [542] = 542, [544] = 544, [545] = 545, [467] = 467, [484] = 484, [293] = 293, [851] = 851, [546] = 546, [543] = 543 }, -- Uldum
    [78] = { [631] = 631, [632] = 632, [393] = 393, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [237] = 237, [415] = 415, [502] = 502, [503] = 503, [504] = 504 }, -- Un'Goro Crater
    [133] = { [412] = 412 }, -- Utgarde Keep
    [136] = { [412] = 412 }, -- Utgarde Pinnacle
    [641] = { [379] = 379, [1705] = 1705, [1706] = 1706, [1734] = 1734, [1736] = 1736, [1737] = 1737, [1738] = 1738, [1739] = 1739, [1802] = 1802, [1804] = 1804, [1907] = 1907, [1913] = 1913, [1927] = 1927, [1735] = 1735 }, -- Val'sharah
    [390] = { [383] = 383, [748] = 748, [1124] = 1124, [1126] = 1126, [1125] = 1125, [747] = 747, [868] = 868, [749] = 749, [750] = 750, [751] = 751, [752] = 752 }, -- Vale of Eternal Blossoms MoP
    [376] = { [1042] = 1042, [650] = 650, [677] = 677, [709] = 709, [706] = 706, [707] = 707, [708] = 708, [710] = 710, [711] = 711, [712] = 712, [713] = 713 }, -- Valley of the Four Winds MoP
    [1195] = { [2188] = 2188, [2190] = 2190, [2426] = 2426, [2428] = 2428, [2399] = 2399, [2417] = 2417, [2423] = 2423, [2425] = 2425 }, -- Vol'dun
    [279] = { [233] = 233, [2049] = 2049 }, -- Wailing Caverns
    [624] = { [1574] = 1574 }, -- Warspear
    [398] = { [379] = 379 }, -- Well of Eternity
    [22] = { [456] = 456, [398] = 398, [378] = 378, [379] = 379 }, -- Western Plaguelands
    [52] = { [385] = 385, [387] = 387, [646] = 646, [388] = 388, [389] = 389, [84] = 84, [386] = 386, [378] = 378, [379] = 379, [2041] = 2041, [2058] = 2058, [2057] = 2057 }, -- Westfall
    [56] = { [509] = 509, [56] = 56, [385] = 385, [646] = 646, [393] = 393, [398] = 398, [58] = 58, [418] = 418, [420] = 420, [378] = 378, [633] = 633, [238] = 238, [379] = 379 }, -- Wetlands
    [83] = { [634] = 634, [57] = 57, [69] = 69, [471] = 471, [472] = 472, [487] = 487, [1163] = 1163, [412] = 412, [306] = 306, [633] = 633, [441] = 441 }, -- Winterspring
    [991] = { [1213] = 1213, [1211] = 1211, [1180] = 1180, [1212] = 1212 }, -- Zandalar
    [102] = { [515] = 515, [387] = 387, [419] = 419, [167] = 167, [146] = 146 }, -- Zangarmarsh
    [333] = { [165] = 165, [412] = 412, [379] = 379 }, -- Zul'Aman
    [121] = { [641] = 641, [387] = 387, [648] = 648, [234] = 234, [412] = 412, [535] = 535 }, -- Zul'Drak
    [337] = { [307] = 307 }, -- Zul'Gurub
    [1193] = { [2384] = 2384, [2412] = 2412, [2416] = 2416, [2418] = 2418, [2430] = 2430, [2444] = 2444, [2385] = 2385, [2427] = 2427, [2413] = 2413, [2421] = 2421, [2422] = 2422, [2390] = 2390, [2196] = 2196, [2387] = 2387 }, -- Zuldazar
}

