-- auto generated by collectmedb on 2018-01-26 23:18:44

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

Data.CompanionsZone = {
    [1624] = { [796] = 796 }, -- Abyssius
    [635] = { [4] = 4, [11] = 11, [607] = 607, [19] = 19, [27] = 27, [37] = 37, [465] = 465, [477] = 477, [950] = 950, [948] = 948, [993] = 993 }, -- Adder
    [1805] = { [1014] = 1014 }, -- Alarm-o-Bot
    [1708] = { [1015] = 1015, [1017] = 1017 }, -- Albatross Chick
    [1385] = { [976] = 976, [971] = 971 }, -- Albino Chimaeraling
    [74] = { [504] = 504, [1014] = 1014 }, -- Albino Snake
    [487] = { [606] = 606, [81] = 81, [281] = 281, [1024] = 1024 }, -- Alpine Chipmunk
    [441] = { [281] = 281, [27] = 27 }, -- Alpine Hare
    [732] = { [858] = 858, [810] = 810 }, -- Amber Moth
    [1465] = { [949] = 949 }, -- Amberbarb Wasp
    [838] = { [101] = 101, [640] = 640 }, -- Amethyst Shale Hatchling
    [716] = { [857] = 857 }, -- Amethyst Spiderling
    [212] = { [492] = 492 }, -- Ammen Vale Lashling
    [52] = { [61] = 61 }, -- Ancona Chicken
    [1163] = { [281] = 281 }, -- Anodized Robo Cub
    [2122] = { [1171] = 1171 }, -- Antoran Bile Larva
    [2126] = { [1171] = 1171 }, -- Antoran Bilescourge
    [1155] = { [766] = 766 }, -- Anubisath Idol
    [836] = { [858] = 858 }, -- Aqua Strider
    [1160] = { [32] = 32 }, -- Arcane Eye
    [2131] = { [1170] = 1170 }, -- Arcane Gorger
    [558] = { [495] = 495 }, -- Arctic Fox Kit
    [641] = { [486] = 486, [488] = 488, [495] = 495, [496] = 496 }, -- Arctic Hare
    [216] = { [492] = 492 }, -- Argent Gruntling
    [214] = { [492] = 492 }, -- Argent Squire
    [272] = { [321] = 321 }, -- Armadillo Pup
    [632] = { [606] = 606, [201] = 201 }, -- Ash Lizard
    [427] = { [28] = 28, [946] = 946 }, -- Ash Spiderling
    [425] = { [29] = 29, [473] = 473, [947] = 947, [1033] = 1033 }, -- Ash Viper
    [1927] = { [1018] = 1018 }, -- Ash'ana
    [1323] = { [951] = 951 }, -- Ashleaf Spriteling
    [1706] = { [1018] = 1018 }, -- Ashmaw Cub
    [1150] = { [696] = 696 }, -- Ashstone Core
    [1324] = { [951] = 951 }, -- Ashwing Moth
    [1738] = { [1018] = 1018 }, -- Auburn Ringtail
    [1429] = { [1014] = 1014 }, -- Autumnal Sproutling
    [1470] = { [949] = 949 }, -- Axebeak Hatchling
    [1321] = { [951] = 951 }, -- Azure Crane Chick
    [57] = { [281] = 281 }, -- Azure Whelpling
    [411] = { [673] = 673 }, -- Baby Ape
    [1884] = { [1024] = 1024 }, -- Baby Elderhorn
    [2047] = { [808] = 808 }, -- Ban-Fu, Cub of Ban-Lu
    [706] = { [807] = 807 }, -- Bandicoon
    [707] = { [807] = 807 }, -- Bandicoon Kit
    [626] = { [606] = 606, [23] = 23, [20] = 20 }, -- Bat
    [406] = { [182] = 182, [261] = 261, [201] = 201, [17] = 17, [23] = 23, [37] = 37, [673] = 673 }, -- Beetle
    [1934] = { [1033] = 1033 }, -- Benax
    [2123] = { [1135] = 1135 }, -- Bile Larva
    [2124] = { [1135] = 1135 }, -- Bilescourge
    [649] = { [493] = 493 }, -- Biletoad
    [75] = { [321] = 321 }, -- Black Kingsnake
    [374] = { [30] = 30 }, -- Black Lamb
    [398] = { [141] = 141, [61] = 61, [17] = 17, [34] = 34, [23] = 23, [700] = 700, [22] = 22, [40] = 40 }, -- Black Rat
    [42] = { [24] = 24 }, -- Black Tabby Cat
    [1743] = { [1024] = 1024, [1017] = 1017 }, -- Black-Footed Fox Kit
    [1322] = { [321] = 321, [953] = 953 }, -- Blackfuse Bombling
    [2086] = { [800] = 800 }, -- Blazehound
    [1693] = { [945] = 945 }, -- Blazing Firehawk
    [1753] = { [1022] = 1022 }, -- Bleakwater Jelly
    [1965] = { [492] = 492, [604] = 604 }, -- Blightbreath
    [455] = { [21] = 21 }, -- Blighted Squirrel
    [456] = { [22] = 22 }, -- Blighthawk
    [1915] = { [1014] = 1014 }, -- Blind Rat
    [1964] = { [492] = 492, [604] = 604 }, -- Blood Boil
    [1468] = { [945] = 945 }, -- Bloodbeak
    [1462] = { [948] = 948 }, -- Bloodsting Wasp
    [1577] = { [976] = 976, [971] = 971 }, -- Bloodthorn Hatchling
    [1666] = { [823] = 823 }, -- Blorp
    [145] = { [479] = 479 }, -- Blue Dragonhawk Hatchling
    [259] = { [606] = 606 }, -- Blue Mini Jouster
    [138] = { [471] = 471 }, -- Blue Moth
    [40] = { [30] = 30 }, -- Bombay Cat
    [1963] = { [492] = 492, [604] = 604 }, -- Boneshard
    [1343] = { [951] = 951 }, -- Bonkers
    [639] = { [486] = 486 }, -- Borean Marmot
    [2082] = { [758] = 758 }, -- Bound Stream
    [1572] = { [946] = 946 }, -- Brilliant Bloodfeather
    [1540] = { [948] = 948 }, -- Brilliant Spore
    [1563] = { [19] = 19 }, -- Bronze Whelpling
    [449] = { [26] = 26, [475] = 475, [949] = 949 }, -- Brown Marmot
    [70] = { [9] = 9 }, -- Brown Prairie Dog
    [137] = { [479] = 479 }, -- Brown Rabbit
    [77] = { [321] = 321 }, -- Brown Snake
    [380] = { [806] = 806 }, -- Bucktooth Flapper
    [1726] = { [1024] = 1024 }, -- Burrow Spiderling
    [224] = { [510] = 510 }, -- Calico Cat
    [540] = { [606] = 606 }, -- Carrion Rat
    [459] = { [16] = 16, [30] = 30, [462] = 462, [480] = 480, [479] = 479 }, -- Cat
    [1586] = { [945] = 945 }, -- Cerulean Moth
    [1633] = { [789] = 789 }, -- Chaos Pup
    [474] = { [11] = 11 }, -- Cheetah Cub
    [1303] = { [951] = 951 }, -- Chi-Chi, Hatchling of Chi-Ji
    [646] = { [141] = 141, [34] = 34, [30] = 30, [24] = 24, [36] = 36, [20] = 20, [39] = 39, [40] = 40, [478] = 478, [491] = 491 }, -- Chicken
    [1152] = { [755] = 755 }, -- Chrominius
    [2087] = { [800] = 800 }, -- Cinderweb Recluse
    [518] = { [477] = 477 }, -- Clefthoof Runt
    [1142] = { [925] = 925 }, -- Clock'em
    [742] = { [858] = 858 }, -- Clouded Hedgehog
    [1914] = { [1015] = 1015, [1096] = 1096, [1033] = 1033 }, -- Coastal Sandpiper
    [47] = { [673] = 673 }, -- Cockatiel
    [393] = { [201] = 201, [29] = 29, [23] = 23, [26] = 26, [700] = 700, [40] = 40, [492] = 492, [949] = 949, [987] = 987 }, -- Cockroach
    [1164] = { [475] = 475 }, -- Cogblade Raptor
    [1232] = { [780] = 780 }, -- Coilfang Stalker
    [562] = { [806] = 806 }, -- Coral Adder
    [488] = { [81] = 81 }, -- Coral Snake
    [1775] = { [1024] = 1024 }, -- Coralback Fiddler
    [1149] = { [696] = 696 }, -- Corefire Imp
    [1890] = { [321] = 321, [301] = 301 }, -- Corgi Pup
    [41] = { [30] = 30 }, -- Cornish Rex Cat
    [1672] = { [1026] = 1026 }, -- Corrupted Nest Guardian
    [1931] = { [1015] = 1015 }, -- Court Scribe
    [1396] = { [976] = 976, [971] = 971 }, -- Crazy Carrot
    [1962] = { [529] = 529 }, -- Creeping Tentacle
    [468] = { [4] = 4 }, -- Creepy Crawly
    [507] = { [41] = 41 }, -- Crested Owl
    [559] = { [640] = 640 }, -- Crimson Geode
    [318] = { [795] = 795 }, -- Crimson Lasher
    [421] = { [37] = 37, [673] = 673 }, -- Crimson Moth
    [554] = { [640] = 640 }, -- Crimson Shale Hatchling
    [78] = { [321] = 321, [479] = 479 }, -- Crimson Snake
    [1537] = { [949] = 949 }, -- Crimson Spore
    [58] = { [40] = 40 }, -- Crimson Whelpling
    [1589] = { [946] = 946 }, -- Crimsonwing Moth
    [1752] = { [1024] = 1024 }, -- Crispin
    [2115] = { [1171] = 1171 }, -- Cross Gazer
    [1068] = { [823] = 823 }, -- Crow
    [745] = { [858] = 858 }, -- Crunchy Scorpion
    [1688] = { [976] = 976, [971] = 971 }, -- Crusher
    [556] = { [640] = 640 }, -- Crystal Beetle
    [634] = { [281] = 281 }, -- Crystal Spider
    [1809] = { [1033] = 1033 }, -- Crystalline Broodling
    [1521] = { [301] = 301, [20] = 20 }, -- Cursed Birman
    [751] = { [811] = 811 }, -- Dancing Water Skimmer
    [1329] = { [951] = 951 }, -- Dandelion Frolicker
    [270] = { [321] = 321 }, -- Dark Phoenix Hatchling
    [56] = { [141] = 141, [17] = 17, [29] = 29, [40] = 40 }, -- Dark Whelpling
    [336] = { [823] = 823 }, -- Darkmoon Balloon
    [343] = { [823] = 823 }, -- Darkmoon Cub
    [1062] = { [823] = 823 }, -- Darkmoon Glowfly
    [1061] = { [823] = 823 }, -- Darkmoon Hatchling
    [330] = { [823] = 823 }, -- Darkmoon Monkey
    [848] = { [823] = 823 }, -- Darkmoon Rabbit
    [338] = { [823] = 823 }, -- Darkmoon Tonk
    [335] = { [823] = 823 }, -- Darkmoon Turtle
    [339] = { [823] = 823 }, -- Darkmoon Zeppelin
    [508] = { [42] = 42 }, -- Darkshore Cub
    [232] = { [141] = 141 }, -- Darting Hatchling
    [1330] = { [951] = 951 }, -- Death Adder Hatchling
    [1153] = { [755] = 755 }, -- Death Talon Whelpguard
    [755] = { [606] = 606 }, -- Death's Head Cockroach
    [1449] = { [321] = 321 }, -- Deathwatch Hatchling
    [555] = { [640] = 640 }, -- Deepholm Cockroach
    [484] = { [101] = 101, [261] = 261, [161] = 161, [720] = 720 }, -- Desert Spider
    [233] = { [749] = 749 }, -- Deviate Hatchling
    [523] = { [491] = 491 }, -- Devouring Maggot
    [504] = { [201] = 201 }, -- Diemetradon Hatchling
    [1205] = { [929] = 929 }, -- Direhorn Runt
    [2079] = { [754] = 754 }, -- Discarded Experiment
    [1564] = { [949] = 949 }, -- Doom Bloom
    [2085] = { [773] = 773 }, -- Drafty
    [537] = { [488] = 488 }, -- Dragonbone Hatchling
    [1952] = { [543] = 543 }, -- Dreadmaw
    [1722] = { [1094] = 1094 }, -- Dream Whelpling
    [1331] = { [321] = 321, [953] = 953 }, -- Droplet of Y'Shaarj
    [1967] = { [492] = 492, [604] = 604 }, -- Drudge Ghoul
    [205] = { [492] = 492 }, -- Dun Morogh Cub
    [467] = { [4] = 4, [321] = 321, [720] = 720 }, -- Dung Beetle
    [207] = { [492] = 492 }, -- Durotar Scorpion
    [396] = { [34] = 34 }, -- Dusk Spiderling
    [1778] = { [1014] = 1014 }, -- Dust Bunny
    [1588] = { [976] = 976, [971] = 971 }, -- Dusty Sporewing
    [1761] = { [1024] = 1024 }, -- Echo Batling
    [747] = { [811] = 811 }, -- Effervescent Glowfly
    [1181] = { [928] = 928 }, -- Elder Python
    [1774] = { [1015] = 1015 }, -- Eldritch Manafiend
    [1179] = { [928] = 928 }, -- Electrified Razortooth
    [293] = { [720] = 720, [700] = 700, [640] = 640 }, -- Elementium Geode
    [479] = { [381] = 381, [101] = 101, [606] = 606, [41] = 41 }, -- Elfin Rabbit
    [209] = { [492] = 492 }, -- Elwynn Lamb
    [631] = { [11] = 11, [607] = 607, [720] = 720, [201] = 201 }, -- Emerald Boa
    [1167] = { [493] = 493 }, -- Emerald Proto-Whelp
    [837] = { [640] = 640 }, -- Emerald Shale Hatchling
    [564] = { [806] = 806 }, -- Emerald Turtle
    [59] = { [121] = 121 }, -- Emerald Whelpling
    [1720] = { [1015] = 1015 }, -- Emmigosa
    [746] = { [858] = 858 }, -- Emperor Crab
    [1766] = { [950] = 950 }, -- Empowered Manafiend
    [1765] = { [950] = 950 }, -- Empyreal Manafiend
    [213] = { [492] = 492 }, -- Enchanted Broom
    [1764] = { [950] = 950 }, -- Energized Manafiend
    [1773] = { [1015] = 1015 }, -- Erudite Manafiend
    [383] = { [811] = 811 }, -- Eternal Strider
    [1717] = { [1033] = 1033 }, -- Extinguished Eye
    [1719] = { [1033] = 1033 }, -- Eye of Inquisition
    [1576] = { [946] = 946 }, -- Eye of Observation
    [2090] = { [824] = 824 }, -- Faceless Mindlasher
    [2083] = { [758] = 758 }, -- Faceless Minion
    [447] = { [41] = 41, [30] = 30 }, -- Fawn
    [519] = { [473] = 473, [947] = 947, [945] = 945 }, -- Fel Flame
    [1760] = { [1014] = 1014 }, -- Fel Piglet
    [1660] = { [945] = 945 }, -- Fel Pup
    [2132] = { [1170] = 1170 }, -- Felcrazed Wyrm
    [319] = { [301] = 301, [20] = 20 }, -- Feline Familiar
    [1731] = { [1015] = 1015, [1024] = 1024 }, -- Felspider
    [1581] = { [945] = 945 }, -- Fen Crab
    [457] = { [23] = 23 }, -- Festering Maggot
    [342] = { [241] = 241 }, -- Festival Lantern
    [1802] = { [1018] = 1018 }, -- Fetid Waveling
    [714] = { [857] = 857 }, -- Feverbite Hatchling
    [1229] = { [799] = 799, [1115] = 1115 }, -- Fiendish Imp
    [415] = { [606] = 606, [201] = 201, [19] = 19, [29] = 29, [28] = 28 }, -- Fire Beetle
    [541] = { [606] = 606, [941] = 941 }, -- Fire-Proof Roach
    [146] = { [467] = 467 }, -- Firefly
    [1545] = { [976] = 976, [971] = 971 }, -- Firewing
    [847] = { [806] = 806 }, -- Fishy
    [644] = { [491] = 491 }, -- Fjord Rat
    [529] = { [491] = 491 }, -- Fjord Worg Pup
    [1325] = { [951] = 951 }, -- Flamering Moth
    [1595] = { [946] = 946 }, -- Flat-Tooth Calf
    [514] = { [465] = 465 }, -- Flayer Youngling
    [395] = { [36] = 36 }, -- Fledgling Buzzard
    [1709] = { [1015] = 1015 }, -- Fledgling Kingfeather
    [521] = { [479] = 479 }, -- Fledgling Nether Ray
    [1710] = { [1015] = 1015 }, -- Fledgling Oliveback
    [1716] = { [1015] = 1015 }, -- Fledgling Warden Owl
    [2127] = { [1135] = 1135 }, -- Flickering Argunite
    [1162] = { [691] = 691 }, -- Fluxfire Feline
    [2058] = { [39] = 39 }, -- Foe Reaper 0.9
    [478] = { [43] = 43, [381] = 381, [101] = 101, [241] = 241, [606] = 606, [41] = 41 }, -- Forest Moth
    [407] = { [37] = 37, [673] = 673, [473] = 473, [947] = 947, [1024] = 1024 }, -- Forest Spiderling
    [278] = { [708] = 708, [709] = 709 }, -- Fox Kit
    [1625] = { [796] = 796 }, -- Fragment of Anger
    [1627] = { [796] = 796 }, -- Fragment of Desire
    [1626] = { [796] = 796 }, -- Fragment of Suffering
    [495] = { [43] = 43 }, -- Frog
    [1427] = { [941] = 941 }, -- Frostfur Rat
    [1578] = { [941] = 941 }, -- Frostshell Pincher
    [1471] = { [941] = 941 }, -- Fruit Hunter
    [1144] = { [535] = 535 }, -- Fungal Abomination
    [756] = { [640] = 640 }, -- Fungal Moth
    [1961] = { [529] = 529 }, -- G0-R41-0N Ultratonk
    [1237] = { [4] = 4 }, -- Gahz'rooki
    [569] = { [806] = 806, [1015] = 1015, [1024] = 1024 }, -- Garden Frog
    [477] = { [9] = 9 }, -- Gazelle Fawn
    [1442] = { [976] = 976, [971] = 971 }, -- Ghastly Kid
    [2077] = { [1015] = 1015 }, -- Ghost Shark
    [190] = { [510] = 510 }, -- Ghostly Skull
    [1665] = { [823] = 823 }, -- Ghostshell Crab
    [1143] = { [535] = 535 }, -- Giant Bone Spider
    [193] = { [504] = 504, [1014] = 1014 }, -- Giant Sewer Rat
    [748] = { [811] = 811 }, -- Gilded Moth
    [630] = { [42] = 42 }, -- Gilnean Raven
    [475] = { [607] = 607 }, -- Giraffe Calf
    [1913] = { [1018] = 1018 }, -- Gleamhoof Fawn
    [1598] = { [976] = 976, [971] = 971 }, -- Glowing Sporebat
    [430] = { [161] = 161, [17] = 17, [949] = 949 }, -- Gold Beetle
    [260] = { [606] = 606 }, -- Gold Mini Jouster
    [749] = { [811] = 811 }, -- Golden Civet
    [750] = { [811] = 811 }, -- Golden Civet Kitten
    [1573] = { [948] = 948 }, -- Golden Dawnfeather
    [142] = { [462] = 462 }, -- Golden Dragonhawk Hatchling
    [1712] = { [1017] = 1017 }, -- Golden Eaglet
    [1332] = { [321] = 321, [953] = 953 }, -- Gooey Sha-ling
    [2120] = { [1170] = 1170 }, -- Grasping Manifestation
    [733] = { [810] = 810 }, -- Grassland Hopper
    [443] = { [16] = 16 }, -- Grasslands Cottontail
    [68] = { [41] = 41 }, -- Great Horned Owl
    [50] = { [756] = 756 }, -- Green Wing Macaw
    [464] = { [464] = 464 }, -- Grey Moth
    [834] = { [858] = 858 }, -- Grinder
    [647] = { [700] = 700, [490] = 490 }, -- Grizzly Squirrel
    [1622] = { [775] = 775 }, -- Grotesque
    [539] = { [606] = 606 }, -- Grotto Vole
    [571] = { [806] = 806 }, -- Grove Viper
    [1705] = { [1018] = 1018 }, -- Grumpy
    [1345] = { [951] = 951 }, -- Gu'chi Swarmling
    [282] = { [321] = 321 }, -- Guild Herald
    [283] = { [321] = 321 }, -- Guild Herald
    [281] = { [321] = 321 }, -- Guild Page
    [280] = { [321] = 321 }, -- Guild Page
    [1338] = { [951] = 951 }, -- Gulp Froglet
    [234] = { [496] = 496, [530] = 530 }, -- Gundrak Hatchling
    [1147] = { [696] = 696 }, -- Harbinger of Flame
    [448] = { [4] = 4, [16] = 16, [26] = 26 }, -- Hare
    [1346] = { [951] = 951 }, -- Harmonious Porcupette
    [1157] = { [11] = 11 }, -- Harpy Youngling
    [1544] = { [696] = 696 }, -- Hatespark the Tiny
    [67] = { [41] = 41 }, -- Hawk Owl
    [550] = { [700] = 700 }, -- Highlands Mouse
    [823] = { [700] = 700 }, -- Highlands Skunk
    [645] = { [700] = 700 }, -- Highlands Turkey
    [1762] = { [1024] = 1024 }, -- Hog-Nosed Bat
    [332] = { [321] = 321 }, -- Horde Balloon
    [851] = { [720] = 720 }, -- Horned Lizard
    [483] = { [101] = 101, [945] = 945 }, -- Horny Toad
    [648] = { [24] = 24, [38] = 38, [700] = 700, [496] = 496 }, -- Huge Toad
    [1926] = { [1096] = 1096 }, -- Hungering Claw
    [49] = { [37] = 37, [673] = 673 }, -- Hyacinth Macaw
    [1541] = { [948] = 948 }, -- Hydraling
    [317] = { [795] = 795 }, -- Hyjal Bear Cub
    [1631] = { [775] = 775 }, -- Hyjal Wisp
    [1457] = { [941] = 941 }, -- Icespine Hatchling
    [1532] = { [948] = 948 }, -- Ikky
    [534] = { [490] = 490 }, -- Imperial Eagle Chick
    [628] = { [476] = 476, [23] = 23, [21] = 21 }, -- Infected Fawn
    [627] = { [476] = 476, [23] = 23, [21] = 21 }, -- Infected Squirrel
    [2089] = { [800] = 800 }, -- Infernal Pyreclaw
    [453] = { [24] = 24 }, -- Infested Bear Cub
    [2017] = { [951] = 951 }, -- Infinite Hatchling
    [1387] = { [19] = 19 }, -- Iron Starlette
    [1956] = { [529] = 529 }, -- Ironbound Proto-Whelp
    [1579] = { [941] = 941 }, -- Ironclaw Scuttler
    [442] = { [27] = 27 }, -- Irradiated Roach
    [792] = { [321] = 321 }, -- Jade Crane Chick
    [446] = { [26] = 26 }, -- Jade Oozeling
    [1348] = { [951] = 951 }, -- Jadefire Spirit
    [1333] = { [951] = 951 }, -- Jademist Dancer
    [1202] = { [930] = 930 }, -- Ji-Kun Hatchling
    [699] = { [806] = 806 }, -- Jumping Spider
    [565] = { [806] = 806 }, -- Jungle Darter
    [678] = { [857] = 857 }, -- Jungle Grub
    [1469] = { [949] = 949 }, -- Junglebeak
    [1728] = { [1015] = 1015, [1096] = 1096 }, -- Juvenile Scuttleback
    [1597] = { [948] = 948 }, -- Kaliri Hatchling
    [1583] = { [946] = 946 }, -- Kelp Scuttler
    [438] = { [17] = 17 }, -- King Snake
    [1334] = { [321] = 321, [953] = 953 }, -- Kovok
    [680] = { [810] = 810 }, -- Kuitan Mongoose
    [115] = { [976] = 976, [971] = 971 }, -- Land Shark
    [461] = { [463] = 463 }, -- Larva
    [307] = { [793] = 793 }, -- Lashtail Hatchling
    [429] = { [29] = 29 }, -- Lava Beetle
    [423] = { [29] = 29, [28] = 28 }, -- Lava Crab
    [1435] = { [950] = 950 }, -- Leatherhide Runt
    [545] = { [720] = 720 }, -- Leopard Scorpid
    [702] = { [806] = 806, [949] = 949 }, -- Leopard Tree Frog
    [1234] = { [782] = 782 }, -- Lesser Voidcaller
    [1623] = { [796] = 796 }, -- Leviathan Hatchling
    [1808] = { [1033] = 1033 }, -- Leyline Broodling
    [1226] = { [799] = 799, [1115] = 1115 }, -- Lil' Bad Wolf
    [320] = { [321] = 321 }, -- Lil' Tarecgosa
    [437] = { [35] = 35 }, -- Little Black Ram
    [1243] = { [930] = 930 }, -- Living Fluid
    [1177] = { [930] = 930 }, -- Living Sandling
    [408] = { [37] = 37, [673] = 673 }, -- Lizard Hatchling
    [543] = { [720] = 720 }, -- Locust
    [1159] = { [24] = 24 }, -- Lofty Libram
    [1713] = { [1024] = 1024, [1017] = 1017 }, -- Long-Eared Owl
    [404] = { [201] = 201, [27] = 27, [37] = 37, [673] = 673 }, -- Long-tailed Mole
    [1661] = { [976] = 976, [971] = 971 }, -- Lost Netherpup
    [458] = { [20] = 20 }, -- Lost of Lordaeron
    [341] = { [241] = 241 }, -- Lunar Lantern
    [1922] = { [1033] = 1033 }, -- Lurking Owl Kitten
    [718] = { [857] = 857 }, -- Luyu Moth
    [542] = { [720] = 720 }, -- Mac Frog
    [450] = { [43] = 43, [463] = 463, [24] = 24, [26] = 26, [20] = 20, [491] = 491, [945] = 945 }, -- Maggot
    [132] = { [478] = 478 }, -- Magical Crawdad
    [1955] = { [529] = 529 }, -- Magma Rageling
    [708] = { [857] = 857, [807] = 807 }, -- Malayan Quillrat
    [709] = { [807] = 807 }, -- Malayan Quillrat Pup
    [136] = { [479] = 479 }, -- Mana Wyrmling
    [710] = { [807] = 807 }, -- Marsh Fiddler
    [570] = { [806] = 806 }, -- Masked Tanuki
    [703] = { [806] = 806 }, -- Masked Tanuki Pup
    [1446] = { [950] = 950 }, -- Meadowstomper Calf
    [215] = { [492] = 492 }, -- Mechanopeep
    [722] = { [857] = 857 }, -- Mei Li Sparkler
    [1227] = { [799] = 799, [1115] = 1115 }, -- Menagerie Custodian
    [500] = { [182] = 182 }, -- Minfernal
    [1156] = { [766] = 766 }, -- Mini Mindslayer
    [149] = { [478] = 478 }, -- Miniwing
    [566] = { [806] = 806 }, -- Mirror Strider
    [1744] = { [1024] = 1024, [1017] = 1017 }, -- Mist Fox Kit
    [422] = { [38] = 38 }, -- Moccasin
    [165] = { [781] = 781 }, -- Mojo
    [428] = { [28] = 28 }, -- Molten Hatchling
    [737] = { [810] = 810 }, -- Mongoose
    [739] = { [810] = 810 }, -- Mongoose Pup
    [1276] = { [823] = 823 }, -- Moon Moon
    [1447] = { [473] = 473, [947] = 947 }, -- Moonshell Crab
    [1455] = { [473] = 473, [947] = 947 }, -- Mossbite Skitterer
    [391] = { [36] = 36, [1024] = 1024 }, -- Mountain Cottontail
    [633] = { [81] = 81, [281] = 281, [40] = 40, [490] = 490, [495] = 495 }, -- Mountain Skunk
    [385] = { [141] = 141, [9] = 9, [34] = 34, [39] = 39, [40] = 40, [479] = 479, [490] = 490 }, -- Mouse
    [286] = { [23] = 23 }, -- Mr. Grubbs
    [1441] = { [950] = 950, [948] = 948, [946] = 946, [1024] = 1024 }, -- Mud Jumper
    [1594] = { [949] = 949 }, -- Mudback Calf
    [1776] = { [1024] = 1024 }, -- Mudshell Conch
    [210] = { [492] = 492 }, -- Mulgore Hatchling
    [2002] = { [20] = 20 }, -- Naxxy
    [1954] = { [543] = 543 }, -- Nerubian Swarmer
    [1604] = { [504] = 504, [1014] = 1014 }, -- Nethaera's Light
    [557] = { [121] = 121 }, -- Nether Faerie Dragon
    [186] = { [478] = 478 }, -- Nether Ray Fry
    [638] = { [479] = 479 }, -- Nether Roach
    [1228] = { [799] = 799, [1115] = 1115 }, -- Netherspace Abyssal
    [1524] = { [950] = 950 }, -- Netherspawn, Spawn of Netherspawn
    [1664] = { [945] = 945 }, -- Nightmare Bell
    [1723] = { [1094] = 1094 }, -- Nightmare Whelpling
    [1715] = { [1014] = 1014 }, -- Nightwatch Swooper
    [547] = { [606] = 606 }, -- Nordrassil Wisp
    [1714] = { [1024] = 1024 }, -- Northern Hawk Owl
    [1727] = { [510] = 510, [504] = 504, [1014] = 1014 }, -- Nursery Spider
    [544] = { [720] = 720 }, -- Oasis Moth
    [236] = { [510] = 510 }, -- Obsidian Hatchling
    [530] = { [486] = 486 }, -- Oily Slimeling
    [1729] = { [1015] = 1015, [1096] = 1096 }, -- Olivetail Hare
    [1335] = { [951] = 951 }, -- Ominous Flame
    [43] = { [30] = 30 }, -- Orange Tabby Cat
    [2116] = { [1184] = 1184 }, -- Orphaned Marsuul
    [1125] = { [811] = 811 }, -- Pandaren Air Spirit
    [1126] = { [811] = 811 }, -- Pandaren Earth Spirit
    [1124] = { [811] = 811 }, -- Pandaren Fire Spirit
    [868] = { [811] = 811 }, -- Pandaren Water Spirit
    [301] = { [37] = 37 }, -- Panther Cub
    [2018] = { [951] = 951 }, -- Paradox Spirit
    [1615] = { [949] = 949 }, -- Parched Lizard
    [403] = { [201] = 201, [37] = 37, [38] = 38, [673] = 673 }, -- Parrot
    [198] = { [488] = 488, [491] = 491 }, -- Pengu
    [1663] = { [945] = 945 }, -- Periwinkle Calf
    [175] = { [798] = 798 }, -- Phoenix Hatchling
    [1235] = { [782] = 782 }, -- Phoenix Hawk Hatchling
    [166] = { [4] = 4, [27] = 27 }, -- Pint-Sized Pink Pachyderm
    [1755] = { [1014] = 1014 }, -- Plump Jelly
    [2041] = { [39] = 39 }, -- Pocket Cannon
    [1233] = { [782] = 782 }, -- Pocket Reaver
    [409] = { [37] = 37 }, -- Polly
    [386] = { [9] = 9, [11] = 11, [607] = 607, [362] = 362, [16] = 16, [39] = 39, [477] = 477, [950] = 950 }, -- Prairie Dog
    [1568] = { [976] = 976, [971] = 971 }, -- Puddle Terror
    [328] = { [767] = 767 }, -- Purple Puffer
    [1200] = { [930] = 930 }, -- Pygmy Direhorn
    [2133] = { [1170] = 1170 }, -- Pygmy Marsuul
    [1907] = { [1018] = 1018 }, -- Pygmy Owl
    [513] = { [261] = 261 }, -- Qiraji Guardling
    [378] = { [181] = 181, [42] = 42, [121] = 121, [241] = 241, [606] = 606, [9] = 9, [81] = 81, [27] = 27, [34] = 34, [30] = 30, [462] = 462, [24] = 24, [36] = 36, [480] = 480, [21] = 21, [301] = 301, [20] = 20, [22] = 22, [39] = 39, [40] = 40, [475] = 475, [477] = 477, [510] = 510, [491] = 491, [950] = 950, [1024] = 1024 }, -- Rabbit
    [472] = { [181] = 181, [81] = 81, [281] = 281 }, -- Rabid Nut Varmint 5000
    [743] = { [858] = 858 }, -- Rapana Whelk
    [417] = { [894] = 894, [43] = 43, [181] = 181, [476] = 476, [42] = 42, [101] = 101, [81] = 81, [16] = 16, [27] = 27, [463] = 463, [545] = 545, [611] = 611, [24] = 24, [35] = 35, [684] = 684, [21] = 21, [301] = 301, [38] = 38, [673] = 673, [26] = 26, [20] = 20, [477] = 477, [481] = 481, [478] = 478, [510] = 510, [491] = 491, [544] = 544, [461] = 461, [762] = 762, [763] = 763, [765] = 765, [756] = 756, [710] = 710, [799] = 799, [534] = 534, [521] = 521, [536] = 536, [535] = 535, [951] = 951, [941] = 941, [950] = 950, [948] = 948, [945] = 945, [1024] = 1024, [1115] = 1115 }, -- Rat
    [399] = { [34] = 34 }, -- Rat Snake
    [2080] = { [754] = 754 }, -- Rattlejaw
    [431] = { [161] = 161, [17] = 17, [700] = 700 }, -- Rattlesnake
    [465] = { [476] = 476 }, -- Ravager Hatchling
    [237] = { [201] = 201 }, -- Ravasaur Hatchling
    [238] = { [40] = 40 }, -- Razormaw Hatchling
    [239] = { [37] = 37, [673] = 673 }, -- Razzashi Hatchling
    [2135] = { [1171] = 1171 }, -- Rebellious Imp
    [1042] = { [807] = 807 }, -- Red Cricket
    [143] = { [462] = 462 }, -- Red Dragonhawk Hatchling
    [139] = { [479] = 479 }, -- Red Moth
    [452] = { [381] = 381, [101] = 101, [41] = 41, [24] = 24, [946] = 946 }, -- Red-Tailed Chipmunk
    [392] = { [36] = 36 }, -- Redridge Rat
    [744] = { [858] = 858 }, -- Resilient Roach
    [439] = { [32] = 32 }, -- Restless Shadeling
    [1804] = { [1018] = 1018 }, -- Risen Saber Kitten
    [1453] = { [1014] = 1014 }, -- River Calf
    [424] = { [43] = 43, [181] = 181, [101] = 101, [81] = 81, [61] = 61, [27] = 27, [34] = 34, [545] = 545, [611] = 611, [35] = 35, [37] = 37, [36] = 36, [673] = 673, [20] = 20, [491] = 491, [492] = 492, [605] = 605, [760] = 760, [765] = 765, [521] = 521, [604] = 604 }, -- Roach
    [471] = { [181] = 181, [321] = 321, [281] = 281 }, -- Robo-Chick
    [482] = { [101] = 101, [606] = 606, [261] = 261, [475] = 475 }, -- Rock Viper
    [1749] = { [1017] = 1017 }, -- Rose Taipan
    [1587] = { [473] = 473, [947] = 947, [946] = 946 }, -- Royal Moth
    [1328] = { [951] = 951 }, -- Ruby Droplet
    [460] = { [462] = 462 }, -- Ruby Sapling
    [1957] = { [529] = 529 }, -- Runeforged Servitor
    [271] = { [708] = 708, [709] = 709 }, -- Rustberg Gull
    [496] = { [43] = 43 }, -- Rusty Snail
    [1958] = { [529] = 529 }, -- Sanctum Cub
    [491] = { [161] = 161 }, -- Sand Kitten
    [573] = { [806] = 806 }, -- Sandy Petrel
    [1592] = { [948] = 948 }, -- Sapphire Firefly
    [1692] = { [945] = 945 }, -- Savage Cub
    [717] = { [857] = 857 }, -- Savory Beetle
    [528] = { [475] = 475 }, -- Scalded Basilisk Hatchling
    [512] = { [261] = 261 }, -- Scarab Hatchling
    [414] = { [321] = 321, [261] = 261, [61] = 61, [19] = 19, [29] = 29, [23] = 23, [700] = 700, [475] = 475, [465] = 465, [473] = 473, [947] = 947 }, -- Scorpid
    [416] = { [19] = 19 }, -- Scorpling
    [538] = { [492] = 492 }, -- Scourged Whelpling
    [2042] = { [1021] = 1021 }, -- Scraps
    [1448] = { [976] = 976, [971] = 971 }, -- Sea Calf
    [560] = { [161] = 161, [857] = 857, [976] = 976, [946] = 946 }, -- Sea Gull
    [340] = { [823] = 823 }, -- Sea Pony
    [1539] = { [945] = 945 }, -- Seaborne Spore
    [172] = { [795] = 795 }, -- Searing Scorchling
    [218] = { [492] = 492 }, -- Sen'jin Fetish
    [51] = { [673] = 673, [479] = 479 }, -- Senegal
    [1601] = { [473] = 473, [947] = 947 }, -- Servant of Demidos
    [1754] = { [1014] = 1014 }, -- Sewer-Pipe Jelly
    [1599] = { [946] = 946 }, -- Shadow Sporebat
    [1690] = { [945] = 945 }, -- Shard of Cyrukh
    [1734] = { [1018] = 1018 }, -- Shimmering Aquafly
    [229] = { [492] = 492 }, -- Shimmering Wyrmling
    [493] = { [42] = 42 }, -- Shimmershell Snail
    [388] = { [181] = 181, [700] = 700, [39] = 39, [486] = 486, [491] = 491, [857] = 857, [950] = 950 }, -- Shore Crab
    [629] = { [321] = 321 }, -- Shore Crawler
    [754] = { [806] = 806 }, -- Shrine Fly
    [677] = { [807] = 807 }, -- Shy Bandicoon
    [44] = { [479] = 479 }, -- Siamese Cat
    [511] = { [261] = 261, [720] = 720 }, -- Sidewinder
    [711] = { [807] = 807 }, -- Sifang Otter
    [712] = { [807] = 807 }, -- Sifang Otter Pup
    [741] = { [858] = 858 }, -- Silent Hedgehog
    [494] = { [161] = 161 }, -- Silithid Hatchling
    [2163] = { [261] = 261 }, -- Silithid Mini-Tank
    [568] = { [806] = 806, [949] = 949, [948] = 948, [946] = 946 }, -- Silkbead Snail
    [503] = { [241] = 241, [606] = 606, [201] = 201 }, -- Silky Moth
    [144] = { [462] = 462 }, -- Silver Dragonhawk Hatchling
    [45] = { [30] = 30 }, -- Silver Tabby Cat
    [291] = { [24] = 24 }, -- Singing Sunflower
    [1628] = { [796] = 796 }, -- Sister of Temptation
    [637] = { [475] = 475 }, -- Skittering Cavern Crawler
    [397] = { [894] = 894, [181] = 181, [476] = 476, [34] = 34, [545] = 545, [478] = 478, [491] = 491, [950] = 950 }, -- Skunk
    [1336] = { [951] = 951 }, -- Skunky Alemental
    [1350] = { [951] = 951 }, -- Sky Lantern
    [2134] = { [1170] = 1170 }, -- Skyfin Juvenile
    [1711] = { [1024] = 1024 }, -- Skyhorn Nestling
    [1326] = { [951] = 951 }, -- Skywisp Moth
    [1736] = { [1015] = 1015, [1017] = 1017, [1018] = 1018 }, -- Slithering Brownscale
    [419] = { [381] = 381, [101] = 101, [11] = 11, [607] = 607, [41] = 41, [16] = 16, [30] = 30, [462] = 462, [463] = 463, [35] = 35, [38] = 38, [467] = 467 }, -- Small Frog
    [90] = { [721] = 721 }, -- Smolderweb Hatchling
    [387] = { [141] = 141, [121] = 121, [462] = 462, [463] = 463, [35] = 35, [37] = 37, [21] = 21, [39] = 39, [477] = 477, [478] = 478, [467] = 467, [491] = 491, [493] = 493, [496] = 496, [950] = 950 }, -- Snake
    [1960] = { [529] = 529 }, -- Snaplasher
    [1953] = { [543] = 543 }, -- Snobold Runt
    [440] = { [27] = 27 }, -- Snow Cub
    [640] = { [24] = 24 }, -- Snowshoe Hare
    [72] = { [27] = 27 }, -- Snowshoe Rabbit
    [69] = { [281] = 281 }, -- Snowy Owl
    [713] = { [807] = 807 }, -- Softshell Snapling
    [1183] = { [930] = 930 }, -- Son of Animus
    [1574] = { [1009] = 1009, [1011] = 1011 }, -- Son of Sethe
    [2049] = { [749] = 749 }, -- Son of Skum
    [1966] = { [492] = 492, [604] = 604 }, -- Soulbroken Whelpling
    [1201] = { [810] = 810 }, -- Spawn of G'nathus
    [489] = { [141] = 141 }, -- Spawn of Onyxia
    [1185] = { [929] = 929 }, -- Spectral Porcupette
    [412] = { [181] = 181, [141] = 141, [321] = 321, [81] = 81, [41] = 41, [281] = 281, [19] = 19, [27] = 27, [23] = 23, [30] = 30, [463] = 463, [545] = 545, [611] = 611, [24] = 24, [684] = 684, [38] = 38, [26] = 26, [20] = 20, [473] = 473, [491] = 491, [492] = 492, [495] = 495, [496] = 496, [765] = 765, [796] = 796, [799] = 799, [522] = 522, [534] = 534, [603] = 603, [602] = 602, [521] = 521, [601] = 601, [536] = 536, [523] = 523, [524] = 524, [604] = 604, [535] = 535, [781] = 781, [947] = 947, [1115] = 1115 }, -- Spider
    [1763] = { [1024] = 1024 }, -- Spiketail Beaver
    [433] = { [261] = 261, [17] = 17 }, -- Spiky Lizard
    [1337] = { [951] = 951 }, -- Spineclaw Crab
    [466] = { [4] = 4, [321] = 321 }, -- Spiny Lizard
    [723] = { [857] = 857 }, -- Spiny Terrapin
    [572] = { [806] = 806 }, -- Spirebound Crab
    [463] = { [463] = 463 }, -- Spirit Crab
    [515] = { [467] = 467 }, -- Sporeling Sprout
    [502] = { [201] = 201 }, -- Spotted Bell Frog
    [1739] = { [1018] = 1018 }, -- Spring Strider
    [87] = { [121] = 121 }, -- Sprite Darter Hatchling
    [379] = { [894] = 894, [43] = 43, [181] = 181, [42] = 42, [141] = 141, [121] = 121, [241] = 241, [606] = 606, [41] = 41, [27] = 27, [34] = 34, [30] = 30, [545] = 545, [24] = 24, [35] = 35, [684] = 684, [21] = 21, [301] = 301, [708] = 708, [709] = 709, [700] = 700, [22] = 22, [39] = 39, [40] = 40, [475] = 475, [477] = 477, [478] = 478, [510] = 510, [491] = 491, [493] = 493, [798] = 798, [816] = 816, [781] = 781, [950] = 950, [948] = 948, [1024] = 1024, [1018] = 1018 }, -- Squirrel
    [1969] = { [495] = 495 }, -- Stardust
    [1911] = { [1014] = 1014 }, -- Sting Ray Pup
    [492] = { [161] = 161 }, -- Stinkbug
    [1629] = { [775] = 775 }, -- Stinkrot
    [1146] = { [535] = 535 }, -- Stitched Pup
    [485] = { [101] = 101 }, -- Stone Armadillo
    [1515] = { [946] = 946 }, -- Stonegrinder
    [1721] = { [1017] = 1017 }, -- Stormborne Whelpling
    [1917] = { [1017] = 1017 }, -- Stormstruck Beaver
    [675] = { [30] = 30, [301] = 301 }, -- Stormwind Rat
    [1518] = { [4] = 4, [27] = 27 }, -- Stout Alemental
    [553] = { [640] = 640 }, -- Stowaway Rat
    [401] = { [42] = 42, [27] = 27, [545] = 545, [37] = 37, [38] = 38, [673] = 673, [488] = 488, [605] = 605, [544] = 544, [948] = 948 }, -- Strand Crab
    [211] = { [321] = 321 }, -- Strand Crawler
    [432] = { [161] = 161, [17] = 17, [478] = 478 }, -- Stripe-Tailed Scorpid
    [532] = { [493] = 493 }, -- Stunted Shardhorn
    [1158] = { [121] = 121 }, -- Stunted Yeti
    [1128] = { [857] = 857 }, -- Sumprush Rodent
    [1434] = { [976] = 976, [971] = 971 }, -- Sun Sproutling
    [1632] = { [789] = 789 }, -- Sunblade Micro-Defender
    [1885] = { [1017] = 1017 }, -- Sunborne Val'kyr
    [1570] = { [976] = 976, [971] = 971 }, -- Sunfire Kaliri
    [1178] = { [928] = 928 }, -- Sunreaver Micro-Sentry
    [2088] = { [800] = 800 }, -- Surger
    [1182] = { [928] = 928 }, -- Swamp Croaker
    [402] = { [38] = 38 }, -- Swamp Moth
    [1590] = { [948] = 948, [1024] = 1024 }, -- Swamplighter Firefly
    [497] = { [182] = 182, [473] = 473, [947] = 947 }, -- Tainted Cockroach
    [498] = { [182] = 182 }, -- Tainted Moth
    [499] = { [182] = 182 }, -- Tainted Rat
    [1231] = { [780] = 780 }, -- Tainted Waveling
    [204] = { [492] = 492 }, -- Teldrassil Sproutling
    [567] = { [806] = 806 }, -- Temple Snake
    [1416] = { [946] = 946 }, -- Teroclaw Hatchling
    [650] = { [807] = 807 }, -- Terrible Turnip
    [1735] = { [1018] = 1018 }, -- Terror Larva
    [1456] = { [948] = 948 }, -- Thicket Skitterer
    [1810] = { [1033] = 1033 }, -- Thornclaw Broodling
    [1175] = { [928] = 928 }, -- Thundertail Flapper
    [1230] = { [780] = 780 }, -- Tideskipper
    [1750] = { [1017] = 1017 }, -- Tiny Apparition
    [509] = { [40] = 40 }, -- Tiny Bog Beast
    [287] = { [29] = 29 }, -- Tiny Flamefly
    [652] = { [857] = 857 }, -- Tiny Goldfish
    [389] = { [39] = 39 }, -- Tiny Harvester
    [279] = { [640] = 640 }, -- Tiny Shale Spider
    [167] = { [467] = 467 }, -- Tiny Sporebat
    [445] = { [16] = 16 }, -- Tiny Twister
    [2078] = { [754] = 754 }, -- Tinytron
    [206] = { [492] = 492 }, -- Tirisfal Batling
    [420] = { [43] = 43, [4] = 4, [141] = 141, [182] = 182, [321] = 321, [41] = 41, [462] = 462, [463] = 463, [24] = 24, [21] = 21, [38] = 38, [700] = 700, [40] = 40, [477] = 477, [491] = 491, [950] = 950 }, -- Toad
    [546] = { [720] = 720 }, -- Tol'vir Scarab
    [480] = { [101] = 101, [640] = 640 }, -- Topaz Shale Hatchling
    [2004] = { [504] = 504, [1014] = 1014 }, -- Trashy
    [65] = { [823] = 823 }, -- Tree Frog
    [405] = { [201] = 201, [37] = 37, [673] = 673, [945] = 945 }, -- Tree Python
    [2057] = { [39] = 39 }, -- Tricorne
    [536] = { [486] = 486, [488] = 488 }, -- Tundra Penguin
    [525] = { [491] = 491 }, -- Turkey
    [473] = { [181] = 181 }, -- Turquoise Turtle
    [469] = { [181] = 181, [606] = 606, [640] = 640 }, -- Twilight Beetle
    [2081] = { [758] = 758 }, -- Twilight Clutch-Sister
    [552] = { [700] = 700 }, -- Twilight Fiendling
    [505] = { [61] = 61 }, -- Twilight Iguana
    [470] = { [181] = 181, [700] = 700, [640] = 640 }, -- Twilight Spider
    [1464] = { [941] = 941, [949] = 949 }, -- Twilight Wasp
    [2022] = { [925] = 925 }, -- Tylarr Gronnden
    [1538] = { [473] = 473, [947] = 947 }, -- Umbrafen Spore
    [55] = { [20] = 20, [479] = 479 }, -- Undercity Cockroach
    [454] = { [20] = 20 }, -- Undercity Rat
    [1151] = { [755] = 755 }, -- Untamed Hatchling
    [1921] = { [1033] = 1033 }, -- Untethered Wyrmling
    [2136] = { [1171] = 1171 }, -- Uuna
    [1737] = { [1018] = 1018 }, -- Vale Flitter
    [187] = { [799] = 799, [1115] = 1115 }, -- Vampiric Batling
    [1596] = { [948] = 948 }, -- Veilwatcher Hatchling
    [1344] = { [951] = 951 }, -- Vengeful Porcupette
    [506] = { [81] = 81 }, -- Venomspitter Hatchling
    [1807] = { [1033] = 1033 }, -- Vicious Broodling
    [1591] = { [945] = 945 }, -- Violet Firefly
    [1154] = { [766] = 766 }, -- Viscidus Globule
    [1244] = { [930] = 930 }, -- Viscous Horror
    [2130] = { [1170] = 1170 }, -- Void Shardling
    [2129] = { [1170] = 1170 }, -- Voidstalker Runt
    [1013] = { [857] = 857 }, -- Wanderer's Festival Hatchling
    [517] = { [478] = 478 }, -- Warpstalker Hatchling
    [2128] = { [1170] = 1170 }, -- Warpstalker Runt
    [418] = { [4] = 4, [321] = 321, [37] = 37, [38] = 38, [700] = 700, [40] = 40 }, -- Water Snake
    [535] = { [496] = 496 }, -- Water Waveling
    [1593] = { [473] = 473, [947] = 947, [946] = 946, [945] = 945 }, -- Waterfly
    [1394] = { [976] = 976, [971] = 971 }, -- Weebomination
    [84] = { [39] = 39 }, -- Westfall Chicken
    [410] = { [673] = 673, [708] = 708, [709] = 709, [987] = 987 }, -- Wharf Rat
    [46] = { [301] = 301 }, -- White Kitten
    [141] = { [471] = 471 }, -- White Moth
    [1968] = { [492] = 492, [604] = 604 }, -- Wicked Soul
    [1523] = { [301] = 301, [20] = 20 }, -- Widget the Departed
    [400] = { [34] = 34 }, -- Widow Spiderling
    [819] = { [806] = 806 }, -- Wild Crimson Hatchling
    [818] = { [806] = 806 }, -- Wild Golden Hatchling
    [817] = { [806] = 806 }, -- Wild Jade Hatchling
    [548] = { [700] = 700 }, -- Wildhammer Gryphon Hatchling
    [1959] = { [529] = 529 }, -- Winter Rageling
    [306] = { [281] = 281 }, -- Winterspring Cub
    [220] = { [42] = 42 }, -- Withers
    [153] = { [4] = 4, [27] = 27 }, -- Wolpertinger
    [64] = { [823] = 823 }, -- Wood Frog
    [1463] = { [949] = 949 }, -- Wood Wasp
    [89] = { [721] = 721 }, -- Worg Pup
    [1634] = { [789] = 789 }, -- Wretched Servant
    [1266] = { [951] = 951 }, -- Xu-Fu, Cub of Xuen
    [740] = { [858] = 858, [810] = 810 }, -- Yakrat
    [140] = { [471] = 471 }, -- Yellow Moth
    [752] = { [811] = 811 }, -- Yellow-Bellied Bullfrog
    [549] = { [700] = 700 }, -- Yellow-Bellied Marmot
    [1912] = { [1014] = 1014 }, -- Young Mutant Warturtle
    [1304] = { [951] = 951 }, -- Yu'la, Broodling of Yu'lon
    [1211] = { [929] = 929 }, -- Zandalari Anklerender
    [1212] = { [929] = 929 }, -- Zandalari Footslasher
    [1180] = { [929] = 929 }, -- Zandalari Kneebiter
    [1213] = { [929] = 929 }, -- Zandalari Toenibbler
    [1582] = { [473] = 473, [947] = 947 }, -- Zangar Crawler
    [1536] = { [945] = 945 }, -- Zangar Spore
    [1305] = { [951] = 951 }, -- Zao, Calfling of Niuzao
    [2084] = { [773] = 773 }, -- Zephyrian Prince
    [1428] = { [473] = 473, [947] = 947 }, -- Zomstrok
}

Data.ZoneCompanions = {
    [522] = { [412] = 412 }, -- Ahn'kahet: The Old Kingdom
    [894] = { [397] = 397, [417] = 417, [379] = 379 }, -- Ammen Vale MoP
    [1171] = { [2122] = 2122, [2126] = 2126, [2115] = 2115, [2135] = 2135, [2136] = 2136 }, -- Antoran Wastes
    [461] = { [417] = 417 }, -- Arathi Basin
    [16] = { [445] = 445, [448] = 448, [419] = 419, [459] = 459, [417] = 417, [386] = 386, [443] = 443 }, -- Arathi Highlands
    [1184] = { [2116] = 2116 }, -- Argus
    [43] = { [450] = 450, [495] = 495, [496] = 496, [478] = 478, [420] = 420, [417] = 417, [424] = 424, [379] = 379 }, -- Ashenvale
    [181] = { [388] = 388, [397] = 397, [469] = 469, [470] = 470, [471] = 471, [472] = 472, [473] = 473, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [379] = 379 }, -- Azshara
    [1015] = { [569] = 569, [1728] = 1728, [1729] = 1729, [1914] = 1914, [1708] = 1708, [1710] = 1710, [1716] = 1716, [1720] = 1720, [1731] = 1731, [1736] = 1736, [1773] = 1773, [1774] = 1774, [1931] = 1931, [1709] = 1709, [2077] = 2077 }, -- Azsuna
    [464] = { [464] = 464 }, -- Azuremyst Isle
    [17] = { [56] = 56, [398] = 398, [406] = 406, [430] = 430, [431] = 431, [432] = 432, [433] = 433, [438] = 438 }, -- Badlands
    [796] = { [1625] = 1625, [1628] = 1628, [1623] = 1623, [1626] = 1626, [1627] = 1627, [1624] = 1624, [412] = 412 }, -- Black Temple
    [721] = { [89] = 89, [90] = 90 }, -- Blackrock Spire
    [754] = { [2078] = 2078, [2080] = 2080, [2079] = 2079 }, -- Blackwing Descent
    [755] = { [1151] = 1151, [1152] = 1152, [1153] = 1153 }, -- Blackwing Lair
    [475] = { [449] = 449, [528] = 528, [414] = 414, [482] = 482, [1164] = 1164, [637] = 637, [378] = 378, [379] = 379 }, -- Blade's Edge Mountains
    [19] = { [635] = 635, [1563] = 1563, [1387] = 1387, [414] = 414, [415] = 415, [412] = 412, [416] = 416 }, -- Blasted Lands
    [476] = { [397] = 397, [465] = 465, [417] = 417, [627] = 627, [628] = 628 }, -- Bloodmyst Isle
    [486] = { [639] = 639, [641] = 641, [388] = 388, [530] = 530, [536] = 536 }, -- Borean Tundra
    [925] = { [1142] = 1142, [2022] = 2022 }, -- Brawl'gar Arena
    [1021] = { [2042] = 2042 }, -- Broken Shore
    [29] = { [56] = 56, [393] = 393, [414] = 414, [415] = 415, [423] = 423, [425] = 425, [429] = 429, [287] = 287 }, -- Burning Steppes
    [510] = { [190] = 190, [224] = 224, [236] = 236, [417] = 417, [378] = 378, [379] = 379, [1727] = 1727 }, -- Crystalsong Forest
    [1014] = { [193] = 193, [74] = 74, [1604] = 1604, [1429] = 1429, [1453] = 1453, [1715] = 1715, [1727] = 1727, [1755] = 1755, [1760] = 1760, [1778] = 1778, [1805] = 1805, [1912] = 1912, [1915] = 1915, [1754] = 1754, [1911] = 1911, [2004] = 2004 }, -- Dalaran
    [504] = { [193] = 193, [74] = 74, [1604] = 1604, [1727] = 1727, [2004] = 2004 }, -- Dalaran
    [823] = { [64] = 64, [65] = 65, [1062] = 1062, [1276] = 1276, [330] = 330, [335] = 335, [336] = 336, [338] = 338, [339] = 339, [340] = 340, [343] = 343, [848] = 848, [1068] = 1068, [1061] = 1061, [1665] = 1665, [1666] = 1666 }, -- Darkmoon Island
    [42] = { [630] = 630, [508] = 508, [401] = 401, [417] = 417, [493] = 493, [220] = 220, [378] = 378, [379] = 379 }, -- Darkshore
    [381] = { [452] = 452, [419] = 419, [478] = 478, [479] = 479 }, -- Darnassus
    [32] = { [1160] = 1160, [439] = 439 }, -- Deadwind Pass
    [640] = { [555] = 555, [469] = 469, [554] = 554, [470] = 470, [556] = 556, [559] = 559, [480] = 480, [837] = 837, [838] = 838, [293] = 293, [553] = 553, [279] = 279, [756] = 756 }, -- Deepholm
    [101] = { [452] = 452, [419] = 419, [478] = 478, [479] = 479, [480] = 480, [482] = 482, [483] = 483, [838] = 838, [484] = 484, [417] = 417, [485] = 485, [424] = 424 }, -- Desolace
    [824] = { [2090] = 2090 }, -- Dragon Soul
    [488] = { [641] = 641, [536] = 536, [401] = 401, [198] = 198, [537] = 537 }, -- Dragonblight
    [534] = { [417] = 417, [412] = 412 }, -- Drak'Tharon Keep
    [858] = { [834] = 834, [742] = 742, [836] = 836, [740] = 740, [741] = 741, [743] = 743, [744] = 744, [745] = 745, [746] = 746, [732] = 732 }, -- Dread Wastes MoP
    [27] = { [1518] = 1518, [635] = 635, [166] = 166, [401] = 401, [404] = 404, [72] = 72, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [440] = 440, [441] = 441, [442] = 442, [379] = 379, [153] = 153 }, -- Dun Morogh
    [4] = { [1518] = 1518, [635] = 635, [448] = 448, [166] = 166, [466] = 466, [467] = 467, [468] = 468, [418] = 418, [420] = 420, [1237] = 1237, [153] = 153 }, -- Durotar
    [34] = { [385] = 385, [646] = 646, [396] = 396, [397] = 397, [398] = 398, [399] = 399, [400] = 400, [424] = 424, [378] = 378, [379] = 379 }, -- Duskwood
    [141] = { [56] = 56, [385] = 385, [387] = 387, [646] = 646, [398] = 398, [232] = 232, [420] = 420, [412] = 412, [489] = 489, [379] = 379 }, -- Dustwallow Marsh
    [23] = { [393] = 393, [457] = 457, [398] = 398, [286] = 286, [406] = 406, [414] = 414, [412] = 412, [626] = 626, [627] = 627, [628] = 628 }, -- Eastern Plaguelands
    [30] = { [40] = 40, [447] = 447, [646] = 646, [41] = 41, [419] = 419, [459] = 459, [43] = 43, [45] = 45, [412] = 412, [675] = 675, [374] = 374, [378] = 378, [379] = 379 }, -- Elwynn Forest
    [462] = { [387] = 387, [419] = 419, [459] = 459, [460] = 460, [142] = 142, [143] = 143, [144] = 144, [420] = 420, [378] = 378 }, -- Eversong Woods
    [1096] = { [1728] = 1728, [1729] = 1729, [1914] = 1914, [1926] = 1926 }, -- Eye of Azshara
    [182] = { [406] = 406, [420] = 420, [497] = 497, [498] = 498, [499] = 499, [500] = 500 }, -- Felwood
    [121] = { [387] = 387, [59] = 59, [557] = 557, [87] = 87, [1158] = 1158, [378] = 378, [379] = 379 }, -- Feralas
    [800] = { [2086] = 2086, [2087] = 2087, [2089] = 2089, [2088] = 2088 }, -- Firelands
    [941] = { [1578] = 1578, [1579] = 1579, [541] = 541, [417] = 417, [1427] = 1427, [1457] = 1457, [1464] = 1464, [1471] = 1471 }, -- Frostfire Ridge
    [976] = { [560] = 560, [1396] = 1396, [1688] = 1688, [1588] = 1588, [1598] = 1598, [1577] = 1577, [1661] = 1661, [1385] = 1385, [1545] = 1545, [1568] = 1568, [1442] = 1442, [1434] = 1434, [1570] = 1570, [1394] = 1394, [115] = 115, [1448] = 1448 }, -- Frostwall
    [463] = { [450] = 450, [387] = 387, [419] = 419, [461] = 461, [463] = 463, [420] = 420, [417] = 417, [412] = 412 }, -- Ghostlands
    [545] = { [397] = 397, [401] = 401, [417] = 417, [412] = 412, [424] = 424, [379] = 379 }, -- Gilneas
    [611] = { [417] = 417, [412] = 412, [424] = 424 }, -- Gilneas City
    [691] = { [1162] = 1162 }, -- Gnomeregan
    [949] = { [1564] = 1564, [449] = 449, [1537] = 1537, [393] = 393, [1594] = 1594, [1615] = 1615, [568] = 568, [702] = 702, [430] = 430, [1463] = 1463, [1465] = 1465, [1464] = 1464, [1469] = 1469, [1470] = 1470 }, -- Gorgrond
    [993] = { [635] = 635 }, -- Grimrail Depot
    [490] = { [385] = 385, [647] = 647, [534] = 534, [633] = 633 }, -- Grizzly Hills
    [530] = { [234] = 234 }, -- Gundrak
    [603] = { [412] = 412 }, -- Halls of Reflection
    [1022] = { [1753] = 1753 }, -- Helheim
    [1026] = { [1672] = 1672 }, -- Hellfire Citadel
    [465] = { [635] = 635, [414] = 414, [514] = 514 }, -- Hellfire Peninsula
    [1024] = { [391] = 391, [407] = 407, [569] = 569, [417] = 417, [487] = 487, [1441] = 1441, [1590] = 1590, [378] = 378, [379] = 379, [1711] = 1711, [1713] = 1713, [1726] = 1726, [1731] = 1731, [1743] = 1743, [1744] = 1744, [1752] = 1752, [1761] = 1761, [1762] = 1762, [1763] = 1763, [1775] = 1775, [1776] = 1776, [1884] = 1884, [1714] = 1714 }, -- Highmountain
    [24] = { [640] = 640, [450] = 450, [646] = 646, [452] = 452, [648] = 648, [453] = 453, [42] = 42, [291] = 291, [1159] = 1159, [420] = 420, [417] = 417, [412] = 412, [378] = 378, [379] = 379 }, -- Hillsbrad Foothills
    [491] = { [450] = 450, [644] = 644, [387] = 387, [646] = 646, [388] = 388, [523] = 523, [525] = 525, [529] = 529, [397] = 397, [198] = 198, [420] = 420, [417] = 417, [412] = 412, [424] = 424, [378] = 378, [379] = 379 }, -- Howling Fjord
    [775] = { [1629] = 1629, [1622] = 1622, [1631] = 1631 }, -- Hyjal Summit
    [492] = { [393] = 393, [229] = 229, [538] = 538, [204] = 204, [205] = 205, [206] = 206, [207] = 207, [212] = 212, [209] = 209, [213] = 213, [214] = 214, [412] = 412, [215] = 215, [216] = 216, [218] = 218, [424] = 424, [210] = 210, [1963] = 1963, [1964] = 1964, [1965] = 1965, [1966] = 1966, [1967] = 1967, [1968] = 1968 }, -- Icecrown
    [604] = { [412] = 412, [424] = 424, [1963] = 1963, [1964] = 1964, [1965] = 1965, [1966] = 1966, [1967] = 1967, [1968] = 1968 }, -- Icecrown Citadel
    [987] = { [393] = 393, [410] = 410 }, -- Iron Docks
    [929] = { [1213] = 1213, [1211] = 1211, [1185] = 1185, [1180] = 1180, [1212] = 1212, [1205] = 1205 }, -- Isle of Giants
    [928] = { [1181] = 1181, [1175] = 1175, [1179] = 1179, [1178] = 1178, [1182] = 1182 }, -- Isle of Thunder
    [799] = { [187] = 187, [417] = 417, [412] = 412, [1227] = 1227, [1226] = 1226, [1228] = 1228, [1229] = 1229 }, -- Karazhan
    [605] = { [401] = 401, [424] = 424 }, -- Kezan
    [857] = { [388] = 388, [1013] = 1013, [1128] = 1128, [678] = 678, [560] = 560, [717] = 717, [708] = 708, [714] = 714, [718] = 718, [722] = 722, [723] = 723, [716] = 716, [652] = 652 }, -- Krasarang Wilds MoP
    [1135] = { [2124] = 2124, [2123] = 2123, [2127] = 2127 }, -- Krokuun
    [35] = { [387] = 387, [419] = 419, [417] = 417, [437] = 437, [424] = 424, [379] = 379 }, -- Loch Modan
    [971] = { [1396] = 1396, [1688] = 1688, [1588] = 1588, [1598] = 1598, [1577] = 1577, [1661] = 1661, [1385] = 1385, [1545] = 1545, [1568] = 1568, [1442] = 1442, [1434] = 1434, [1570] = 1570, [1394] = 1394, [115] = 115, [1448] = 1448 }, -- Lunarfall
    [1170] = { [2120] = 2120, [2128] = 2128, [2130] = 2130, [2132] = 2132, [2129] = 2129, [2134] = 2134, [2133] = 2133, [2131] = 2131 }, -- Mac'Aree
    [798] = { [175] = 175, [379] = 379 }, -- Magisters' Terrace
    [696] = { [1544] = 1544, [1147] = 1147, [1149] = 1149, [1150] = 1150 }, -- Molten Core
    [795] = { [317] = 317, [172] = 172, [318] = 318 }, -- Molten Front
    [241] = { [341] = 341, [342] = 342, [478] = 478, [503] = 503, [378] = 378, [379] = 379 }, -- Moonglade
    [606] = { [632] = 632, [259] = 259, [539] = 539, [540] = 540, [541] = 541, [547] = 547, [469] = 469, [478] = 478, [415] = 415, [479] = 479, [482] = 482, [487] = 487, [503] = 503, [378] = 378, [626] = 626, [755] = 755, [260] = 260, [379] = 379 }, -- Mount Hyjal
    [9] = { [385] = 385, [70] = 70, [477] = 477, [386] = 386, [378] = 378 }, -- Mulgore
    [477] = { [635] = 635, [387] = 387, [518] = 518, [420] = 420, [417] = 417, [386] = 386, [378] = 378, [379] = 379 }, -- Nagrand
    [950] = { [635] = 635, [1524] = 1524, [387] = 387, [388] = 388, [397] = 397, [420] = 420, [417] = 417, [1435] = 1435, [1441] = 1441, [1446] = 1446, [386] = 386, [378] = 378, [379] = 379, [1764] = 1764, [1765] = 1765, [1766] = 1766 }, -- Nagrand
    [535] = { [1146] = 1146, [1143] = 1143, [1144] = 1144, [417] = 417, [412] = 412 }, -- Naxxramas
    [479] = { [638] = 638, [385] = 385, [521] = 521, [459] = 459, [136] = 136, [137] = 137, [51] = 51, [44] = 44, [145] = 145, [139] = 139, [55] = 55, [78] = 78 }, -- Netherstorm
    [11] = { [631] = 631, [635] = 635, [419] = 419, [474] = 474, [1157] = 1157, [386] = 386 }, -- Northern Barrens
    [37] = { [635] = 635, [387] = 387, [49] = 49, [401] = 401, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [407] = 407, [408] = 408, [409] = 409, [239] = 239, [418] = 418, [421] = 421, [301] = 301, [424] = 424 }, -- Northern Stranglethorn
    [321] = { [272] = 272, [1449] = 1449, [332] = 332, [792] = 792, [1331] = 1331, [1332] = 1332, [466] = 466, [467] = 467, [270] = 270, [471] = 471, [281] = 281, [282] = 282, [283] = 283, [1334] = 1334, [280] = 280, [414] = 414, [418] = 418, [420] = 420, [211] = 211, [75] = 75, [1322] = 1322, [412] = 412, [320] = 320, [78] = 78, [77] = 77, [629] = 629, [1890] = 1890 }, -- Orgrimmar
    [602] = { [412] = 412 }, -- Pit of Saron
    [760] = { [424] = 424 }, -- Razorfen Downs
    [36] = { [646] = 646, [391] = 391, [392] = 392, [395] = 395, [424] = 424, [378] = 378 }, -- Redridge Mountains
    [1115] = { [187] = 187, [417] = 417, [412] = 412, [1227] = 1227, [1226] = 1226, [1228] = 1228, [1229] = 1229 }, -- Return to Karazhan
    [684] = { [417] = 417, [412] = 412, [379] = 379 }, -- Ruins of Gilneas
    [762] = { [417] = 417 }, -- Scarlet Monastery
    [763] = { [417] = 417 }, -- Scholomance
    [28] = { [415] = 415, [423] = 423, [427] = 427, [428] = 428 }, -- Searing Gorge
    [780] = { [1230] = 1230, [1231] = 1231, [1232] = 1232 }, -- Serpentshrine Cavern
    [473] = { [519] = 519, [1593] = 1593, [407] = 407, [1601] = 1601, [414] = 414, [1428] = 1428, [425] = 425, [1447] = 1447, [1582] = 1582, [412] = 412, [1455] = 1455, [1587] = 1587, [1538] = 1538, [497] = 497 }, -- Shadowmoon Valley
    [947] = { [519] = 519, [1593] = 1593, [407] = 407, [1601] = 1601, [414] = 414, [1428] = 1428, [425] = 425, [1447] = 1447, [1582] = 1582, [412] = 412, [1455] = 1455, [1587] = 1587, [1538] = 1538, [497] = 497 }, -- Shadowmoon Valley
    [481] = { [417] = 417 }, -- Shattrath City
    [493] = { [387] = 387, [649] = 649, [1167] = 1167, [532] = 532, [379] = 379 }, -- Sholazar Basin
    [953] = { [1331] = 1331, [1332] = 1332, [1334] = 1334, [1322] = 1322 }, -- Siege of Orgrimmar
    [261] = { [511] = 511, [512] = 512, [513] = 513, [406] = 406, [414] = 414, [482] = 482, [484] = 484, [433] = 433, [2163] = 2163 }, -- Silithus
    [480] = { [459] = 459, [378] = 378 }, -- Silvermoon City
    [21] = { [387] = 387, [455] = 455, [420] = 420, [417] = 417, [378] = 378, [627] = 627, [628] = 628, [379] = 379 }, -- Silverpine Forest
    [607] = { [631] = 631, [635] = 635, [419] = 419, [475] = 475, [386] = 386 }, -- Southern Barrens
    [948] = { [635] = 635, [1532] = 1532, [1540] = 1540, [1541] = 1541, [1596] = 1596, [1573] = 1573, [401] = 401, [568] = 568, [1597] = 1597, [417] = 417, [1441] = 1441, [1456] = 1456, [1462] = 1462, [1590] = 1590, [379] = 379, [1592] = 1592 }, -- Spires of Arak
    [81] = { [472] = 472, [417] = 417, [487] = 487, [488] = 488, [412] = 412, [424] = 424, [378] = 378, [633] = 633, [506] = 506 }, -- Stonetalon Mountains
    [1017] = { [1708] = 1708, [1712] = 1712, [1713] = 1713, [1721] = 1721, [1736] = 1736, [1743] = 1743, [1744] = 1744, [1749] = 1749, [1917] = 1917, [1750] = 1750, [1885] = 1885 }, -- Stormheim
    [1009] = { [1574] = 1574 }, -- Stormshield
    [301] = { [1523] = 1523, [319] = 319, [417] = 417, [1521] = 1521, [46] = 46, [675] = 675, [378] = 378, [379] = 379, [1890] = 1890 }, -- Stormwind City
    [765] = { [417] = 417, [412] = 412, [424] = 424 }, -- Stratholme
    [789] = { [1634] = 1634, [1632] = 1632, [1633] = 1633 }, -- Sunwell Plateau
    [1033] = { [425] = 425, [1914] = 1914, [1717] = 1717, [1719] = 1719, [1807] = 1807, [1808] = 1808, [1809] = 1809, [1921] = 1921, [1922] = 1922, [1934] = 1934, [1810] = 1810 }, -- Suramar
    [38] = { [648] = 648, [419] = 419, [401] = 401, [402] = 402, [403] = 403, [418] = 418, [420] = 420, [417] = 417, [422] = 422, [412] = 412 }, -- Swamp of Sorrows
    [946] = { [1515] = 1515, [452] = 452, [1572] = 1572, [1583] = 1583, [1595] = 1595, [1593] = 1593, [560] = 560, [1599] = 1599, [568] = 568, [1416] = 1416, [1576] = 1576, [1441] = 1441, [427] = 427, [1587] = 1587, [1589] = 1589 }, -- Talador
    [945] = { [450] = 450, [519] = 519, [1593] = 1593, [405] = 405, [483] = 483, [417] = 417, [1468] = 1468, [1536] = 1536, [1539] = 1539, [1586] = 1586, [1591] = 1591, [1660] = 1660, [1663] = 1663, [1664] = 1664, [1692] = 1692, [1693] = 1693, [1690] = 1690, [1581] = 1581 }, -- Tanaan Jungle
    [161] = { [560] = 560, [484] = 484, [491] = 491, [492] = 492, [430] = 430, [494] = 494, [431] = 431, [432] = 432 }, -- Tanaris
    [41] = { [507] = 507, [447] = 447, [452] = 452, [68] = 68, [419] = 419, [67] = 67, [478] = 478, [479] = 479, [420] = 420, [412] = 412, [379] = 379 }, -- Teldrassil
    [766] = { [1154] = 1154, [1155] = 1155, [1156] = 1156 }, -- Temple of Ahn'Qiraj
    [478] = { [387] = 387, [646] = 646, [132] = 132, [397] = 397, [417] = 417, [149] = 149, [517] = 517, [432] = 432, [186] = 186, [379] = 379 }, -- Terokkar Forest
    [758] = { [2082] = 2082, [2081] = 2081, [2083] = 2083 }, -- The Bastion of Twilight
    [673] = { [49] = 49, [401] = 401, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [51] = 51, [407] = 407, [408] = 408, [410] = 410, [411] = 411, [239] = 239, [417] = 417, [421] = 421, [424] = 424, [47] = 47 }, -- The Cape of Stranglethorn
    [521] = { [417] = 417, [412] = 412, [424] = 424 }, -- The Culling of Stratholme
    [756] = { [50] = 50, [417] = 417 }, -- The Deadmines
    [1094] = { [1722] = 1722, [1723] = 1723 }, -- The Emerald Nightmare
    [471] = { [141] = 141, [140] = 140, [138] = 138 }, -- The Exodar
    [782] = { [1233] = 1233, [1234] = 1234, [1235] = 1235 }, -- The Eye
    [601] = { [412] = 412 }, -- The Forge of Souls
    [26] = { [446] = 446, [448] = 448, [449] = 449, [450] = 450, [393] = 393, [417] = 417, [412] = 412 }, -- The Hinterlands
    [806] = { [380] = 380, [817] = 817, [818] = 818, [819] = 819, [562] = 562, [564] = 564, [567] = 567, [566] = 566, [568] = 568, [570] = 570, [569] = 569, [571] = 571, [699] = 699, [572] = 572, [702] = 702, [703] = 703, [565] = 565, [847] = 847, [573] = 573, [754] = 754 }, -- The Jade Forest MoP
    [544] = { [401] = 401, [417] = 417 }, -- The Lost Isles
    [710] = { [417] = 417 }, -- The Shattered Halls
    [495] = { [641] = 641, [558] = 558, [412] = 412, [633] = 633, [1969] = 1969 }, -- The Storm Peaks
    [536] = { [417] = 417, [412] = 412 }, -- The Violet Hold
    [808] = { [2047] = 2047 }, -- The Wandering Isle MoP
    [61] = { [398] = 398, [414] = 414, [52] = 52, [424] = 424, [505] = 505 }, -- Thousand Needles
    [773] = { [2084] = 2084, [2085] = 2085 }, -- Throne of the Four Winds
    [767] = { [328] = 328 }, -- Throne of the Tides
    [930] = { [1183] = 1183, [1200] = 1200, [1177] = 1177, [1243] = 1243, [1202] = 1202, [1244] = 1244 }, -- Throne of Thunder
    [362] = { [386] = 386 }, -- Thunder Bluff
    [951] = { [1304] = 1304, [1323] = 1323, [1324] = 1324, [1326] = 1326, [1328] = 1328, [1337] = 1337, [1333] = 1333, [1338] = 1338, [1343] = 1343, [1344] = 1344, [1346] = 1346, [1350] = 1350, [1336] = 1336, [1335] = 1335, [1348] = 1348, [1345] = 1345, [417] = 417, [1325] = 1325, [1330] = 1330, [1329] = 1329, [1303] = 1303, [1321] = 1321, [1305] = 1305, [1266] = 1266, [2017] = 2017, [2018] = 2018 }, -- Timeless Isle
    [20] = { [1523] = 1523, [319] = 319, [450] = 450, [646] = 646, [454] = 454, [458] = 458, [417] = 417, [1521] = 1521, [412] = 412, [424] = 424, [55] = 55, [378] = 378, [626] = 626, [2002] = 2002 }, -- Tirisfal Glades
    [708] = { [271] = 271, [278] = 278, [410] = 410, [379] = 379 }, -- Tol Barad
    [709] = { [271] = 271, [278] = 278, [410] = 410, [379] = 379 }, -- Tol Barad Peninsula
    [810] = { [1201] = 1201, [680] = 680, [733] = 733, [737] = 737, [739] = 739, [740] = 740, [732] = 732 }, -- Townlong Steppes MoP
    [543] = { [1952] = 1952, [1953] = 1953, [1954] = 1954 }, -- Trial of the Crusader
    [700] = { [645] = 645, [647] = 647, [388] = 388, [648] = 648, [393] = 393, [398] = 398, [548] = 548, [549] = 549, [550] = 550, [552] = 552, [470] = 470, [823] = 823, [414] = 414, [418] = 418, [420] = 420, [293] = 293, [431] = 431, [379] = 379 }, -- Twilight Highlands
    [529] = { [1955] = 1955, [1956] = 1956, [1957] = 1957, [1958] = 1958, [1959] = 1959, [1960] = 1960, [1961] = 1961, [1962] = 1962 }, -- Ulduar
    [720] = { [631] = 631, [511] = 511, [542] = 542, [544] = 544, [545] = 545, [467] = 467, [484] = 484, [293] = 293, [851] = 851, [546] = 546, [543] = 543 }, -- Uldum
    [201] = { [631] = 631, [632] = 632, [393] = 393, [403] = 403, [404] = 404, [405] = 405, [406] = 406, [237] = 237, [415] = 415, [502] = 502, [503] = 503, [504] = 504 }, -- Un'Goro Crater
    [523] = { [412] = 412 }, -- Utgarde Keep
    [524] = { [412] = 412 }, -- Utgarde Pinnacle
    [1018] = { [379] = 379, [1705] = 1705, [1706] = 1706, [1734] = 1734, [1736] = 1736, [1737] = 1737, [1738] = 1738, [1739] = 1739, [1802] = 1802, [1804] = 1804, [1907] = 1907, [1913] = 1913, [1927] = 1927, [1735] = 1735 }, -- Val'sharah
    [811] = { [383] = 383, [748] = 748, [1124] = 1124, [1126] = 1126, [1125] = 1125, [747] = 747, [868] = 868, [749] = 749, [750] = 750, [751] = 751, [752] = 752 }, -- Vale of Eternal Blossoms MoP
    [807] = { [1042] = 1042, [650] = 650, [677] = 677, [709] = 709, [706] = 706, [707] = 707, [708] = 708, [710] = 710, [711] = 711, [712] = 712, [713] = 713 }, -- Valley of the Four Winds MoP
    [749] = { [233] = 233, [2049] = 2049 }, -- Wailing Caverns
    [1011] = { [1574] = 1574 }, -- Warspear
    [816] = { [379] = 379 }, -- Well of Eternity
    [22] = { [456] = 456, [398] = 398, [378] = 378, [379] = 379 }, -- Western Plaguelands
    [39] = { [385] = 385, [387] = 387, [646] = 646, [388] = 388, [389] = 389, [84] = 84, [386] = 386, [378] = 378, [379] = 379, [2041] = 2041, [2058] = 2058, [2057] = 2057 }, -- Westfall
    [40] = { [509] = 509, [56] = 56, [385] = 385, [646] = 646, [393] = 393, [398] = 398, [58] = 58, [418] = 418, [420] = 420, [378] = 378, [633] = 633, [238] = 238, [379] = 379 }, -- Wetlands
    [281] = { [634] = 634, [57] = 57, [69] = 69, [471] = 471, [472] = 472, [487] = 487, [1163] = 1163, [412] = 412, [306] = 306, [633] = 633, [441] = 441 }, -- Winterspring
    [467] = { [515] = 515, [387] = 387, [419] = 419, [167] = 167, [146] = 146 }, -- Zangarmarsh
    [781] = { [165] = 165, [412] = 412, [379] = 379 }, -- Zul'Aman
    [496] = { [641] = 641, [387] = 387, [648] = 648, [234] = 234, [412] = 412, [535] = 535 }, -- Zul'Drak
    [793] = { [307] = 307 }, -- Zul'Gurub
}

