-- auto generated by collectmedb on 2016-08-02 12:09:39

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

if UnitFactionGroup("player") == "Horde" then
    Data.FollowersZone = {
        [209] = { [950] = 950 }, -- Abu'gar
        [208] = { [946] = 946 }, -- Ahm
        [225] = { [988] = 988 }, -- Aknor Steelbringer
        [195] = { [976] = 976 }, -- Alexi Barov
        [474] = { [1026] = 1026 }, -- Ariok
        [204] = { [948] = 948 }, -- Benjamin Gibb
        [189] = { [949] = 949 }, -- Blook
        [177] = { [964] = 964 }, -- Croman
        [32] = { [941] = 941 }, -- Dagg
        [462] = { [1009] = 1009, [1011] = 1011 }, -- Dawnseeker Rukaryx
        [207] = { [946] = 946 }, -- Defender Illona / Aeda Brightdawn
        [581] = { [945] = 945 }, -- Dowser Bigspark / Dowser Goodwell
        [467] = { [1009] = 1009, [1011] = 1011 }, -- Fen Tao
        [466] = { [946] = 946 }, -- Garona Halforcen
        [211] = { [949] = 949 }, -- Glirin / Penny Clobberbottom
        [170] = { [950] = 950 }, -- Goldmane the Skinner
        [186] = { [941] = 941 }, -- Greatmother Geyah
        [183] = { [941] = 941 }, -- Gronnstalker Rokash
        [465] = { [976] = 976, [971] = 971 }, -- Harrison Jones
        [453] = { [948] = 948 }, -- Hulda Shadowblade / Dark Ranger Velonara
        [190] = { [941] = 941, [949] = 949, [950] = 950, [946] = 946 }, -- Image of Archmage Vargoth
        [153] = { [941] = 941 }, -- Ka'la
        [184] = { [941] = 941 }, -- Kal'gor the Honorable
        [459] = { [1011] = 1011 }, -- Karg Bloodfury
        [192] = { [948] = 948 }, -- Kimzee Pinchwhistle
        [157] = { [950] = 950 }, -- Lantresor of the Blade
        [178] = { [995] = 995 }, -- Leeroy Jenkins
        [219] = { [948] = 948 }, -- Leorajh
        [185] = { [941] = 941 }, -- Lokra
        [154] = { [946] = 946 }, -- Magister Serena / Magister Krelas
        [203] = { [321] = 321, [301] = 301 }, -- Meatball
        [155] = { [946] = 946 }, -- Miall / Morketh Bladehowl
        [455] = { [995] = 995 }, -- Millhouse Manastorm
        [182] = { [941] = 941 }, -- Mulverick
        [202] = { [976] = 976, [971] = 971 }, -- Nat Pagle
        [34] = { [941] = 941 }, -- Olin Umberhide
        [468] = { [945] = 945 }, -- Oronok Torn-heart
        [580] = { [945] = 945 }, -- Pallas
        [194] = { [976] = 976, [971] = 971 }, -- Phylarch the Evergreen
        [176] = { [949] = 949 }, -- Pitfighter Vaandaam / Bruto
        [171] = { [946] = 946 }, -- Pleasure-Bot 8000
        [460] = { [1009] = 1009, [1011] = 1011 }, -- Professor Felblast
        [212] = { [949] = 949 }, -- Rangari Erdanii / Spirit of Bony Xuk
        [159] = { [949] = 949 }, -- Rangari Kaalya / Kaz the Shrieker
        [180] = { [941] = 941 }, -- Shadow Hunter Rala
        [582] = { [945] = 945 }, -- Solar Priest Vayx
        [205] = { [946] = 946 }, -- Soulbinder Tuulani
        [224] = { [948] = 948 }, -- Talon Guard Kurekk
        [218] = { [948] = 948 }, -- Talonpriest Ishaal
        [217] = { [976] = 976, [949] = 949, [971] = 971 }, -- Thisalee Crow / Choluna
        [193] = { [949] = 949 }, -- Tormmok
        [463] = { [941] = 941 }, -- Ulna Thresher
        [458] = { [976] = 976, [971] = 971 }, -- Vindicator Heluun / Cacklebone
        [216] = { [976] = 976, [1011] = 1011 }, -- Vivianne
        [179] = { [941] = 941 }, -- Weaponsmith Na'Shra
        [168] = { [948] = 948 }, -- Ziri'ak
    }

    Data.ZoneFollowers = {
        [988] = { [225] = 225 }, -- Blackrock Foundry
        [964] = { [177] = 177 }, -- Bloodmaul Slag Mines
        [941] = { [32] = 32, [34] = 34, [153] = 153, [179] = 179, [180] = 180, [182] = 182, [183] = 183, [184] = 184, [185] = 185, [186] = 186, [190] = 190, [463] = 463 }, -- Frostfire Ridge
        [976] = { [194] = 194, [195] = 195, [202] = 202, [216] = 216, [217] = 217, [458] = 458, [465] = 465 }, -- Frostwall
        [949] = { [159] = 159, [176] = 176, [189] = 189, [190] = 190, [193] = 193, [211] = 211, [212] = 212, [217] = 217 }, -- Gorgrond
        [1026] = { [474] = 474 }, -- Hellfire Citadel
        [971] = { [194] = 194, [202] = 202, [217] = 217, [458] = 458, [465] = 465 }, -- Lunarfall
        [950] = { [157] = 157, [170] = 170, [190] = 190, [209] = 209 }, -- Nagrand
        [321] = { [203] = 203 }, -- Orgrimmar
        [948] = { [168] = 168, [192] = 192, [204] = 204, [218] = 218, [219] = 219, [224] = 224, [453] = 453 }, -- Spires of Arak
        [1009] = { [460] = 460, [462] = 462, [467] = 467 }, -- Stormshield
        [301] = { [203] = 203 }, -- Stormwind City
        [946] = { [154] = 154, [155] = 155, [171] = 171, [190] = 190, [205] = 205, [207] = 207, [208] = 208, [466] = 466 }, -- Talador
        [945] = { [468] = 468, [580] = 580, [581] = 581, [582] = 582 }, -- Tanaan Jungle
        [995] = { [178] = 178, [455] = 455 }, -- Upper Blackrock Spire
        [1011] = { [216] = 216, [459] = 459, [460] = 460, [462] = 462, [467] = 467 }, -- Warspear
    }
else
    Data.FollowersZone = {
            [209] = { [950] = 950 }, -- Abu'gar
            [204] = { [948] = 948 }, -- Admiral Taylor
            [208] = { [946] = 946 }, -- Ahm
            [225] = { [988] = 988 }, -- Aknor Steelbringer
            [184] = { [947] = 947 }, -- Apprentice Artificer Andren
            [474] = { [1026] = 1026 }, -- Ariok
            [179] = { [947] = 947 }, -- Artificer Romuul
            [189] = { [949] = 949 }, -- Blook
            [153] = { [947] = 947 }, -- Bruma Swiftstone
            [459] = { [1009] = 1009 }, -- Cleric Maluuf
            [177] = { [964] = 964 }, -- Croman
            [32] = { [941] = 941 }, -- Dagg
            [463] = { [947] = 947 }, -- Daleera Moonfang
            [462] = { [1009] = 1009, [1011] = 1011 }, -- Dawnseeker Rukaryx
            [207] = { [946] = 946 }, -- Defender Illona / Aeda Brightdawn
            [216] = { [971] = 971, [1009] = 1009 }, -- Delvar Ironfist
            [581] = { [945] = 945 }, -- Dowser Bigspark / Dowser Goodwell
            [467] = { [1009] = 1009, [1011] = 1011 }, -- Fen Tao
            [180] = { [947] = 947 }, -- Fiona
            [466] = { [946] = 946 }, -- Garona Halforcen
            [211] = { [949] = 949 }, -- Glirin / Penny Clobberbottom
            [170] = { [950] = 950 }, -- Goldmane the Skinner
            [465] = { [976] = 976, [971] = 971 }, -- Harrison Jones
            [453] = { [948] = 948 }, -- Hulda Shadowblade / Dark Ranger Velonara
            [190] = { [941] = 941, [949] = 949, [950] = 950, [946] = 946 }, -- Image of Archmage Vargoth
            [192] = { [948] = 948 }, -- Kimzee Pinchwhistle
            [157] = { [950] = 950 }, -- Lantresor of the Blade
            [178] = { [995] = 995 }, -- Leeroy Jenkins
            [219] = { [948] = 948 }, -- Leorajh
            [154] = { [946] = 946 }, -- Magister Serena / Magister Krelas
            [203] = { [321] = 321, [301] = 301 }, -- Meatball
            [155] = { [946] = 946 }, -- Miall / Morketh Bladehowl
            [455] = { [995] = 995 }, -- Millhouse Manastorm
            [202] = { [976] = 976, [971] = 971 }, -- Nat Pagle
            [468] = { [945] = 945 }, -- Oronok Torn-heart
            [580] = { [945] = 945 }, -- Pallas
            [194] = { [976] = 976, [971] = 971 }, -- Phylarch the Evergreen
            [176] = { [949] = 949 }, -- Pitfighter Vaandaam / Bruto
            [171] = { [946] = 946 }, -- Pleasure-Bot 8000
            [460] = { [1009] = 1009, [1011] = 1011 }, -- Professor Felblast
            [34] = { [947] = 947 }, -- Qiana Moonshadow
            [185] = { [947] = 947 }, -- Rangari Chel
            [212] = { [949] = 949 }, -- Rangari Erdanii / Spirit of Bony Xuk
            [159] = { [949] = 949 }, -- Rangari Kaalya / Kaz the Shrieker
            [183] = { [947] = 947 }, -- Rulkan
            [182] = { [947] = 947 }, -- Shelly Hamby
            [582] = { [945] = 945 }, -- Solar Priest Vayx
            [205] = { [946] = 946 }, -- Soulbinder Tuulani
            [224] = { [948] = 948 }, -- Talon Guard Kurekk
            [218] = { [948] = 948 }, -- Talonpriest Ishaal
            [217] = { [976] = 976, [949] = 949, [971] = 971 }, -- Thisalee Crow / Choluna
            [193] = { [949] = 949 }, -- Tormmok
            [458] = { [976] = 976, [971] = 971 }, -- Vindicator Heluun / Cacklebone
            [186] = { [947] = 947 }, -- Vindicator Onaala
            [195] = { [971] = 971 }, -- Weldon Barov
            [168] = { [948] = 948 }, -- Ziri'ak
        }

    Data.ZoneFollowers = {
            [988] = { [225] = 225 }, -- Blackrock Foundry
            [964] = { [177] = 177 }, -- Bloodmaul Slag Mines
            [941] = { [32] = 32, [190] = 190 }, -- Frostfire Ridge
            [976] = { [194] = 194, [202] = 202, [217] = 217, [458] = 458, [465] = 465 }, -- Frostwall
            [949] = { [159] = 159, [176] = 176, [189] = 189, [190] = 190, [193] = 193, [211] = 211, [212] = 212, [217] = 217 }, -- Gorgrond
            [1026] = { [474] = 474 }, -- Hellfire Citadel
            [971] = { [194] = 194, [195] = 195, [202] = 202, [216] = 216, [217] = 217, [458] = 458, [465] = 465 }, -- Lunarfall
            [950] = { [157] = 157, [170] = 170, [190] = 190, [209] = 209 }, -- Nagrand
            [321] = { [203] = 203 }, -- Orgrimmar
            [947] = { [34] = 34, [153] = 153, [179] = 179, [180] = 180, [182] = 182, [183] = 183, [184] = 184, [185] = 185, [186] = 186, [463] = 463 }, -- Shadowmoon Valley
            [948] = { [168] = 168, [192] = 192, [204] = 204, [218] = 218, [219] = 219, [224] = 224, [453] = 453 }, -- Spires of Arak
            [1009] = { [216] = 216, [459] = 459, [460] = 460, [462] = 462, [467] = 467 }, -- Stormshield
            [301] = { [203] = 203 }, -- Stormwind City
            [946] = { [154] = 154, [155] = 155, [171] = 171, [190] = 190, [205] = 205, [207] = 207, [208] = 208, [466] = 466 }, -- Talador
            [945] = { [468] = 468, [580] = 580, [581] = 581, [582] = 582 }, -- Tanaan Jungle
            [995] = { [178] = 178, [455] = 455 }, -- Upper Blackrock Spire
            [1011] = { [460] = 460, [462] = 462, [467] = 467 }, -- Warspear
        }
end
