-- auto generated by collectmedb on 2019-11-30 21:58:58

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

if UnitFactionGroup("player") == "Horde" then
    Data.FollowersZone = {
        [209] = { [550] = 550 }, -- Abu'gar
        [208] = { [535] = 535 }, -- Ahm
        [225] = { [596] = 596 }, -- Aknor Steelbringer
        [195] = { [585] = 585 }, -- Alexi Barov
        [474] = { [661] = 661 }, -- Ariok
        [204] = { [542] = 542 }, -- Benjamin Gibb
        [189] = { [543] = 543 }, -- Blook
        [177] = { [573] = 573 }, -- Croman
        [32] = { [525] = 525 }, -- Dagg
        [462] = { [622] = 622, [624] = 624 }, -- Dawnseeker Rukaryx
        [207] = { [535] = 535 }, -- Defender Illona / Aeda Brightdawn
        [581] = { [534] = 534 }, -- Dowser Bigspark / Dowser Goodwell
        [467] = { [622] = 622, [624] = 624 }, -- Fen Tao
        [466] = { [535] = 535 }, -- Garona Halforcen
        [211] = { [543] = 543 }, -- Glirin / Penny Clobberbottom
        [170] = { [550] = 550 }, -- Goldmane the Skinner
        [186] = { [525] = 525 }, -- Greatmother Geyah
        [183] = { [525] = 525 }, -- Gronnstalker Rokash
        [465] = { [585] = 585, [579] = 579 }, -- Harrison Jones
        [453] = { [542] = 542 }, -- Hulda Shadowblade / Dark Ranger Velonara
        [190] = { [525] = 525, [543] = 543, [550] = 550, [535] = 535 }, -- Image of Archmage Vargoth
        [153] = { [525] = 525 }, -- Ka'la
        [184] = { [525] = 525 }, -- Kal'gor the Honorable
        [459] = { [624] = 624 }, -- Karg Bloodfury
        [192] = { [542] = 542 }, -- Kimzee Pinchwhistle
        [157] = { [550] = 550 }, -- Lantresor of the Blade
        [178] = { [616] = 616 }, -- Leeroy Jenkins
        [219] = { [542] = 542 }, -- Leorajh
        [185] = { [525] = 525 }, -- Lokra
        [154] = { [535] = 535 }, -- Magister Serena / Magister Krelas
        [203] = { [85] = 85, [84] = 84 }, -- Meatball
        [155] = { [535] = 535 }, -- Miall / Morketh Bladehowl
        [455] = { [616] = 616 }, -- Millhouse Manastorm
        [182] = { [525] = 525 }, -- Mulverick
        [202] = { [585] = 585, [579] = 579 }, -- Nat Pagle
        [34] = { [525] = 525 }, -- Olin Umberhide
        [468] = { [534] = 534 }, -- Oronok Torn-heart
        [580] = { [534] = 534 }, -- Pallas
        [194] = { [585] = 585, [579] = 579 }, -- Phylarch the Evergreen
        [176] = { [543] = 543 }, -- Pitfighter Vaandaam / Bruto
        [171] = { [535] = 535 }, -- Pleasure-Bot 8000
        [460] = { [622] = 622, [624] = 624 }, -- Professor Felblast
        [212] = { [543] = 543 }, -- Rangari Erdanii / Spirit of Bony Xuk
        [159] = { [543] = 543 }, -- Rangari Kaalya / Kaz the Shrieker
        [180] = { [525] = 525 }, -- Shadow Hunter Rala
        [582] = { [534] = 534 }, -- Solar Priest Vayx
        [205] = { [535] = 535 }, -- Soulbinder Tuulani
        [224] = { [542] = 542 }, -- Talon Guard Kurekk
        [218] = { [542] = 542 }, -- Talonpriest Ishaal
        [217] = { [585] = 585, [543] = 543, [579] = 579 }, -- Thisalee Crow / Choluna
        [193] = { [543] = 543 }, -- Tormmok
        [463] = { [525] = 525 }, -- Ulna Thresher
        [458] = { [585] = 585, [579] = 579 }, -- Vindicator Heluun / Cacklebone
        [216] = { [585] = 585, [624] = 624 }, -- Vivianne
        [179] = { [525] = 525 }, -- Weaponsmith Na'Shra
        [168] = { [542] = 542 }, -- Ziri'ak
    }

    Data.ZoneFollowers = {
        [596] = { [225] = 225 }, -- Blackrock Foundry
        [573] = { [177] = 177 }, -- Bloodmaul Slag Mines
        [525] = { [32] = 32, [186] = 186, [183] = 183, [190] = 190, [153] = 153, [184] = 184, [185] = 185, [182] = 182, [34] = 34, [180] = 180, [463] = 463, [179] = 179 }, -- Frostfire Ridge
        [585] = { [195] = 195, [465] = 465, [202] = 202, [194] = 194, [217] = 217, [458] = 458, [216] = 216 }, -- Frostwall
        [543] = { [189] = 189, [211] = 211, [190] = 190, [176] = 176, [212] = 212, [159] = 159, [217] = 217, [193] = 193 }, -- Gorgrond
        [661] = { [474] = 474 }, -- Hellfire Citadel
        [579] = { [465] = 465, [202] = 202, [194] = 194, [217] = 217, [458] = 458 }, -- Lunarfall
        [550] = { [209] = 209, [170] = 170, [190] = 190, [157] = 157 }, -- Nagrand
        [85] = { [203] = 203 }, -- Orgrimmar
        [542] = { [204] = 204, [453] = 453, [192] = 192, [219] = 219, [224] = 224, [218] = 218, [168] = 168 }, -- Spires of Arak
        [622] = { [462] = 462, [467] = 467, [460] = 460 }, -- Stormshield
        [84] = { [203] = 203 }, -- Stormwind City
        [535] = { [208] = 208, [207] = 207, [466] = 466, [190] = 190, [154] = 154, [155] = 155, [171] = 171, [205] = 205 }, -- Talador
        [534] = { [581] = 581, [468] = 468, [580] = 580, [582] = 582 }, -- Tanaan Jungle
        [616] = { [178] = 178, [455] = 455 }, -- Upper Blackrock Spire
        [624] = { [462] = 462, [467] = 467, [459] = 459, [460] = 460, [216] = 216 }, -- Warspear
    }
else
    Data.FollowersZone = {
            [209] = { [550] = 550 }, -- Abu'gar
            [204] = { [542] = 542 }, -- Admiral Taylor
            [208] = { [535] = 535 }, -- Ahm
            [225] = { [596] = 596 }, -- Aknor Steelbringer
            [184] = { [539] = 539 }, -- Apprentice Artificer Andren
            [474] = { [661] = 661 }, -- Ariok
            [179] = { [539] = 539 }, -- Artificer Romuul
            [189] = { [543] = 543 }, -- Blook
            [153] = { [539] = 539 }, -- Bruma Swiftstone
            [459] = { [622] = 622 }, -- Cleric Maluuf
            [177] = { [573] = 573 }, -- Croman
            [32] = { [525] = 525 }, -- Dagg
            [463] = { [539] = 539 }, -- Daleera Moonfang
            [462] = { [622] = 622, [624] = 624 }, -- Dawnseeker Rukaryx
            [207] = { [535] = 535 }, -- Defender Illona / Aeda Brightdawn
            [216] = { [579] = 579, [622] = 622 }, -- Delvar Ironfist
            [581] = { [534] = 534 }, -- Dowser Bigspark / Dowser Goodwell
            [467] = { [622] = 622, [624] = 624 }, -- Fen Tao
            [180] = { [539] = 539 }, -- Fiona
            [466] = { [535] = 535 }, -- Garona Halforcen
            [211] = { [543] = 543 }, -- Glirin / Penny Clobberbottom
            [170] = { [550] = 550 }, -- Goldmane the Skinner
            [465] = { [585] = 585, [579] = 579 }, -- Harrison Jones
            [453] = { [542] = 542 }, -- Hulda Shadowblade / Dark Ranger Velonara
            [190] = { [525] = 525, [543] = 543, [550] = 550, [535] = 535 }, -- Image of Archmage Vargoth
            [192] = { [542] = 542 }, -- Kimzee Pinchwhistle
            [157] = { [550] = 550 }, -- Lantresor of the Blade
            [178] = { [616] = 616 }, -- Leeroy Jenkins
            [219] = { [542] = 542 }, -- Leorajh
            [154] = { [535] = 535 }, -- Magister Serena / Magister Krelas
            [203] = { [85] = 85, [84] = 84 }, -- Meatball
            [155] = { [535] = 535 }, -- Miall / Morketh Bladehowl
            [455] = { [616] = 616 }, -- Millhouse Manastorm
            [202] = { [585] = 585, [579] = 579 }, -- Nat Pagle
            [468] = { [534] = 534 }, -- Oronok Torn-heart
            [580] = { [534] = 534 }, -- Pallas
            [194] = { [585] = 585, [579] = 579 }, -- Phylarch the Evergreen
            [176] = { [543] = 543 }, -- Pitfighter Vaandaam / Bruto
            [171] = { [535] = 535 }, -- Pleasure-Bot 8000
            [460] = { [622] = 622, [624] = 624 }, -- Professor Felblast
            [34] = { [539] = 539 }, -- Qiana Moonshadow
            [185] = { [539] = 539 }, -- Rangari Chel
            [212] = { [543] = 543 }, -- Rangari Erdanii / Spirit of Bony Xuk
            [159] = { [543] = 543 }, -- Rangari Kaalya / Kaz the Shrieker
            [183] = { [539] = 539 }, -- Rulkan
            [182] = { [539] = 539 }, -- Shelly Hamby
            [582] = { [534] = 534 }, -- Solar Priest Vayx
            [205] = { [535] = 535 }, -- Soulbinder Tuulani
            [224] = { [542] = 542 }, -- Talon Guard Kurekk
            [218] = { [542] = 542 }, -- Talonpriest Ishaal
            [217] = { [585] = 585, [543] = 543, [579] = 579 }, -- Thisalee Crow / Choluna
            [193] = { [543] = 543 }, -- Tormmok
            [458] = { [585] = 585, [579] = 579 }, -- Vindicator Heluun / Cacklebone
            [186] = { [539] = 539 }, -- Vindicator Onaala
            [195] = { [579] = 579 }, -- Weldon Barov
            [168] = { [542] = 542 }, -- Ziri'ak
        }

    Data.ZoneFollowers = {
            [596] = { [225] = 225 }, -- Blackrock Foundry
            [573] = { [177] = 177 }, -- Bloodmaul Slag Mines
            [525] = { [32] = 32, [190] = 190 }, -- Frostfire Ridge
            [585] = { [465] = 465, [202] = 202, [194] = 194, [217] = 217, [458] = 458 }, -- Frostwall
            [543] = { [189] = 189, [211] = 211, [190] = 190, [176] = 176, [212] = 212, [159] = 159, [217] = 217, [193] = 193 }, -- Gorgrond
            [661] = { [474] = 474 }, -- Hellfire Citadel
            [579] = { [216] = 216, [465] = 465, [202] = 202, [194] = 194, [217] = 217, [458] = 458, [195] = 195 }, -- Lunarfall
            [550] = { [209] = 209, [170] = 170, [190] = 190, [157] = 157 }, -- Nagrand
            [85] = { [203] = 203 }, -- Orgrimmar
            [539] = { [184] = 184, [179] = 179, [153] = 153, [463] = 463, [180] = 180, [34] = 34, [185] = 185, [183] = 183, [182] = 182, [186] = 186 }, -- Shadowmoon Valley
            [542] = { [204] = 204, [453] = 453, [192] = 192, [219] = 219, [224] = 224, [218] = 218, [168] = 168 }, -- Spires of Arak
            [622] = { [459] = 459, [462] = 462, [216] = 216, [467] = 467, [460] = 460 }, -- Stormshield
            [84] = { [203] = 203 }, -- Stormwind City
            [535] = { [208] = 208, [207] = 207, [466] = 466, [190] = 190, [154] = 154, [155] = 155, [171] = 171, [205] = 205 }, -- Talador
            [534] = { [581] = 581, [468] = 468, [580] = 580, [582] = 582 }, -- Tanaan Jungle
            [616] = { [178] = 178, [455] = 455 }, -- Upper Blackrock Spire
            [624] = { [462] = 462, [467] = 467, [460] = 460 }, -- Warspear
        }
end
