-- auto generated by collectmedb on 2014-10-25 15:35:26

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

Data.Toys = {}


Data.Toys[86589] = {
    zones  = { 858  }
} -- Ai'lis Skymirror
Data.Toys[113570] = {
    zones  = { 947  }
} -- Ancient's Bloom
Data.Toys[117550] = {
    zones  = { 947  }
} -- Angry Beehive
Data.Toys[108735] = {
    zones  = { 941  }
} -- Arena Master's Warhorn
Data.Toys[46843] = {
    zones  = { 492  }
} -- Argent Crusader's Banner
Data.Toys[90067] = {
    zones  = { 810  }
} -- B.F.F Necklace
Data.Toys[119178] = {
    zones  = { 947  }
} -- Black Whirlwind
Data.Toys[104302] = {
    zones  = { 951  }
} -- Blackflame Daggers
Data.Toys[115503] = {
    zones  = { 941  }
} -- Blazin Diamon Pendant
Data.Toys[113096] = {
    zones  = { 948  }
} -- Bloodmane Charm
Data.Toys[119432] = {
    zones  = { 949  }
} -- Botani Camouflage
Data.Toys[34686] = {
    zones  = { 381, 321, 471, 362, 341, 480, 301, 382  }
} -- Brazier of Dancing Flames
Data.Toys[114227] = {
    zones  = { 949  }
} -- Bubble Wand
Data.Toys[116122] = {
    zones  = { 946  }
} -- Burning Legion Missive
Data.Toys[103685] = {
    zones  = { 951  }
} -- Celestial Defender's Medallion
Data.Toys[86575] = {
    zones  = { 811  }
} -- Chalice of Secrets
Data.Toys[89222] = {
    zones  = { 806  }
} -- Cloud Ring
Data.Toys[88589] = {
    zones  = { 810  }
} -- Cremating Torch
Data.Toys[90899] = {
    zones  = { 823  }
} -- Darkmoon Whistle
Data.Toys[45021] = {
    zones  = { 492  }
} -- Darnassus Banner
Data.Toys[108743] = {
    zones  = { 946  }
} -- Deceptia's Smoldering Boots
Data.Toys[21540] = {
    zones  = { 241  }
} -- Elune's Lantern
Data.Toys[104309] = {
    zones  = { 951  }
} -- Eternal Kiln
Data.Toys[45020] = {
    zones  = { 492  }
} -- Exodar Banner
Data.Toys[53057] = {
    zones  = { 181  }
} -- Faded Wizard Hat
Data.Toys[86581] = {
    zones  = { 809  }
} -- Farwater Conch
Data.Toys[119145] = {
    zones  = { 941  }
} -- Firefury Totem
Data.Toys[88801] = {
    zones  = { 807  }
} -- Flippable Table
Data.Toys[104324] = {
    zones  = { 321, 301, 504  }
} -- Foot Ball
Data.Toys[88802] = {
    zones  = { 807  }
} -- Foxzcopter Controller
Data.Toys[44719] = {
    zones  = { 493  }
} -- Frenzyheard Brew
Data.Toys[98136] = {
    zones  = { 930  }
} -- Ghastropod Shell
Data.Toys[117569] = {
    zones  = { 946  }
} -- Giant Deathweb Egg
Data.Toys[90175] = {
    zones  = { 807  }
} -- Gin-Ji Knife Set
Data.Toys[95589] = {
    zones  = { 928  }
} -- Glorious Standard of the Kirin Tor Offenseive
Data.Toys[95590] = {
    zones  = { 928  }
} -- Glorious Standard of the Sunreaver Onslaught
Data.Toys[45019] = {
    zones  = { 492  }
} -- Gnomeregan Banner
Data.Toys[88417] = {
    zones  = { 858  }
} -- Gokk'lok's Shell
Data.Toys[118716] = {
    zones  = { 949  }
} -- Goren Garb
Data.Toys[69895] = {
    zones  = { 321, 301  }
} -- Green Balloon
Data.Toys[116139] = {
    zones  = { 823  }
} -- Haunting Memento
Data.Toys[119210] = {
    zones  = { 976, 971  }
} -- Hearthstone Board
Data.Toys[86593] = {
    zones  = { 858  }
} -- Hozen Beach Ball
Data.Toys[88385] = {
    zones  = { 809  }
} -- Hozen Idol
Data.Toys[113631] = {
    zones  = { 947  }
} -- Hypnosis Googles
Data.Toys[43499] = {
    zones  = { 495  }
} -- Iron Boot Flask
Data.Toys[118244] = {
    zones  = { 950  }
} -- Iron Buccanee's Hat
Data.Toys[45018] = {
    zones  = { 492  }
} -- Ironforge Banner
Data.Toys[88579] = {
    zones  = { 809  }
} -- Jin Warmkeg's Brew
Data.Toys[68806] = {
    zones  = { 181  }
} -- Kalytha's Haunted Locket
Data.Toys[86571] = {
    zones  = { 811  }
} -- Kang's Bindstone
Data.Toys[88580] = {
    zones  = { 857  }
} -- Ken-Ken's Mask
Data.Toys[116125] = {
    zones  = { 946  }
} -- Klikixx's Webspinner
Data.Toys[88566] = {
    zones  = { 763  }
} -- Krastinov's Bag of Horrors
Data.Toys[88531] = {
    zones  = { 809  }
} -- Lao Chin's Last Mug
Data.Toys[71259] = {
    zones  = { 795  }
} -- Leyara's Locket
Data.Toys[119039] = {
    zones  = { 976, 971  }
} -- Lilians Warning Sign
Data.Toys[118938] = {
    zones  = { 976, 971  }
} -- Manastorm Duplicator

