-- auto generated by collectmedb on 2014-10-25 16:38:10

local CollectMe = LibStub("AceAddon-3.0"):GetAddon("CollectMe")
local Data = CollectMe:GetModule("Data")

Data.Toys = {
    [86589] = {
        zones  = { [858] = 858 }
    }, -- Ai'lis Skymirror
    [113570] = {
        zones  = { [947] = 947 }
    }, -- Ancient's Bloom
    [117550] = {
        zones  = { [947] = 947 }
    }, -- Angry Beehive
    [108735] = {
        zones  = { [941] = 941 }
    }, -- Arena Master's Warhorn
    [46843] = {
        zones  = { [492] = 492 }
    }, -- Argent Crusader's Banner
    [90067] = {
        zones  = { [810] = 810 }
    }, -- B.F.F Necklace
    [119178] = {
        zones  = { [947] = 947 }
    }, -- Black Whirlwind
    [104302] = {
        zones  = { [951] = 951 }
    }, -- Blackflame Daggers
    [115503] = {
        zones  = { [941] = 941 }
    }, -- Blazin Diamon Pendant
    [113096] = {
        zones  = { [948] = 948 }
    }, -- Bloodmane Charm
    [119432] = {
        zones  = { [949] = 949 }
    }, -- Botani Camouflage
    [34686] = {
        zones  = { [381] = 381, [321] = 321, [471] = 471, [362] = 362, [341] = 341, [480] = 480, [301] = 301, [382] = 382 }
    }, -- Brazier of Dancing Flames
    [114227] = {
        zones  = { [949] = 949 }
    }, -- Bubble Wand
    [116122] = {
        zones  = { [946] = 946 }
    }, -- Burning Legion Missive
    [103685] = {
        zones  = { [951] = 951 }
    }, -- Celestial Defender's Medallion
    [86575] = {
        zones  = { [811] = 811 }
    }, -- Chalice of Secrets
    [89222] = {
        zones  = { [806] = 806 }
    }, -- Cloud Ring
    [88589] = {
        zones  = { [810] = 810 }
    }, -- Cremating Torch
    [90899] = {
        zones  = { [823] = 823 }
    }, -- Darkmoon Whistle
    [45021] = {
        zones  = { [492] = 492 }
    }, -- Darnassus Banner
    [108743] = {
        zones  = { [946] = 946 }
    }, -- Deceptia's Smoldering Boots
    [21540] = {
        zones  = { [241] = 241 }
    }, -- Elune's Lantern
    [104309] = {
        zones  = { [951] = 951 }
    }, -- Eternal Kiln
    [45020] = {
        zones  = { [492] = 492 }
    }, -- Exodar Banner
    [53057] = {
        zones  = { [181] = 181 }
    }, -- Faded Wizard Hat
    [86581] = {
        zones  = { [809] = 809 }
    }, -- Farwater Conch
    [119145] = {
        zones  = { [941] = 941 }
    }, -- Firefury Totem
    [88801] = {
        zones  = { [807] = 807 }
    }, -- Flippable Table
    [104324] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- Foot Ball
    [88802] = {
        zones  = { [807] = 807 }
    }, -- Foxzcopter Controller
    [44719] = {
        zones  = { [493] = 493 }
    }, -- Frenzyheard Brew
    [98136] = {
        zones  = { [930] = 930 }
    }, -- Ghastropod Shell
    [117569] = {
        zones  = { [946] = 946 }
    }, -- Giant Deathweb Egg
    [90175] = {
        zones  = { [807] = 807 }
    }, -- Gin-Ji Knife Set
    [95589] = {
        zones  = { [928] = 928 }
    }, -- Glorious Standard of the Kirin Tor Offenseive
    [95590] = {
        zones  = { [928] = 928 }
    }, -- Glorious Standard of the Sunreaver Onslaught
    [45019] = {
        zones  = { [492] = 492 }
    }, -- Gnomeregan Banner
    [88417] = {
        zones  = { [858] = 858 }
    }, -- Gokk'lok's Shell
    [118716] = {
        zones  = { [949] = 949 }
    }, -- Goren Garb
    [69895] = {
        zones  = { [321] = 321, [301] = 301 }
    }, -- Green Balloon
    [116139] = {
        zones  = { [823] = 823 }
    }, -- Haunting Memento
    [119210] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Hearthstone Board
    [86593] = {
        zones  = { [858] = 858 }
    }, -- Hozen Beach Ball
    [88385] = {
        zones  = { [809] = 809 }
    }, -- Hozen Idol
    [113631] = {
        zones  = { [947] = 947 }
    }, -- Hypnosis Googles
    [43499] = {
        zones  = { [495] = 495 }
    }, -- Iron Boot Flask
    [118244] = {
        zones  = { [950] = 950 }
    }, -- Iron Buccanee's Hat
    [45018] = {
        zones  = { [492] = 492 }
    }, -- Ironforge Banner
    [88579] = {
        zones  = { [809] = 809 }
    }, -- Jin Warmkeg's Brew
    [68806] = {
        zones  = { [181] = 181 }
    }, -- Kalytha's Haunted Locket
    [86571] = {
        zones  = { [811] = 811 }
    }, -- Kang's Bindstone
    [88580] = {
        zones  = { [857] = 857 }
    }, -- Ken-Ken's Mask
    [116125] = {
        zones  = { [946] = 946 }
    }, -- Klikixx's Webspinner
    [88566] = {
        zones  = { [763] = 763 }
    }, -- Krastinov's Bag of Horrors
    [88531] = {
        zones  = { [809] = 809 }
    }, -- Lao Chin's Last Mug
    [71259] = {
        zones  = { [795] = 795 }
    }, -- Leyara's Locket
    [119039] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Lilians Warning Sign
    [118938] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Manastorm Duplicator
    [113670] = {
        zones  = { [946] = 946 }
    }, -- Mournful Moan of Murmur
    [86568] = {
        zones  = { [811] = 811 }
    }, -- Mr. Smite's Brass COmpass
    [52201] = {
        zones  = { [604] = 604 }
    }, -- Muradin's Favor
    [70161] = {
        zones  = { [795] = 795 }
    }, -- Mushroom Chair
    [70159] = {
        zones  = { [795] = 795 }
    }, -- Mylunes Call
    [86596] = {
        zones  = { [857] = 857 }
    }, -- Nat's Fishing Chair
    [104262] = {
        zones  = { [951] = 951 }
    }, -- Odd Polished Stone
    [35275] = {
        zones  = { [798] = 798 }
    }, -- Orb of the Sin'dorei
    [45014] = {
        zones  = { [492] = 492 }
    }, -- Orgrimmar Banner
    [120276] = {
        zones  = { [950] = 950 }
    }, -- Outrider's Bridle Chain
    [90427] = {
        zones  = { [4] = 4, [321] = 321, [27] = 27, [341] = 341 }
    }, -- Pandaren Brewpack
    [86588] = {
        zones  = { [809] = 809 }
    }, -- Pandaren Firework Launcher
    [89869] = {
        zones  = { [807] = 807 }
    }, -- Pandaren Scarecrow
    [86586] = {
        zones  = { [811] = 811 }
    }, -- Panflute of Pandaria
    [115468] = {
        zones  = { [976] = 976 }
    }, -- Permanent Frost Essence
    [118221] = {
        zones  = { [949] = 949 }
    }, -- Petrification Stone
    [30690] = {
        zones  = { [475] = 475 }
    }, -- Power Converter
    [108739] = {
        zones  = { [941] = 941 }
    }, -- Pretty Draenor Pearl
    [88370] = {
        zones  = { [807] = 807 }
    }, -- Puntable Marmot
    [104294] = {
        zones  = { [951] = 951 }
    }, -- Rime of the Time-Lost Mariner
    [45015] = {
        zones  = { [492] = 492 }
    }, -- Sen'Jin Banner
    [98132] = {
        zones  = { [930] = 930 }
    }, -- Shado-Pan Geysyr Gun
    [88387] = {
        zones  = { [857] = 857 }
    }, -- Shushen's Spittoon
    [45017] = {
        zones  = { [492] = 492 }
    }, -- Silvermoon City Banner
    [88381] = {
        zones  = { [809] = 809 }
    }, -- Silversage Incense
    [118222] = {
        zones  = { [949] = 949 }
    }, -- Spirit of Bashiok
    [91904] = {
        zones  = { [807] = 807 }
    }, -- Stackable Stag
    [109739] = {
        zones  = { [947] = 947 }
    }, -- Star Chart
    [66888] = {
        zones  = { [182] = 182 }
    }, -- Stave of Fur and Claw
    [111476] = {
        zones  = { [941] = 941 }
    }, -- Stolen Breath
    [45011] = {
        zones  = { [492] = 492 }
    }, -- Stormwind Banner
    [52253] = {
        zones  = { [604] = 604 }
    }, -- Sylvana's Music Box
    [80822] = {
        zones  = { [857] = 857 }
    }, -- The Golden Banana
    [104323] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- The Pigskin
    [45013] = {
        zones  = { [492] = 492 }
    }, -- Thunder Bluff Banner
    [119160] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Tickle Totem
    [32782] = {
        zones  = { [478] = 478 }
    }, -- Time-Lost Figurine
    [54438] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- Tiny Blue Ragdoll
    [54437] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- Tiny Green Ragdoll
    [44430] = {
        zones  = { [504] = 504 }
    }, -- Titanium Seal of Dalaran
    [64997] = {
        zones  = { [708] = 708, [709] = 709 }
    }, -- Tol Barad Searchlight
    [63141] = {
        zones  = { [708] = 708, [709] = 709 }
    }, -- Tol Barad Searchlight
    [88584] = {
        zones  = { [810] = 810 }
    }, -- Totem of Harmoy
    [119144] = {
        zones  = { [947] = 947 }
    }, -- Touch of the Naaru
    [44606] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- Toy Train Set
    [88377] = {
        zones  = { [807] = 807 }
    }, -- Turnip Paint Gun
    [45016] = {
        zones  = { [492] = 492 }
    }, -- Undercity Banner
    [113375] = {
        zones  = { [947] = 947 }
    }, -- Vindicator's Armor Polish Kit
    [119003] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Void Totem
    [104331] = {
        zones  = { [951] = 951 }
    }, -- Warning Sign
    [117573] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Wayfarer's Bonfire
    [45057] = {
        zones  = { [321] = 321, [301] = 301, [504] = 504 }
    }, -- Wind-Up Train Wrecker
    [119212] = {
        zones  = { [976] = 976, [971] = 971 }
    }, -- Winning Hand
}
